UNITS = [
    {
        "name": "Scientific Foundations of Psychology",
        "description": "Introduces psychology as a science, its history and major perspectives, and the research methods and ethical standards used to study behavior and mental processes.",
        "ap_weight_min": 10.0,
        "ap_weight_max": 14.0,
        "display_order": 1,
        "topics": [
            {
                "name": "Introducing Psychology",
                "description": "The definition of psychology and its emergence as a scientific discipline.",
                "skill_tags": ["history-of-psychology"],
                "display_order": 1,
            },
            {
                "name": "Perspectives in Psychology",
                "description": "Major theoretical perspectives, including biological, cognitive, humanistic, and sociocultural approaches.",
                "skill_tags": ["theoretical-perspectives"],
                "display_order": 2,
            },
            {
                "name": "Psychological Research Methods",
                "description": "Experimental, correlational, and descriptive research designs and their strengths and limitations.",
                "skill_tags": ["research-methods"],
                "display_order": 3,
            },
            {
                "name": "Statistical Analysis in Psychology",
                "description": "Descriptive and inferential statistics used to summarize and interpret psychological data.",
                "skill_tags": ["statistics"],
                "display_order": 4,
            },
            {
                "name": "Ethical Guidelines in Psychology",
                "description": "Ethical standards governing research with human and animal participants.",
                "skill_tags": ["research-ethics"],
                "display_order": 5,
            },
        ],
    },
    {
        "name": "Biological Bases of Behavior",
        "description": "Examines the nervous and endocrine systems, brain structures, and genetic and evolutionary influences on behavior.",
        "ap_weight_min": 8.0,
        "ap_weight_max": 10.0,
        "display_order": 2,
        "topics": [
            {
                "name": "Interaction of Heredity and Environment",
                "description": "How genetics and environmental factors jointly shape behavior and traits.",
                "skill_tags": ["nature-vs-nurture"],
                "display_order": 1,
            },
            {
                "name": "The Endocrine System",
                "description": "Hormones and glands that regulate bodily functions and influence behavior.",
                "skill_tags": ["endocrine-system"],
                "display_order": 2,
            },
            {
                "name": "Overview of the Nervous System and the Neuron",
                "description": "Structure and function of neurons and the organization of the nervous system.",
                "skill_tags": ["neuron-structure"],
                "display_order": 3,
            },
            {
                "name": "Neurotransmitters",
                "description": "How neurotransmitters affect behavior, mood, and cognition.",
                "skill_tags": ["neurotransmitters"],
                "display_order": 4,
            },
            {
                "name": "The Brain",
                "description": "Structures and functions of the brain, including localization of function.",
                "skill_tags": ["brain-structures"],
                "display_order": 5,
            },
            {
                "name": "Tools to Examine Brain Structure and Function",
                "description": "Techniques such as EEG, CT, MRI, and fMRI used to study the brain.",
                "skill_tags": ["neuroimaging"],
                "display_order": 6,
            },
        ],
    },
    {
        "name": "Sensation and Perception",
        "description": "Covers how sensory systems detect stimuli and how the brain organizes and interprets sensory information.",
        "ap_weight_min": 6.0,
        "ap_weight_max": 8.0,
        "display_order": 3,
        "topics": [
            {
                "name": "Principles of Sensation",
                "description": "Thresholds, sensory adaptation, and signal detection theory.",
                "skill_tags": ["sensory-thresholds"],
                "display_order": 1,
            },
            {
                "name": "Principles of Perception",
                "description": "Attention, perceptual set, and top-down versus bottom-up processing.",
                "skill_tags": ["perceptual-processing"],
                "display_order": 2,
            },
            {
                "name": "The Visual System",
                "description": "Structures of the eye and theories of color vision.",
                "skill_tags": ["visual-system"],
                "display_order": 3,
            },
            {
                "name": "Visual Perception",
                "description": "Depth perception, perceptual constancies, and Gestalt principles of organization.",
                "skill_tags": ["gestalt-principles"],
                "display_order": 4,
            },
            {
                "name": "The Auditory System",
                "description": "Structures of the ear and theories of pitch perception.",
                "skill_tags": ["auditory-system"],
                "display_order": 5,
            },
            {
                "name": "Chemical Senses, Touch, Kinesthesis, and Vestibular Sense",
                "description": "Taste, smell, touch, body position, and balance senses.",
                "skill_tags": ["chemical-senses"],
                "display_order": 6,
            },
        ],
    },
    {
        "name": "Learning",
        "description": "Explores how organisms acquire new behaviors through classical conditioning, operant conditioning, and observational learning.",
        "ap_weight_min": 7.0,
        "ap_weight_max": 9.0,
        "display_order": 4,
        "topics": [
            {
                "name": "Classical Conditioning",
                "description": "Pavlovian conditioning, including acquisition, extinction, generalization, and discrimination.",
                "skill_tags": ["classical-conditioning"],
                "display_order": 1,
            },
            {
                "name": "Operant Conditioning",
                "description": "Reinforcement, punishment, and schedules of reinforcement.",
                "skill_tags": ["operant-conditioning"],
                "display_order": 2,
            },
            {
                "name": "Social and Cognitive Factors in Learning",
                "description": "Observational learning, modeling, and cognitive perspectives such as latent learning and insight.",
                "skill_tags": ["observational-learning"],
                "display_order": 3,
            },
        ],
    },
    {
        "name": "Cognitive Psychology",
        "description": "Focuses on memory, thinking, problem solving, language, and intelligence.",
        "ap_weight_min": 13.0,
        "ap_weight_max": 17.0,
        "display_order": 5,
        "topics": [
            {
                "name": "Introduction to Memory",
                "description": "The three-stage model of memory: sensory, short-term, and long-term memory.",
                "skill_tags": ["memory-models"],
                "display_order": 1,
            },
            {
                "name": "Encoding",
                "description": "How information is encoded into memory, including levels of processing and mnemonic devices.",
                "skill_tags": ["encoding"],
                "display_order": 2,
            },
            {
                "name": "Storing",
                "description": "Long-term potentiation and the biological basis of storing memories.",
                "skill_tags": ["memory-storage"],
                "display_order": 3,
            },
            {
                "name": "Retrieving",
                "description": "Retrieval cues, forgetting, and memory construction/reconstruction, including source amnesia and misinformation effect.",
                "skill_tags": ["memory-retrieval"],
                "display_order": 4,
            },
            {
                "name": "Biases and Errors in Thinking",
                "description": "Cognitive biases and heuristics that influence decision making and problem solving, such as availability bias, confirmation bias, and fixation.",
                "skill_tags": ["cognitive-biases"],
                "display_order": 5,
            },
            {
                "name": "Psychometric Principles",
                "description": "Theories of intelligence and the reliability, validity, standardization, and norms used in psychological testing.",
                "skill_tags": ["test-validity-reliability"],
                "display_order": 6,
            },
        ],
    },
    {
        "name": "Developmental Psychology",
        "description": "Studies physical, cognitive, social, and moral development across the lifespan.",
        "ap_weight_min": 7.0,
        "ap_weight_max": 9.0,
        "display_order": 6,
        "topics": [
            {
                "name": "Theories of Development",
                "description": "Major research designs and issues in developmental psychology, such as nature versus nurture and continuity versus stages.",
                "skill_tags": ["developmental-theories"],
                "display_order": 1,
            },
            {
                "name": "Influences on Development",
                "description": "Prenatal development and influences of genetics and environment on physical and cognitive development.",
                "skill_tags": ["prenatal-development"],
                "display_order": 2,
            },
            {
                "name": "Moral Development",
                "description": "Kohlberg's stages of moral reasoning.",
                "skill_tags": ["kohlberg-moral-development"],
                "display_order": 3,
            },
            {
                "name": "Social Development",
                "description": "Attachment styles, parenting styles, and Erikson's psychosocial stages.",
                "skill_tags": ["attachment-theory"],
                "display_order": 4,
            },
            {
                "name": "Gender and Sexual Orientation",
                "description": "Influences on gender identity, gender roles, and sexual orientation.",
                "skill_tags": ["gender-development"],
                "display_order": 5,
            },
        ],
    },
    {
        "name": "Motivation, Emotion, and Personality",
        "description": "Covers theories of motivation, the components of emotion, stress, and major theories of personality.",
        "ap_weight_min": 11.0,
        "ap_weight_max": 15.0,
        "display_order": 7,
        "topics": [
            {
                "name": "Theories of Motivation",
                "description": "Instinct, drive-reduction, arousal, and incentive theories of motivation.",
                "skill_tags": ["motivation-theories"],
                "display_order": 1,
            },
            {
                "name": "Specific Topics in Motivation",
                "description": "Hunger, sexual motivation, and social motivation such as achievement.",
                "skill_tags": ["hunger-motivation"],
                "display_order": 2,
            },
            {
                "name": "Theories of Emotion",
                "description": "James-Lange, Cannon-Bard, and Schachter-Singer two-factor theories of emotion.",
                "skill_tags": ["emotion-theories"],
                "display_order": 3,
            },
            {
                "name": "Stress and Coping",
                "description": "Sources of stress and adaptive versus maladaptive coping strategies.",
                "skill_tags": ["stress-coping"],
                "display_order": 4,
            },
            {
                "name": "Introduction to Personality",
                "description": "Psychoanalytic, humanistic, trait, social-cognitive, and biological theories of personality.",
                "skill_tags": ["personality-theories"],
                "display_order": 5,
            },
            {
                "name": "Personality Assessment",
                "description": "Self-report inventories and projective tests used to measure personality.",
                "skill_tags": ["personality-assessment"],
                "display_order": 6,
            },
        ],
    },
    {
        "name": "Clinical Psychology",
        "description": "Addresses the definition and classification of psychological disorders and approaches to treatment.",
        "ap_weight_min": 13.0,
        "ap_weight_max": 17.0,
        "display_order": 8,
        "topics": [
            {
                "name": "Introduction to Psychological Disorders",
                "description": "Defining and classifying psychological disorders using the DSM.",
                "skill_tags": ["disorder-classification"],
                "display_order": 1,
            },
            {
                "name": "Psychological Perspectives and Etiology of Disorders",
                "description": "Biological, psychological, and sociocultural explanations for the origins of disorders.",
                "skill_tags": ["disorder-etiology"],
                "display_order": 2,
            },
            {
                "name": "Anxiety Disorders, OCD, and PTSD",
                "description": "Symptoms and features of anxiety-related, obsessive-compulsive, and trauma disorders.",
                "skill_tags": ["anxiety-disorders"],
                "display_order": 3,
            },
            {
                "name": "Depressive and Bipolar Disorders",
                "description": "Symptoms and features of major depressive disorder, persistent depressive disorder, and bipolar disorders.",
                "skill_tags": ["mood-disorders"],
                "display_order": 4,
            },
            {
                "name": "Schizophrenia",
                "description": "Positive and negative symptoms and features of schizophrenia spectrum disorders, along with dissociative and personality disorders.",
                "skill_tags": ["schizophrenia"],
                "display_order": 5,
            },
            {
                "name": "Treatment of Disorders",
                "description": "Overview of biomedical, psychodynamic, and behavioral approaches to treatment, including specific psychotherapy modalities and their effectiveness.",
                "skill_tags": ["psychotherapy"],
                "display_order": 6,
            },
        ],
    },
    {
        "name": "Social Psychology",
        "description": "Examines how individuals' thoughts, feelings, and behaviors are influenced by the presence and actions of others.",
        "ap_weight_min": 8.0,
        "ap_weight_max": 10.0,
        "display_order": 9,
        "topics": [
            {
                "name": "Attribution Theory and Person Perception",
                "description": "Situational versus dispositional attributions and the fundamental attribution error.",
                "skill_tags": ["attribution-theory"],
                "display_order": 1,
            },
            {
                "name": "Attitude Formation and Attitude Change",
                "description": "How attitudes form and change, including cognitive dissonance theory.",
                "skill_tags": ["cognitive-dissonance"],
                "display_order": 2,
            },
            {
                "name": "Conformity, Compliance, and Obedience",
                "description": "Classic studies on social influence, including Asch, Milgram, and Zimbardo.",
                "skill_tags": ["conformity-obedience"],
                "display_order": 3,
            },
            {
                "name": "Group Influences on Behavior and Mental Processes",
                "description": "Social facilitation, social loafing, groupthink, and group polarization.",
                "skill_tags": ["group-dynamics"],
                "display_order": 4,
            },
            {
                "name": "Prosocial Behavior, Aggression, Altruism",
                "description": "Bystander effect, aggression, and the factors that promote helping behavior.",
                "skill_tags": ["prosocial-behavior"],
                "display_order": 5,
            },
            {
                "name": "Interpersonal Attraction",
                "description": "Factors influencing attraction, relationships, and prejudice and discrimination.",
                "skill_tags": ["interpersonal-attraction"],
                "display_order": 6,
            },
        ],
    },
]
