"""Demo-scale AP Biology question bank for seeding. Not exhaustive — a
modest set (~3-4 MCQ per unit plus a handful of FRQs) intended to exercise
the app's end-to-end flows. Every unit_name/topic_name pair here must match
a name defined in units_topics/biology.py exactly."""

QUESTIONS = [
    # ---------------------------------------------------------------
    # Unit 1: Chemistry of Life
    # ---------------------------------------------------------------
    {
        "unit_name": "Chemistry of Life",
        "topic_name": "Structure of Water and Hydrogen Bonding",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Which property of water allows it to move upward through the xylem of a tall tree against gravity?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["water-properties", "cohesion-adhesion"],
        "misconception_tags": ["confuses-cohesion-with-adhesion"],
        "options": [
            {"label": "A", "text": "Water's high specific heat capacity", "is_correct": False},
            {"label": "B", "text": "Cohesion between water molecules and adhesion to xylem walls", "is_correct": True},
            {"label": "C", "text": "Water's ability to dissociate into H+ and OH- ions", "is_correct": False},
            {"label": "D", "text": "The low density of ice relative to liquid water", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Specific heat capacity relates to water resisting temperature change, not to capillary movement through a plant.", "misconception_tag": "confuses-cohesion-with-adhesion"},
            {"option_label": "B", "explanation": "Correct. Hydrogen bonds cause water molecules to stick to each other (cohesion) and to the polar xylem walls (adhesion), producing capillary action.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Dissociation into ions is related to pH, not to the tension-cohesion mechanism of water transport.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Ice density relative to liquid water explains why ice floats, which is unrelated to capillary action in plants.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Chemistry of Life",
        "topic_name": "Introduction to Biological Macromolecules",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "A student observes that a large macromolecule breaks down into smaller subunits when water is added, with each bond broken adding one water molecule. This process is best described as:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["hydrolysis", "dehydration-synthesis"],
        "misconception_tags": ["reverses-hydrolysis-and-dehydration-synthesis"],
        "options": [
            {"label": "A", "text": "Hydrolysis", "is_correct": True},
            {"label": "B", "text": "Dehydration synthesis", "is_correct": False},
            {"label": "C", "text": "Condensation reaction", "is_correct": False},
            {"label": "D", "text": "Phosphorylation", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Hydrolysis uses water to break a bond between monomers, releasing the subunits.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Dehydration synthesis is the reverse process: it builds polymers by removing water, not adding it.", "misconception_tag": "reverses-hydrolysis-and-dehydration-synthesis"},
            {"option_label": "C", "explanation": "A condensation reaction is another name for dehydration synthesis, which releases water rather than consuming it.", "misconception_tag": "reverses-hydrolysis-and-dehydration-synthesis"},
            {"option_label": "D", "explanation": "Phosphorylation involves adding a phosphate group, which is unrelated to breaking a polymer with water.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Chemistry of Life",
        "topic_name": "Structure and Function of Enzymes",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "An enzyme's reaction rate increases as substrate concentration rises, then plateaus even as more substrate is added. What best explains the plateau?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["enzyme-kinetics", "saturation"],
        "misconception_tags": ["thinks-enzymes-are-consumed-in-reaction"],
        "options": [
            {"label": "A", "text": "The enzyme is being permanently consumed by the reaction", "is_correct": False},
            {"label": "B", "text": "The substrate has become denatured at high concentrations", "is_correct": False},
            {"label": "C", "text": "All available active sites are saturated with substrate", "is_correct": True},
            {"label": "D", "text": "The reaction has reached chemical equilibrium", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Enzymes are catalysts and are not consumed or permanently altered by the reactions they catalyze.", "misconception_tag": "thinks-enzymes-are-consumed-in-reaction"},
            {"option_label": "B", "explanation": "Denaturation is caused by factors like extreme pH or temperature, not by high substrate concentration itself.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Once every active site is continuously occupied, adding more substrate cannot increase the rate further.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Equilibrium refers to forward and reverse reaction rates being equal, which is a different concept from enzyme saturation.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Chemistry of Life",
        "topic_name": "Properties of Biological Macromolecules",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A missense mutation changes a single hydrophobic amino acid in the interior of a globular protein to a hydrophilic one. Which level of protein structure is most directly disrupted first?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["protein-folding", "structure-levels"],
        "misconception_tags": ["thinks-primary-structure-mutation-cannot-affect-folding"],
        "options": [
            {"label": "A", "text": "Primary structure only, with no effect on folding", "is_correct": False},
            {"label": "B", "text": "Secondary structure, by breaking peptide bonds", "is_correct": False},
            {"label": "C", "text": "Tertiary structure, by disrupting hydrophobic interactions that drive folding", "is_correct": True},
            {"label": "D", "text": "Quaternary structure only, since a single subunit change cannot affect internal folding", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The primary structure (amino acid sequence) does change, but the question asks which structural level's folding is disrupted as a consequence.", "misconception_tag": "thinks-primary-structure-mutation-cannot-affect-folding"},
            {"option_label": "B", "explanation": "Secondary structure is stabilized by hydrogen bonds along the backbone, not by peptide bonds, and this substitution primarily disrupts hydrophobic packing.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Tertiary structure depends heavily on hydrophobic interior residues clustering away from water; replacing one with a hydrophilic residue disrupts this packing.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Quaternary structure describes interactions between multiple subunits, but a single internal residue change disrupts folding within one subunit first.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 2: Cell Structure and Function
    # ---------------------------------------------------------------
    {
        "unit_name": "Cell Structure and Function",
        "topic_name": "Cell Size",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "As a spherical cell increases in radius, which of the following best describes the change in its surface area-to-volume ratio?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["surface-area-to-volume"],
        "misconception_tags": ["thinks-surface-area-and-volume-scale-equally"],
        "options": [
            {"label": "A", "text": "It increases, since surface area increases faster than volume", "is_correct": False},
            {"label": "B", "text": "It decreases, since volume increases faster than surface area", "is_correct": True},
            {"label": "C", "text": "It stays constant, since both scale with radius equally", "is_correct": False},
            {"label": "D", "text": "It becomes unpredictable without knowing the cell's shape", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reverses the actual relationship: volume (r^3) grows faster than surface area (r^2) as radius increases.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Because volume scales with r^3 and surface area with r^2, the ratio of surface area to volume shrinks as a cell grows larger.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Surface area and volume do not scale equally with radius, so the ratio is not constant.", "misconception_tag": "thinks-surface-area-and-volume-scale-equally"},
            {"option_label": "D", "explanation": "The relationship is mathematically predictable from geometry regardless of the specific cell shape's proportions.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cell Structure and Function",
        "topic_name": "Membrane Permeability and Transport",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A plant cell is placed in a hypertonic solution. Which outcome is most likely to occur?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["osmosis", "tonicity"],
        "misconception_tags": ["reverses-hypertonic-and-hypotonic-effects"],
        "options": [
            {"label": "A", "text": "The cell will swell and burst as water rushes in", "is_correct": False},
            {"label": "B", "text": "Water will move into the cell, increasing turgor pressure", "is_correct": False},
            {"label": "C", "text": "No net water movement will occur because the cell wall prevents osmosis", "is_correct": False},
            {"label": "D", "text": "The cell membrane will pull away from the cell wall as water exits (plasmolysis)", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Swelling and bursting would occur in a hypotonic solution where water enters the cell, the opposite of this scenario.", "misconception_tag": "reverses-hypertonic-and-hypotonic-effects"},
            {"option_label": "B", "explanation": "In a hypertonic solution, water leaves the cell rather than entering it, so turgor pressure decreases rather than increases.", "misconception_tag": "reverses-hypertonic-and-hypotonic-effects"},
            {"option_label": "C", "explanation": "The cell wall provides structural support but does not block osmotic water movement across the membrane.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct. In a hypertonic environment, water leaves the cell by osmosis, causing the plasma membrane to pull away from the rigid cell wall.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cell Structure and Function",
        "topic_name": "Plasma Membranes",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "According to the fluid mosaic model, the phospholipid bilayer of a cell membrane arranges itself so that:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["membrane-structure"],
        "misconception_tags": ["reverses-hydrophilic-hydrophobic-orientation"],
        "options": [
            {"label": "A", "text": "Hydrophilic heads face the watery interior and exterior, while hydrophobic tails face each other", "is_correct": True},
            {"label": "B", "text": "Hydrophobic heads face outward toward water, while hydrophilic tails face inward", "is_correct": False},
            {"label": "C", "text": "Both heads and tails are hydrophilic, allowing water to pass freely", "is_correct": False},
            {"label": "D", "text": "The bilayer is a rigid, static structure with fixed protein positions", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. The polar hydrophilic heads orient toward the aqueous cytoplasm and extracellular fluid, while the nonpolar hydrophobic tails cluster together, shielded from water.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This reverses the actual orientation; the heads (not tails) are hydrophilic and face water.", "misconception_tag": "reverses-hydrophilic-hydrophobic-orientation"},
            {"option_label": "C", "explanation": "The tails are hydrophobic, not hydrophilic, which is precisely why the membrane is selectively permeable rather than freely permeable to water-soluble substances.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The 'fluid' in fluid mosaic model refers to the lateral movement of lipids and proteins, not a rigid fixed structure.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cell Structure and Function",
        "topic_name": "Cell Structure: Subcellular Components",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A cell biologist finds a cell type with an unusually extensive smooth endoplasmic reticulum. This cell most likely specializes in:",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["organelles", "structure-function"],
        "misconception_tags": ["confuses-rough-and-smooth-er-functions"],
        "options": [
            {"label": "A", "text": "Synthesizing and secreting large quantities of protein hormones", "is_correct": False},
            {"label": "B", "text": "Detoxifying drugs and synthesizing lipids", "is_correct": True},
            {"label": "C", "text": "Packaging and modifying proteins for secretion", "is_correct": False},
            {"label": "D", "text": "Generating ATP through oxidative phosphorylation", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Protein synthesis and secretion are primarily associated with the rough ER (ribosome-studded), not the smooth ER.", "misconception_tag": "confuses-rough-and-smooth-er-functions"},
            {"option_label": "B", "explanation": "Correct. Smooth ER lacks ribosomes and specializes in lipid synthesis, calcium storage, and detoxification of drugs and toxins, notably in liver cells.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Packaging and modifying proteins for secretion is the role of the Golgi apparatus, not the smooth ER.", "misconception_tag": None},
            {"option_label": "D", "explanation": "ATP generation via oxidative phosphorylation occurs in the mitochondria, not the smooth ER.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 3: Cellular Energetics
    # ---------------------------------------------------------------
    {
        "unit_name": "Cellular Energetics",
        "topic_name": "Cellular Respiration",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "In which part of the mitochondrion does the electron transport chain occur?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["electron-transport-chain", "mitochondria"],
        "misconception_tags": ["confuses-mitochondrial-matrix-with-inner-membrane"],
        "options": [
            {"label": "A", "text": "The outer mitochondrial membrane", "is_correct": False},
            {"label": "B", "text": "The mitochondrial matrix", "is_correct": False},
            {"label": "C", "text": "The inner mitochondrial membrane", "is_correct": True},
            {"label": "D", "text": "The intermembrane space", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The outer membrane is relatively permeable and does not house the electron transport chain complexes.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The matrix is where the Krebs cycle occurs, but the electron transport chain proteins are embedded in the inner membrane, not free in the matrix.", "misconception_tag": "confuses-mitochondrial-matrix-with-inner-membrane"},
            {"option_label": "C", "explanation": "Correct. The electron transport chain complexes and ATP synthase are embedded in the inner mitochondrial membrane, where the proton gradient is established.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The intermembrane space accumulates protons pumped across the inner membrane but does not contain the electron transport chain proteins themselves.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cellular Energetics",
        "topic_name": "Photosynthesis",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "If a plant is exposed to light of a wavelength that chlorophyll does not absorb well (e.g., pure green light), what is the most likely effect on the light-dependent reactions?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["light-reactions", "pigments"],
        "misconception_tags": ["thinks-all-light-wavelengths-are-equally-absorbed"],
        "options": [
            {"label": "A", "text": "The rate of electron excitation and ATP/NADPH production will decrease", "is_correct": True},
            {"label": "B", "text": "The rate will be unaffected, since all wavelengths of visible light are absorbed equally", "is_correct": False},
            {"label": "C", "text": "The Calvin cycle will speed up to compensate", "is_correct": False},
            {"label": "D", "text": "The plant will switch to cellular respiration to generate ATP instead", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Chlorophyll a and b absorb mostly red and blue light and reflect green light, so green light excites far fewer electrons, reducing ATP and NADPH output.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Absorption spectra show chlorophyll absorbs red and blue light much more strongly than green light, so wavelengths are not absorbed equally.", "misconception_tag": "thinks-all-light-wavelengths-are-equally-absorbed"},
            {"option_label": "C", "explanation": "The Calvin cycle depends on ATP and NADPH from the light reactions, so it would slow down, not speed up, if light reactions are impaired.", "misconception_tag": None},
            {"option_label": "D", "explanation": "A plant cell does not substitute cellular respiration for photosynthesis simply because light absorption is reduced; respiration continues independently at its normal rate.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cellular Energetics",
        "topic_name": "Coupled Reactions and ATP",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Why is ATP considered a useful 'energy currency' for the cell?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["atp", "energy-coupling"],
        "misconception_tags": ["thinks-atp-stores-energy-long-term"],
        "options": [
            {"label": "A", "text": "It stores large amounts of energy for long-term use, like fat", "is_correct": False},
            {"label": "B", "text": "Its terminal phosphate bond can be readily hydrolyzed to release energy for immediate cellular work", "is_correct": True},
            {"label": "C", "text": "It is only produced during photosynthesis", "is_correct": False},
            {"label": "D", "text": "It cannot be regenerated once used, requiring constant new synthesis from glucose", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "ATP is meant for short-term, immediate energy transfer; long-term energy storage is handled by molecules like fats and glycogen.", "misconception_tag": "thinks-atp-stores-energy-long-term"},
            {"option_label": "B", "explanation": "Correct. ATP's phosphate bonds are readily hydrolyzed, releasing usable energy quickly to power immediate cellular processes.", "misconception_tag": None},
            {"option_label": "C", "explanation": "ATP is produced in many processes, including cellular respiration in nearly all living cells, not just photosynthesis.", "misconception_tag": None},
            {"option_label": "D", "explanation": "ATP is continuously regenerated from ADP and phosphate through respiration, forming a rapid recycling cycle rather than requiring only new synthesis from glucose each time.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 4: Cell Communication and Cell Cycle
    # ---------------------------------------------------------------
    {
        "unit_name": "Cell Communication and Cell Cycle",
        "topic_name": "Cell Cycle",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "During which phase of the cell cycle does DNA replication occur?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["cell-cycle", "dna-replication"],
        "misconception_tags": ["thinks-dna-replicates-during-mitosis"],
        "options": [
            {"label": "A", "text": "G1 phase", "is_correct": False},
            {"label": "B", "text": "S phase", "is_correct": True},
            {"label": "C", "text": "G2 phase", "is_correct": False},
            {"label": "D", "text": "M phase", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "G1 is a growth phase where the cell increases in size and synthesizes proteins, but DNA replication has not yet begun.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. S phase stands for 'synthesis' phase, during which the entire genome is replicated.", "misconception_tag": None},
            {"option_label": "C", "explanation": "G2 occurs after DNA replication is complete, as the cell prepares for mitosis.", "misconception_tag": None},
            {"option_label": "D", "explanation": "M phase (mitosis) segregates already-replicated chromosomes; it does not replicate DNA itself.", "misconception_tag": "thinks-dna-replicates-during-mitosis"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cell Communication and Cell Cycle",
        "topic_name": "Regulation of Cell Cycle",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A cell with a mutated p53 gene fails to halt the cell cycle despite significant DNA damage. This is most likely to result in:",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["checkpoints", "tumor-suppressors", "cancer"],
        "misconception_tags": ["thinks-p53-is-an-oncogene-rather-than-tumor-suppressor"],
        "options": [
            {"label": "A", "text": "Immediate apoptosis of all surrounding healthy cells", "is_correct": False},
            {"label": "B", "text": "Permanent arrest of the cell in G0 phase", "is_correct": False},
            {"label": "C", "text": "Enhanced DNA repair efficiency to compensate", "is_correct": False},
            {"label": "D", "text": "Accumulation of mutations and potential uncontrolled cell division (cancer)", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The mutation affects the cell carrying the damaged DNA, not surrounding healthy cells, which are unaffected by this specific mutation.", "misconception_tag": None},
            {"option_label": "B", "explanation": "A functioning p53 might trigger arrest or apoptosis, but a mutated, non-functional p53 fails to do this, allowing the cycle to continue rather than arrest.", "misconception_tag": None},
            {"option_label": "C", "explanation": "p53 helps trigger repair mechanisms and checkpoints; a loss-of-function mutation reduces, not enhances, the cell's ability to manage DNA damage.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct. p53 is a tumor suppressor that normally halts the cycle to allow repair or triggers apoptosis; its loss allows damaged cells to keep dividing, accumulating mutations that can lead to cancer.", "misconception_tag": "thinks-p53-is-an-oncogene-rather-than-tumor-suppressor"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cell Communication and Cell Cycle",
        "topic_name": "Introduction to Signal Transduction",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In a signal transduction pathway, a hydrophilic hormone binds to a receptor on the outside of the target cell rather than entering the cell directly. This is best explained by the fact that:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["signal-transduction", "receptors"],
        "misconception_tags": ["thinks-all-hormones-cross-membrane-directly"],
        "options": [
            {"label": "A", "text": "Hydrophilic signals cannot easily cross the hydrophobic core of the plasma membrane", "is_correct": True},
            {"label": "B", "text": "All signaling molecules are too large to pass through membrane channels", "is_correct": False},
            {"label": "C", "text": "Surface receptors are only used when the target cell lacks a nucleus", "is_correct": False},
            {"label": "D", "text": "Hydrophilic hormones are always broken down before reaching the cell surface", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Because the membrane interior is hydrophobic, polar or charged (hydrophilic) signaling molecules cannot easily diffuse through and instead bind surface receptors.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Size is not the primary factor here; it is the molecule's polarity/hydrophilicity that prevents it from crossing the lipid bilayer.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Surface receptors are used by many nucleated cells for hydrophilic signals; the presence or absence of a nucleus is not the determining factor.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Hydrophilic hormones reach the cell surface intact; they are not systematically degraded before binding their receptors.", "misconception_tag": "thinks-all-hormones-cross-membrane-directly"},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 5: Heredity
    # ---------------------------------------------------------------
    {
        "unit_name": "Heredity",
        "topic_name": "Meiosis and Genetic Diversity",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which event during meiosis I is primarily responsible for creating new combinations of alleles on a single chromosome that did not exist in either parent?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["crossing-over", "genetic-variation"],
        "misconception_tags": ["confuses-crossing-over-with-independent-assortment"],
        "options": [
            {"label": "A", "text": "Independent assortment of homologous chromosomes", "is_correct": False},
            {"label": "B", "text": "Random fertilization of gametes", "is_correct": False},
            {"label": "C", "text": "Crossing over between non-sister chromatids", "is_correct": True},
            {"label": "D", "text": "Cytokinesis following telophase I", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Independent assortment shuffles which whole chromosomes end up together in a gamete, but it does not recombine alleles within a single chromosome.", "misconception_tag": "confuses-crossing-over-with-independent-assortment"},
            {"option_label": "B", "explanation": "Random fertilization creates new combinations of chromosomes between two parents' gametes, not new allele combinations within one chromosome.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Crossing over exchanges segments between non-sister chromatids of homologous chromosomes, creating recombinant chromosomes with new allele combinations.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Cytokinesis is simply cell division and does not itself create genetic recombination.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Heredity",
        "topic_name": "Non-Mendelian Genetics",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A cross between a red-flowered plant (R1R1) and a white-flowered plant (R2R2) produces all pink-flowered offspring (R1R2). This inheritance pattern is an example of:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["incomplete-dominance"],
        "misconception_tags": ["confuses-incomplete-dominance-with-codominance"],
        "options": [
            {"label": "A", "text": "Incomplete dominance, where the heterozygous phenotype blends both alleles", "is_correct": True},
            {"label": "B", "text": "Codominance, where both alleles are fully and separately expressed", "is_correct": False},
            {"label": "C", "text": "Simple Mendelian dominance, where one allele completely masks the other", "is_correct": False},
            {"label": "D", "text": "Polygenic inheritance involving multiple genes", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. In incomplete dominance, the heterozygote shows an intermediate, blended phenotype (pink) rather than either parental phenotype.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Codominance would show both red and white patches or streaks distinctly (like in roan cattle), not a blended pink color.", "misconception_tag": "confuses-incomplete-dominance-with-codominance"},
            {"option_label": "C", "explanation": "Simple dominance would produce all red or all white offspring, not an intermediate phenotype.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This cross involves a single gene with two alleles, not multiple genes contributing additively as in polygenic traits.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Heredity",
        "topic_name": "Mendelian Genetics",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In a dihybrid cross between two heterozygous pea plants (AaBb x AaBb) where both genes assort independently, what fraction of offspring is expected to show both recessive phenotypes?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["dihybrid-cross", "punnett-squares"],
        "misconception_tags": ["miscalculates-dihybrid-ratio"],
        "options": [
            {"label": "A", "text": "1/2", "is_correct": False},
            {"label": "B", "text": "3/16", "is_correct": False},
            {"label": "C", "text": "9/16", "is_correct": False},
            {"label": "D", "text": "1/16", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This does not correspond to any category in the standard 9:3:3:1 dihybrid ratio.", "misconception_tag": "miscalculates-dihybrid-ratio"},
            {"option_label": "B", "explanation": "3/16 represents one of the single-recessive-trait categories (e.g., aaB_), not the double-recessive category.", "misconception_tag": "miscalculates-dihybrid-ratio"},
            {"option_label": "C", "explanation": "9/16 represents the fraction showing both dominant phenotypes, not both recessive.", "misconception_tag": "miscalculates-dihybrid-ratio"},
            {"option_label": "D", "explanation": "Correct. In the classic 9:3:3:1 ratio, only 1/16 of offspring are homozygous recessive for both genes (aabb), since each recessive trait alone has a 1/4 probability and 1/4 x 1/4 = 1/16.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 6: Gene Expression and Regulation
    # ---------------------------------------------------------------
    {
        "unit_name": "Gene Expression and Regulation",
        "topic_name": "Transcription and RNA Processing",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which of the following is a key difference between transcription in eukaryotes and the resulting mature mRNA?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["rna-splicing", "transcription"],
        "misconception_tags": ["thinks-introns-are-translated"],
        "options": [
            {"label": "A", "text": "Eukaryotic mRNA retains introns to increase protein diversity", "is_correct": False},
            {"label": "B", "text": "Eukaryotic pre-mRNA has introns spliced out before translation", "is_correct": True},
            {"label": "C", "text": "Eukaryotic mRNA is translated as it is being transcribed, like in prokaryotes", "is_correct": False},
            {"label": "D", "text": "Eukaryotic mRNA does not require a 5' cap or poly-A tail", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Introns are non-coding sequences that are removed, not retained, during RNA splicing; retaining them would typically disrupt the reading frame.", "misconception_tag": "thinks-introns-are-translated"},
            {"option_label": "B", "explanation": "Correct. Pre-mRNA splicing removes introns and joins exons together, and alternative splicing of exons (not introns) can increase protein diversity.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Because eukaryotic transcription occurs in the nucleus and translation in the cytoplasm, the two processes are separated in space and time, unlike in prokaryotes.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Eukaryotic mRNA requires both a 5' cap and poly-A tail for stability, export from the nucleus, and efficient translation.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Gene Expression and Regulation",
        "topic_name": "Regulation of Gene Expression",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "In the lac operon of E. coli, when lactose is absent and glucose is present, what is the state of the operon?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["operons", "gene-regulation"],
        "misconception_tags": ["thinks-repressor-and-activator-roles-are-interchangeable"],
        "options": [
            {"label": "A", "text": "The repressor is bound to the operator, blocking transcription", "is_correct": True},
            {"label": "B", "text": "The repressor is inactive, and transcription proceeds at a high rate", "is_correct": False},
            {"label": "C", "text": "CAP is bound to its site, strongly promoting transcription", "is_correct": False},
            {"label": "D", "text": "RNA polymerase transcribes the operon continuously regardless of repressor binding", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Without lactose, the active lac repressor binds the operator and physically blocks RNA polymerase, keeping the operon off.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The repressor is only inactivated (and released from the operator) when lactose (as allolactose) is present to bind it; without lactose, the repressor remains active.", "misconception_tag": "thinks-repressor-and-activator-roles-are-interchangeable"},
            {"option_label": "C", "explanation": "CAP promotes transcription only when glucose is low (via high cAMP); with glucose present, CAP is not actively bound, and here lactose is also absent so the operon is off regardless.", "misconception_tag": None},
            {"option_label": "D", "explanation": "RNA polymerase cannot transcribe the operon while the repressor physically occupies the operator site, blocking its access.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Gene Expression and Regulation",
        "topic_name": "Mutations",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A single nucleotide insertion occurs near the beginning of a gene's coding sequence. Compared to a single nucleotide substitution at the same position, the insertion is generally more harmful because it:",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["frameshift", "point-mutations"],
        "misconception_tags": ["thinks-all-mutations-equally-disruptive"],
        "options": [
            {"label": "A", "text": "Always changes the start codon into a stop codon", "is_correct": False},
            {"label": "B", "text": "Removes the gene entirely from the chromosome", "is_correct": False},
            {"label": "C", "text": "Shifts the reading frame, altering every codon downstream of the insertion", "is_correct": True},
            {"label": "D", "text": "Prevents RNA polymerase from binding to the promoter", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "An insertion does not necessarily create a stop codon at the start; its main effect is disrupting the reading frame for all downstream codons.", "misconception_tag": None},
            {"option_label": "B", "explanation": "An insertion adds a nucleotide but does not delete or remove the gene from the chromosome.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Because codons are read in triplets, inserting one nucleotide shifts the frame for every codon after it, typically scrambling the entire downstream protein, unlike a substitution which usually affects only one amino acid.", "misconception_tag": "thinks-all-mutations-equally-disruptive"},
            {"option_label": "D", "explanation": "The mutation is within the coding sequence, not the promoter, so it does not directly affect RNA polymerase binding to the promoter.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 7: Natural Selection
    # ---------------------------------------------------------------
    {
        "unit_name": "Natural Selection",
        "topic_name": "Population Genetics",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In a population at Hardy-Weinberg equilibrium, the frequency of the recessive allele (q) is 0.4. What is the expected frequency of heterozygous individuals?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["hardy-weinberg", "allele-frequency"],
        "misconception_tags": ["confuses-2pq-with-p-squared-or-q-squared"],
        "options": [
            {"label": "A", "text": "0.16", "is_correct": False},
            {"label": "B", "text": "0.48", "is_correct": True},
            {"label": "C", "text": "0.36", "is_correct": False},
            {"label": "D", "text": "0.4", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "0.16 is q^2, the frequency of the homozygous recessive genotype, not the heterozygous frequency.", "misconception_tag": "confuses-2pq-with-p-squared-or-q-squared"},
            {"option_label": "B", "explanation": "Correct. With q = 0.4, p = 0.6, so heterozygote frequency 2pq = 2(0.6)(0.4) = 0.48.", "misconception_tag": None},
            {"option_label": "C", "explanation": "0.36 is p^2, the frequency of the homozygous dominant genotype, not the heterozygous frequency.", "misconception_tag": "confuses-2pq-with-p-squared-or-q-squared"},
            {"option_label": "D", "explanation": "0.4 is simply the given allele frequency q, not the genotype frequency for heterozygotes.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Natural Selection",
        "topic_name": "Speciation",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Two populations of a fish species are separated by a newly formed waterfall, preventing gene flow between them. Over thousands of years they diverge into two species. This is an example of:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["speciation", "reproductive-isolation"],
        "misconception_tags": ["confuses-allopatric-and-sympatric-speciation"],
        "options": [
            {"label": "A", "text": "Allopatric speciation", "is_correct": True},
            {"label": "B", "text": "Sympatric speciation", "is_correct": False},
            {"label": "C", "text": "Adaptive radiation only, with no true speciation occurring", "is_correct": False},
            {"label": "D", "text": "Genetic drift without any speciation", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Allopatric speciation occurs when a physical barrier (the waterfall) geographically separates populations, preventing gene flow and allowing independent divergence.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Sympatric speciation occurs without geographic separation, while this scenario explicitly involves a physical barrier dividing the populations.", "misconception_tag": "confuses-allopatric-and-sympatric-speciation"},
            {"option_label": "C", "explanation": "The scenario describes divergence into two distinct species due to isolation, which is the definition of speciation, not merely radiation without speciation.", "misconception_tag": None},
            {"option_label": "D", "explanation": "While genetic drift may contribute to divergence, the populations forming two distinct species over time is speciation, not merely drift without speciation.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Natural Selection",
        "topic_name": "Evidence of Evolution",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "The forelimb bones of a human, whale, and bat share a similar underlying skeletal arrangement despite being used for very different functions (grasping, swimming, flying). These are examples of:",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["homologous-structures", "evolution-evidence"],
        "misconception_tags": ["confuses-homologous-with-analogous-structures"],
        "options": [
            {"label": "A", "text": "Analogous structures, resulting from convergent evolution", "is_correct": False},
            {"label": "B", "text": "Vestigial structures with no remaining function", "is_correct": False},
            {"label": "C", "text": "Homologous structures, indicating a shared common ancestor", "is_correct": True},
            {"label": "D", "text": "Coincidental similarities with no evolutionary significance", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Analogous structures share function due to convergent evolution but do not share the same underlying anatomical structure, which is the opposite of what's described here.", "misconception_tag": "confuses-homologous-with-analogous-structures"},
            {"option_label": "B", "explanation": "Vestigial structures have reduced or lost function, but these forelimbs are all fully functional for their respective uses.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Homologous structures share the same underlying anatomy inherited from a common ancestor, even when used for different functions.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The shared skeletal arrangement is strong evidence of evolutionary relationship, not mere coincidence.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 8: Ecology
    # ---------------------------------------------------------------
    {
        "unit_name": "Ecology",
        "topic_name": "Energy Flow Through Ecosystems",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Approximately what percentage of energy is typically transferred from one trophic level to the next in an ecosystem?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["trophic-levels", "energy-pyramid"],
        "misconception_tags": ["thinks-energy-transfer-between-trophic-levels-is-high"],
        "options": [
            {"label": "A", "text": "About 10%", "is_correct": True},
            {"label": "B", "text": "About 50%", "is_correct": False},
            {"label": "C", "text": "About 90%", "is_correct": False},
            {"label": "D", "text": "About 100%, since energy is conserved", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. On average, only about 10% of energy at one trophic level is passed on to the next; the rest is lost as heat or used for metabolism.", "misconception_tag": None},
            {"option_label": "B", "explanation": "50% greatly overestimates typical ecological energy transfer efficiency between trophic levels.", "misconception_tag": "thinks-energy-transfer-between-trophic-levels-is-high"},
            {"option_label": "C", "explanation": "90% would imply very little energy loss, which contradicts the substantial energy lost as metabolic heat at each level.", "misconception_tag": "thinks-energy-transfer-between-trophic-levels-is-high"},
            {"option_label": "D", "explanation": "While energy is conserved overall (first law of thermodynamics), most of it is lost as heat rather than being passed to the next trophic level as usable biomass.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Ecology",
        "topic_name": "Population Ecology",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A population growing according to the logistic growth model slows its growth rate as it approaches carrying capacity (K) primarily because of:",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["logistic-growth", "carrying-capacity"],
        "misconception_tags": ["thinks-exponential-growth-is-unlimited-in-real-populations"],
        "options": [
            {"label": "A", "text": "A fixed, unavoidable maximum reproductive rate built into the species' genome", "is_correct": False},
            {"label": "B", "text": "Random genetic drift reducing population size", "is_correct": False},
            {"label": "C", "text": "Predators completely eliminating population growth at a set population size", "is_correct": False},
            {"label": "D", "text": "Increasing competition for limited resources as population density rises", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The slowing growth rate is a response to environmental limits, not a fixed genetic maximum independent of the environment.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Genetic drift affects allele frequencies, not the density-dependent growth-rate slowdown described by the logistic model.", "misconception_tag": None},
            {"option_label": "C", "explanation": "While predation can be one density-dependent factor, the logistic model's general mechanism is broader resource limitation, not predation alone reaching a fixed cutoff.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct. As population density increases toward K, resources like food and space become limited, increasing competition and slowing the growth rate — a density-dependent effect.", "misconception_tag": "thinks-exponential-growth-is-unlimited-in-real-populations"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Ecology",
        "topic_name": "Community Ecology",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "A keystone predator is removed from an intertidal ecosystem, after which one competitively dominant prey species overtakes the habitat and outcompetes several other species, drastically reducing biodiversity. This outcome best illustrates:",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["keystone-species", "species-interactions"],
        "misconception_tags": ["thinks-keystone-species-must-be-abundant"],
        "options": [
            {"label": "A", "text": "Mutualism between the predator and its prey", "is_correct": False},
            {"label": "B", "text": "The keystone species' disproportionately large effect on community structure relative to its abundance", "is_correct": True},
            {"label": "C", "text": "Competitive exclusion caused directly by the predator's presence", "is_correct": False},
            {"label": "D", "text": "A density-independent limiting factor on the prey population", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Predation is not mutualism; the predator-prey relationship benefits the predator at the prey's expense, not both parties.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Keystone species exert effects on community structure far larger than their numbers alone would suggest; their removal can cause a cascade that drastically reduces biodiversity.", "misconception_tag": "thinks-keystone-species-must-be-abundant"},
            {"option_label": "C", "explanation": "Competitive exclusion occurs between the prey species themselves once the predator is removed, not because of the predator's direct presence.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This scenario describes a biotic interaction (predation and competition), not an abiotic density-independent factor like a storm or fire.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Free Response Questions (spread across units)
    # ---------------------------------------------------------------
    {
        "unit_name": "Cellular Energetics",
        "topic_name": "Photosynthesis",
        "type": "frq",
        "difficulty": 4,
        "prompt": "A researcher grows two groups of the same plant species under identical light and temperature conditions, except Group A receives normal atmospheric CO2 (0.04%) and Group B receives elevated CO2 (0.12%). After two weeks, Group B shows a significantly higher rate of starch accumulation in its leaves. Explain the biochemical mechanism by which increased CO2 availability leads to greater starch accumulation, referencing the relevant stage of photosynthesis and enzyme involved.",
        "correct_answer": "Increased CO2 provides more substrate for RuBisCO in the Calvin cycle (stroma), increasing the rate of carbon fixation into G3P, which is then used to synthesize more glucose and starch; also reduces photorespiration by favoring RuBisCO's carboxylase activity over its oxygenase activity.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["calvin-cycle", "rubisco", "photorespiration"],
        "misconception_tags": ["thinks-co2-is-used-in-light-reactions"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "A complete answer identifies that CO2 is fixed during the Calvin cycle (light-independent reactions) in the stroma, not the light reactions in the thylakoid. It should name RuBisCO as the enzyme that catalyzes carbon fixation, explain that higher CO2 concentration increases the rate at which RuBisCO fixes carbon into 3-carbon compounds (G3P), which are used to build glucose and starch, and ideally note that higher CO2 also reduces wasteful photorespiration by outcompeting O2 for RuBisCO's active site.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies the Calvin cycle (light-independent reactions) in the stroma as the site of CO2 fixation", "keywords": ["calvin cycle", "stroma", "light-independent"], "points": 1},
                {"point": "Names RuBisCO as the enzyme responsible for fixing CO2", "keywords": ["rubisco", "carbon fixation"], "points": 1},
                {"point": "Explains that more CO2 increases the rate of G3P/sugar production, supporting more starch synthesis", "keywords": ["g3p", "glucose", "starch", "rate"], "points": 1},
                {"point": "Connects to reduced photorespiration as an additional mechanism", "keywords": ["photorespiration", "oxygenase", "carboxylase"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Heredity",
        "topic_name": "Meiosis",
        "type": "frq",
        "difficulty": 3,
        "prompt": "A student claims that mitosis and meiosis are 'basically the same process' because both start with chromosome replication and end with cell division. Explain two key ways in which meiosis differs from mitosis that account for meiosis producing genetically diverse, haploid gametes rather than two genetically identical, diploid daughter cells.",
        "correct_answer": "Meiosis includes two rounds of division without an intervening replication (meiosis I and II), reducing chromosome number by half; and meiosis I involves pairing of homologous chromosomes with crossing over and independent assortment, generating genetic variation, neither of which occurs in mitosis.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["meiosis", "mitosis-comparison"],
        "misconception_tags": ["thinks-mitosis-and-meiosis-are-equivalent"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "A strong answer explains that meiosis consists of two successive divisions (meiosis I and II) with only one round of DNA replication, halving the chromosome number to produce haploid cells, unlike mitosis's single division that preserves the diploid number. It should also explain that during meiosis I, homologous chromosomes pair up (synapsis) and undergo crossing over, and that independent assortment of homologs occurs, both of which introduce genetic variation absent in mitosis, which produces genetically identical clones.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "States meiosis involves two divisions with one round of replication, halving chromosome number to produce haploid cells", "keywords": ["haploid", "two divisions", "meiosis i", "meiosis ii"], "points": 1},
                {"point": "States mitosis involves one division producing two diploid identical cells", "keywords": ["diploid", "identical", "mitosis"], "points": 1},
                {"point": "Explains crossing over between homologous chromosomes as a source of variation unique to meiosis", "keywords": ["crossing over", "homologous", "synapsis"], "points": 1},
                {"point": "Explains independent assortment of homologs as a second source of variation unique to meiosis", "keywords": ["independent assortment"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Natural Selection",
        "topic_name": "Introduction to Natural Selection",
        "type": "frq",
        "difficulty": 3,
        "prompt": "A population of beetles exhibits variation in shell color, from light tan to dark brown. After a wildfire blackens the ground in their habitat, researchers observe that dark brown beetles make up a much larger percentage of the population five generations later. Using the principles of natural selection, explain how this shift in the population's color distribution likely occurred. Do not describe this as beetles individually changing color to adapt.",
        "correct_answer": "Color variation already existed in the population due to heritable genetic differences; after the fire, dark beetles were better camouflaged from predators and survived/reproduced at higher rates than light beetles, so the allele(s) for dark color increased in frequency over generations (differential reproductive success), not because individual beetles changed color.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["natural-selection", "differential-survival"],
        "misconception_tags": ["thinks-individuals-adapt-during-their-lifetime"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "A complete answer notes that heritable variation in shell color already existed before the fire, that dark-colored beetles had a survival advantage post-fire due to camouflage from predators, that this led to differential survival and reproduction (natural selection), and that the allele frequency for dark coloration increased across generations as a population-level change — explicitly rejecting the idea that individual beetles changed color during their lifetimes.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "States that color variation was already present in the population due to heritable alleles before the fire", "keywords": ["heritable", "variation", "existed"], "points": 1},
                {"point": "Explains dark beetles had a survival/camouflage advantage against predators after the fire", "keywords": ["camouflage", "predators", "survival advantage"], "points": 1},
                {"point": "Explains differential reproductive success increased the frequency of the dark allele over generations", "keywords": ["reproductive success", "allele frequency", "generations"], "points": 1},
                {"point": "Explicitly clarifies selection acts on populations over generations, not individuals changing during their lifetime", "keywords": ["population", "not individual"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Ecology",
        "topic_name": "Disruptions to Ecosystems",
        "type": "frq",
        "difficulty": 2,
        "prompt": "An invasive plant species is introduced to a grassland ecosystem and rapidly outcompetes native plants for sunlight and soil nutrients. Describe one likely short-term effect on the native herbivore population that depended on the native plants, and explain the ecological mechanism behind this effect.",
        "correct_answer": "The native herbivore population would likely decline in the short term because its food source (native plants) becomes scarce as the invasive species outcompetes them, reducing the carrying capacity for herbivores dependent on the native plants and leading to starvation or emigration.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["invasive-species", "carrying-capacity", "food-web"],
        "misconception_tags": ["thinks-herbivores-can-instantly-switch-food-sources"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "A strong answer identifies a plausible short-term effect (e.g., decline in native herbivore population size) and links it mechanistically: the invasive plant reduces the abundance of the native food source, lowering the effective carrying capacity for herbivores that rely on it, which increases competition for remaining food and can cause starvation, reduced reproduction, or emigration — rather than assuming herbivores can immediately and fully switch to eating the invasive plant.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific, plausible short-term effect on the native herbivore population (e.g., decline in numbers)", "keywords": ["decline", "decrease", "population"], "points": 1},
                {"point": "Explains that the invasive plant reduces availability of the native food source", "keywords": ["outcompete", "food source", "resources"], "points": 1},
                {"point": "Connects reduced food availability to lowered carrying capacity and/or starvation for the herbivore population", "keywords": ["carrying capacity", "starvation", "resource limitation"], "points": 2},
            ]
        },
    },
    {
        "unit_name": "Gene Expression and Regulation",
        "topic_name": "Regulation of Gene Expression",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Two cells in the same multicellular organism, a liver cell and a skin cell, contain identical DNA sequences but produce very different sets of proteins. Explain how differential gene expression accounts for this difference, referencing at least one specific regulatory mechanism.",
        "correct_answer": "Even though the DNA is identical, different genes are transcribed in each cell type due to differential gene regulation, such as different transcription factors binding to different promoters/enhancers, or differences in chromatin structure (e.g., histone modification or DNA methylation) that make specific genes accessible or inaccessible for transcription in each cell type.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["gene-regulation", "differentiation", "epigenetics"],
        "misconception_tags": ["thinks-different-cell-types-have-different-dna"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "A complete answer explicitly states that the DNA sequence is the same in both cells, and that the different protein sets arise from differential gene expression: different transcription factors are present/active in each cell type, binding different promoters and enhancers to turn specific genes on or off, and/or chromatin modifications (histone acetylation/methylation, DNA methylation) make certain genes more or less accessible to transcription machinery in each cell type.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "States explicitly that the DNA sequence itself is identical between the two cell types", "keywords": ["identical dna", "same dna", "same sequence"], "points": 1},
                {"point": "Explains that different transcription factors regulate which genes are transcribed in each cell type", "keywords": ["transcription factors", "promoters", "enhancers"], "points": 1},
                {"point": "References a specific chromatin-level regulatory mechanism (e.g., histone modification, DNA methylation)", "keywords": ["chromatin", "methylation", "histone", "epigenetic"], "points": 2},
            ]
        },
    },
]
