"""Demo-scale AP Calculus AB question bank for seeding the database.

Not exhaustive -- a modest set (~3-4 MCQ per unit plus a handful of FRQs)
meant to exercise the app's flows end-to-end. Every unit_name/topic_name
pair below must match a unit/topic defined in
scripts/seed_data/units_topics/calculus_ab.py exactly.
"""

QUESTIONS = [
    # ------------------------------------------------------------------
    # Unit 1: Limits and Continuity
    # ------------------------------------------------------------------
    {
        "unit_name": "Limits and Continuity",
        "topic_name": "Defining Limits and Using Limit Notation",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Which of the following expressions correctly denotes 'the limit of f(x) as x approaches 3'?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["limits", "notation"],
        "misconception_tags": ["confuses-limit-with-function-value"],
        "options": [
            {"label": "A", "text": "f(3)", "is_correct": False},
            {"label": "B", "text": "f'(3)", "is_correct": False},
            {"label": "C", "text": "lim(x->3) f(x)", "is_correct": True},
            {"label": "D", "text": "integral of f(x) from 0 to 3", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "f(3) is the function value at x=3, not the limit; these can differ if f has a removable discontinuity there.", "misconception_tag": "confuses-limit-with-function-value"},
            {"option_label": "B", "explanation": "f'(3) denotes the derivative at x=3, an unrelated concept.", "misconception_tag": "confuses-derivative-with-limit"},
            {"option_label": "C", "explanation": "Correct. lim(x->3) f(x) is the standard notation for the limit of f as x approaches 3.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This is definite integral notation, not limit notation.", "misconception_tag": "confuses-integral-with-limit"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Limits and Continuity",
        "topic_name": "Determining Limits Using Algebraic Properties",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Find lim(x->2) (x^2 - 4)/(x - 2).",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["limits", "factoring"],
        "misconception_tags": ["plugs-in-value-causing-zero-division"],
        "options": [
            {"label": "A", "text": "0", "is_correct": False},
            {"label": "B", "text": "4", "is_correct": True},
            {"label": "C", "text": "Undefined", "is_correct": False},
            {"label": "D", "text": "2", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Incorrect; this would result from mistakenly evaluating the numerator alone at x=2 and dividing by a nonzero placeholder.", "misconception_tag": "arithmetic-error"},
            {"option_label": "B", "explanation": "Correct. Factor the numerator as (x-2)(x+2), cancel (x-2), then substitute x=2 into (x+2) to get 4.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The expression is undefined AT x=2, but the limit still exists because the (x-2) factor cancels before substitution.", "misconception_tag": "plugs-in-value-causing-zero-division"},
            {"option_label": "D", "explanation": "This confuses the input value (x=2) with the limit's output value.", "misconception_tag": "confuses-input-with-output"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Limits and Continuity",
        "topic_name": "Connecting Limits, Asymptotes, and Continuity",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Let f(x) = (3x^2 + 1)/(x^2 - 4). What is lim(x->infinity) f(x)?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["limits", "asymptotes", "end-behavior"],
        "misconception_tags": ["ignores-leading-coefficients-ratio"],
        "options": [
            {"label": "A", "text": "3", "is_correct": True},
            {"label": "B", "text": "1", "is_correct": False},
            {"label": "C", "text": "Infinity", "is_correct": False},
            {"label": "D", "text": "0", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. When numerator and denominator have the same degree, the limit at infinity is the ratio of leading coefficients: 3/1 = 3.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Incorrectly uses the constant terms (1 and -4 implicitly) rather than the leading coefficients.", "misconception_tag": "ignores-leading-coefficients-ratio"},
            {"option_label": "C", "explanation": "This would only be true if the numerator's degree exceeded the denominator's degree, which it does not here.", "misconception_tag": "misjudges-degree-comparison"},
            {"option_label": "D", "explanation": "This would only be true if the denominator's degree exceeded the numerator's degree.", "misconception_tag": "misjudges-degree-comparison"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Limits and Continuity",
        "topic_name": "Connecting Limits, Asymptotes, and Continuity",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A function g is defined as g(x) = x + 1 for x < 2, g(2) = 5, and g(x) = x^2 - 1 for x > 2. Is g continuous at x = 2?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["continuity", "piecewise-functions"],
        "misconception_tags": ["checks-only-one-sided-limit"],
        "options": [
            {"label": "A", "text": "Yes, because both pieces are polynomials.", "is_correct": False},
            {"label": "B", "text": "Yes, because g(2) is defined.", "is_correct": False},
            {"label": "C", "text": "No, because the left-hand limit does not exist.", "is_correct": False},
            {"label": "D", "text": "No, because the left- and right-hand limits both equal 3, but g(2) = 5.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Being built from polynomial pieces does not guarantee continuity at the boundary point; the pieces must also agree in value there.", "misconception_tag": "assumes-polynomial-implies-continuous-everywhere"},
            {"option_label": "B", "explanation": "g(2) being defined is necessary but not sufficient for continuity; it must also equal the limit as x approaches 2.", "misconception_tag": "checks-only-one-sided-limit"},
            {"option_label": "C", "explanation": "The left-hand limit does exist: as x->2^-, x+1 -> 3.", "misconception_tag": "arithmetic-error"},
            {"option_label": "D", "explanation": "Correct. lim(x->2^-) g(x) = 3 and lim(x->2^+) g(x) = 3, so the two-sided limit is 3, but g(2) = 5 != 3, so g is discontinuous (a removable discontinuity) at x=2.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 2: Differentiation: Definition and Fundamental Properties
    # ------------------------------------------------------------------
    {
        "unit_name": "Differentiation: Definition and Fundamental Properties",
        "topic_name": "Defining Average and Instantaneous Rates of Change",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "A car's position is given by s(t) = t^2 (in meters, t in seconds). What is the car's average velocity from t=1 to t=3?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["rates-of-change", "average-velocity"],
        "misconception_tags": ["confuses-average-rate-with-instantaneous-rate"],
        "options": [
            {"label": "A", "text": "2 m/s", "is_correct": False},
            {"label": "B", "text": "4 m/s", "is_correct": True},
            {"label": "C", "text": "6 m/s", "is_correct": False},
            {"label": "D", "text": "8 m/s", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is s'(1), the instantaneous velocity at t=1, not the average velocity over the interval.", "misconception_tag": "confuses-average-rate-with-instantaneous-rate"},
            {"option_label": "B", "explanation": "Correct. Average velocity = (s(3)-s(1))/(3-1) = (9-1)/2 = 4 m/s.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This is s'(3), the instantaneous velocity at t=3, not the average over the interval.", "misconception_tag": "confuses-average-rate-with-instantaneous-rate"},
            {"option_label": "D", "explanation": "This results from dividing the change in position by the wrong interval length (using 1 instead of 2).", "misconception_tag": "arithmetic-error"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differentiation: Definition and Fundamental Properties",
        "topic_name": "Defining the Derivative and Using Derivative Notation",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Using the limit definition of the derivative, f'(x) = lim(h->0) [f(x+h) - f(x)]/h, find f'(x) for f(x) = x^2 + 3x.",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["derivatives", "limit-definition"],
        "misconception_tags": ["drops-linear-term-when-expanding"],
        "options": [
            {"label": "A", "text": "2x + 3", "is_correct": True},
            {"label": "B", "text": "2x", "is_correct": False},
            {"label": "C", "text": "x^2 + 3", "is_correct": False},
            {"label": "D", "text": "2x + 3x", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Expanding f(x+h) = (x+h)^2 + 3(x+h), subtracting f(x), dividing by h, and letting h->0 gives 2x + 3.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This drops the derivative contribution of the linear term 3x, forgetting that its difference quotient contributes a constant 3.", "misconception_tag": "drops-linear-term-when-expanding"},
            {"option_label": "C", "explanation": "This looks like the original function's terms individually 'derived' incorrectly rather than applying the limit definition.", "misconception_tag": "misapplies-power-rule"},
            {"option_label": "D", "explanation": "This incorrectly keeps an h-independent x term multiplied by 3 rather than reducing 3x's contribution to the constant 3.", "misconception_tag": "algebra-error-in-difference-quotient"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differentiation: Definition and Fundamental Properties",
        "topic_name": "Connecting Differentiability and Continuity",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "At x = 0, the function f(x) = |x| is:",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["differentiability", "continuity"],
        "misconception_tags": ["assumes-continuity-implies-differentiability"],
        "options": [
            {"label": "A", "text": "Differentiable but not continuous", "is_correct": False},
            {"label": "B", "text": "Neither continuous nor differentiable", "is_correct": False},
            {"label": "C", "text": "Continuous but not differentiable", "is_correct": True},
            {"label": "D", "text": "Both continuous and differentiable", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Differentiability requires continuity, so a function cannot be differentiable without also being continuous.", "misconception_tag": "assumes-differentiability-without-continuity"},
            {"option_label": "B", "explanation": "|x| is continuous at x=0 since lim(x->0) |x| = 0 = f(0).", "misconception_tag": "misjudges-continuity-at-corner"},
            {"option_label": "C", "explanation": "Correct. |x| is continuous everywhere, but has a corner at x=0 where the left-hand derivative (-1) and right-hand derivative (1) disagree, so it is not differentiable there.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This assumes continuity implies differentiability, but a sharp corner can be continuous yet non-differentiable.", "misconception_tag": "assumes-continuity-implies-differentiability"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differentiation: Definition and Fundamental Properties",
        "topic_name": "Applying Basic Differentiation Rules",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Find the derivative of f(x) = 5x^4 - 2x^3 + 7.",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["derivatives", "power-rule"],
        "misconception_tags": ["forgets-derivative-of-constant-is-zero"],
        "options": [
            {"label": "A", "text": "20x^3 - 6x^2 + 7", "is_correct": False},
            {"label": "B", "text": "20x^3 - 6x^2", "is_correct": True},
            {"label": "C", "text": "5x^3 - 2x^2", "is_correct": False},
            {"label": "D", "text": "20x^3 - 6x^2 + 1", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The derivative of a constant (7) is 0, not 7 itself; this option incorrectly carries the constant through.", "misconception_tag": "forgets-derivative-of-constant-is-zero"},
            {"option_label": "B", "explanation": "Correct. Applying the power rule term by term: d/dx(5x^4)=20x^3, d/dx(-2x^3)=-6x^2, and d/dx(7)=0.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This forgets to multiply by the original exponent, only reducing the exponent without multiplying by it (power rule error).", "misconception_tag": "misapplies-power-rule"},
            {"option_label": "D", "explanation": "This incorrectly treats the derivative of the constant 7 as 1 rather than 0.", "misconception_tag": "forgets-derivative-of-constant-is-zero"},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 3: Differentiation: Composite, Implicit, and Inverse Functions
    # ------------------------------------------------------------------
    {
        "unit_name": "Differentiation: Composite, Implicit, and Inverse Functions",
        "topic_name": "The Chain Rule",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Find the derivative of f(x) = (3x + 1)^5.",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["chain-rule", "derivatives"],
        "misconception_tags": ["forgets-inner-derivative-in-chain-rule"],
        "options": [
            {"label": "A", "text": "15(3x + 1)^4", "is_correct": True},
            {"label": "B", "text": "5(3x + 1)^4", "is_correct": False},
            {"label": "C", "text": "5(3x + 1)^4 * 3x", "is_correct": False},
            {"label": "D", "text": "15x(3x + 1)^4", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. By the chain rule, f'(x) = 5(3x+1)^4 * 3 = 15(3x+1)^4.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This applies the outer power rule correctly but forgets to multiply by the derivative of the inner function (3x+1)' = 3.", "misconception_tag": "forgets-inner-derivative-in-chain-rule"},
            {"option_label": "C", "explanation": "This incorrectly multiplies by the inner function's variable term (3x) rather than its derivative (3).", "misconception_tag": "confuses-inner-function-with-its-derivative"},
            {"option_label": "D", "explanation": "This incorrectly distributes an extra factor of x into the coefficient instead of just multiplying by the constant derivative 3.", "misconception_tag": "algebra-error-applying-chain-rule"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differentiation: Composite, Implicit, and Inverse Functions",
        "topic_name": "Implicit Differentiation",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Given x^2 + y^2 = 25, find dy/dx.",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["implicit-differentiation"],
        "misconception_tags": ["forgets-dy-dx-factor-on-y-terms"],
        "options": [
            {"label": "A", "text": "dy/dx = y/x", "is_correct": False},
            {"label": "B", "text": "dy/dx = 2x", "is_correct": False},
            {"label": "C", "text": "dy/dx = -x/y", "is_correct": True},
            {"label": "D", "text": "dy/dx = x/y", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This incorrectly inverts the ratio and drops the sign; differentiating x^2+y^2=25 does not produce this form.", "misconception_tag": "algebra-error-isolating-dy-dx"},
            {"option_label": "B", "explanation": "This differentiates only the x^2 term, treating y as a constant instead of a function of x and dropping the y^2 term's contribution entirely.", "misconception_tag": "forgets-dy-dx-factor-on-y-terms"},
            {"option_label": "C", "explanation": "Correct. Differentiating both sides: 2x + 2y(dy/dx) = 0, so dy/dx = -2x/(2y) = -x/y.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This makes a sign error when isolating dy/dx, dropping the negative sign from -2x.", "misconception_tag": "sign-error-isolating-dy-dx"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differentiation: Composite, Implicit, and Inverse Functions",
        "topic_name": "Differentiating Inverse Trigonometric Functions",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Find the derivative of f(x) = arctan(2x).",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["inverse-trig", "chain-rule"],
        "misconception_tags": ["forgets-chain-rule-with-inverse-trig-formula"],
        "options": [
            {"label": "A", "text": "1/(1 + 4x^2)", "is_correct": False},
            {"label": "B", "text": "2/(1 + x^2)", "is_correct": False},
            {"label": "C", "text": "1/(1 + x^2)", "is_correct": False},
            {"label": "D", "text": "2/(1 + 4x^2)", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This correctly substitutes 2x into the denominator formula 1/(1+u^2) but forgets to multiply by the chain-rule factor du/dx = 2.", "misconception_tag": "forgets-chain-rule-with-inverse-trig-formula"},
            {"option_label": "B", "explanation": "This multiplies by the chain-rule factor 2 but forgets to substitute u=2x into the denominator, using x^2 instead of (2x)^2.", "misconception_tag": "forgets-substitution-in-denominator"},
            {"option_label": "C", "explanation": "This is the derivative of arctan(x), ignoring the inner function 2x entirely.", "misconception_tag": "ignores-inner-function-entirely"},
            {"option_label": "D", "explanation": "Correct. d/dx[arctan(u)] = u'/(1+u^2); with u=2x, u'=2, giving 2/(1+4x^2).", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 4: Contextual Applications of Differentiation
    # ------------------------------------------------------------------
    {
        "unit_name": "Contextual Applications of Differentiation",
        "topic_name": "Straight-Line Motion: Position, Velocity, and Acceleration",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "A particle moves along a line with position s(t) = t^3 - 6t^2 + 9t. At t = 4, is the particle speeding up or slowing down?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["motion", "velocity", "acceleration"],
        "misconception_tags": ["ignores-sign-comparison-of-velocity-and-acceleration"],
        "options": [
            {"label": "A", "text": "Speeding up, because velocity and acceleration have the same sign.", "is_correct": True},
            {"label": "B", "text": "Slowing down, because velocity and acceleration have opposite signs.", "is_correct": False},
            {"label": "C", "text": "Speeding up, because velocity is positive.", "is_correct": False},
            {"label": "D", "text": "Slowing down, because acceleration is positive.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. v(t) = 3t^2 - 12t + 9, so v(4) = 48 - 48 + 9 = 9 (positive). a(t) = 6t - 12, so a(4) = 12 (positive). Since velocity and acceleration share the same sign, speed is increasing.", "misconception_tag": None},
            {"option_label": "B", "explanation": "v(4) and a(4) are both positive (same sign), not opposite; this option misreads the signs.", "misconception_tag": "misreads-sign-chart"},
            {"option_label": "C", "explanation": "Velocity being positive alone does not determine speeding up or slowing down; you must also compare the sign of acceleration.", "misconception_tag": "ignores-sign-comparison-of-velocity-and-acceleration"},
            {"option_label": "D", "explanation": "A positive acceleration alone does not imply slowing down; it depends on the sign of velocity too, and here both are positive so the particle speeds up.", "misconception_tag": "ignores-sign-comparison-of-velocity-and-acceleration"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Contextual Applications of Differentiation",
        "topic_name": "Introduction to Related Rates",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A spherical balloon is inflated so its radius increases at 2 cm/s. Volume V = (4/3)*pi*r^3. How fast is the volume increasing when r = 3 cm?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["related-rates"],
        "misconception_tags": ["forgets-chain-rule-in-related-rates"],
        "options": [
            {"label": "A", "text": "72*pi cm^3/s", "is_correct": True},
            {"label": "B", "text": "36*pi cm^3/s", "is_correct": False},
            {"label": "C", "text": "24*pi cm^3/s", "is_correct": False},
            {"label": "D", "text": "108*pi cm^3/s", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. dV/dt = 4*pi*r^2 * dr/dt = 4*pi*(9)*(2) = 72*pi cm^3/s.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This forgets to multiply by dr/dt = 2, using dr/dt = 1 implicitly.", "misconception_tag": "forgets-chain-rule-in-related-rates"},
            {"option_label": "C", "explanation": "This uses r=2 instead of r=3, likely swapping the radius value with the rate value.", "misconception_tag": "swaps-given-values-in-related-rates"},
            {"option_label": "D", "explanation": "This mistakenly uses r^3's derivative pattern (3r^2) times dr/dt without applying the 4*pi coefficient correctly, then over-multiplies.", "misconception_tag": "arithmetic-error"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Contextual Applications of Differentiation",
        "topic_name": "Using L'Hospital's Rule for Indeterminate Forms",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Evaluate lim(x->0) sin(x)/x using L'Hospital's Rule.",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["lhopitals-rule", "limits"],
        "misconception_tags": ["applies-lhopital-without-checking-indeterminate-form"],
        "options": [
            {"label": "A", "text": "0", "is_correct": False},
            {"label": "B", "text": "1", "is_correct": True},
            {"label": "C", "text": "Undefined", "is_correct": False},
            {"label": "D", "text": "Infinity", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This incorrectly evaluates cos(0)/1 as 0 instead of 1, likely confusing cos(0) with sin(0).", "misconception_tag": "confuses-sin-and-cos-values-at-zero"},
            {"option_label": "B", "explanation": "Correct. The form is 0/0, so L'Hospital's Rule applies: lim(x->0) cos(x)/1 = cos(0)/1 = 1.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The limit is well-defined and finite; sin(x)/x approaches 1 as x approaches 0.", "misconception_tag": "applies-lhopital-without-checking-indeterminate-form"},
            {"option_label": "D", "explanation": "This misapplies the rule as if the form were nonzero/0 rather than the true 0/0 indeterminate form.", "misconception_tag": "applies-lhopital-without-checking-indeterminate-form"},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 5: Analytical Applications of Differentiation
    # ------------------------------------------------------------------
    {
        "unit_name": "Analytical Applications of Differentiation",
        "topic_name": "Using the First Derivative Test for Relative Extrema",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "For f(x) = x^3 - 3x^2, at x = 2, f has:",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["first-derivative-test", "extrema"],
        "misconception_tags": ["assumes-critical-point-is-always-extremum"],
        "options": [
            {"label": "A", "text": "A local maximum", "is_correct": False},
            {"label": "B", "text": "No critical point", "is_correct": False},
            {"label": "C", "text": "A local minimum", "is_correct": True},
            {"label": "D", "text": "An inflection point only, with no extremum", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "f'(x)=3x^2-6x=3x(x-2), which is negative just before x=2 and positive just after, indicating a minimum, not a maximum.", "misconception_tag": "misreads-sign-chart"},
            {"option_label": "B", "explanation": "f'(2) = 3(2)(0) = 0, so x=2 is indeed a critical point.", "misconception_tag": "arithmetic-error"},
            {"option_label": "C", "explanation": "Correct. f'(x)=3x(x-2) changes from negative (for 0<x<2) to positive (for x>2) at x=2, so by the First Derivative Test, f has a local minimum there.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Since f' changes sign at x=2, this is a genuine extremum (a minimum), not merely an inflection point.", "misconception_tag": "assumes-critical-point-is-always-extremum"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Analytical Applications of Differentiation",
        "topic_name": "Using the Second Derivative Test for Concavity and Extrema",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "If f''(x) < 0 on an interval, the graph of f on that interval is:",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["concavity", "second-derivative-test"],
        "misconception_tags": ["confuses-concavity-with-increasing-decreasing"],
        "options": [
            {"label": "A", "text": "Concave down", "is_correct": True},
            {"label": "B", "text": "Concave up", "is_correct": False},
            {"label": "C", "text": "Increasing", "is_correct": False},
            {"label": "D", "text": "Decreasing", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. A negative second derivative means the first derivative is decreasing, which corresponds to a concave-down graph.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This reverses the concavity rule; concave up requires f''(x) > 0, not negative.", "misconception_tag": "reverses-concavity-inequality"},
            {"option_label": "C", "explanation": "This confuses concavity (behavior of f') with monotonicity (behavior of f itself), which is governed by f', not f''.", "misconception_tag": "confuses-concavity-with-increasing-decreasing"},
            {"option_label": "D", "explanation": "This also confuses concavity with monotonicity; the sign of f'' says nothing directly about whether f itself is decreasing.", "misconception_tag": "confuses-concavity-with-increasing-decreasing"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Analytical Applications of Differentiation",
        "topic_name": "Solving Optimization Problems",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "A farmer has 100 meters of fencing to enclose a rectangular field bordering a straight river (no fence needed along the river). What dimensions (width parallel to river, by depth perpendicular to river) maximize the enclosed area?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["optimization"],
        "misconception_tags": ["forgets-one-side-is-unfenced"],
        "options": [
            {"label": "A", "text": "25 m by 25 m", "is_correct": False},
            {"label": "B", "text": "33.3 m by 33.3 m", "is_correct": False},
            {"label": "C", "text": "40 m by 20 m", "is_correct": False},
            {"label": "D", "text": "50 m by 25 m", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This treats all four sides as fenced (a square using the standard perimeter formula), ignoring that one side borders the river and needs no fence.", "misconception_tag": "forgets-one-side-is-unfenced"},
            {"option_label": "B", "explanation": "This incorrectly divides the fencing into three equal parts without deriving the optimal split via calculus.", "misconception_tag": "guesses-equal-partition-without-optimizing"},
            {"option_label": "C", "explanation": "This has correct perimeter usage (40+20+20=80, not 100) but does not reflect the maximum from A = x(100-2x)/1 optimization; it's not the critical point.", "misconception_tag": "arithmetic-error"},
            {"option_label": "D", "explanation": "Correct. With width w (parallel to river) and depth d, w + 2d = 100, so w = 100-2d, and Area = d(100-2d) = 100d - 2d^2. Setting dA/dd = 100 - 4d = 0 gives d = 25, w = 50, maximizing area at 1250 m^2.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 6: Integration and Accumulation of Change
    # ------------------------------------------------------------------
    {
        "unit_name": "Integration and Accumulation of Change",
        "topic_name": "The Fundamental Theorem of Calculus and Definite Integrals",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Evaluate the definite integral: integral from 0 to 2 of (3x^2) dx.",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["fundamental-theorem-of-calculus", "definite-integrals"],
        "misconception_tags": ["forgets-to-evaluate-at-both-bounds"],
        "options": [
            {"label": "A", "text": "6", "is_correct": False},
            {"label": "B", "text": "4", "is_correct": False},
            {"label": "C", "text": "8", "is_correct": True},
            {"label": "D", "text": "12", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This appears to evaluate the derivative of 3x^2 (which is 6x) at a point rather than antidifferentiating and evaluating the integral.", "misconception_tag": "confuses-derivative-with-antiderivative"},
            {"option_label": "B", "explanation": "This uses an incorrect antiderivative, such as x^2 instead of x^3, before evaluating at the bounds.", "misconception_tag": "misapplies-power-rule-for-integration"},
            {"option_label": "C", "explanation": "Correct. The antiderivative of 3x^2 is x^3. Evaluating from 0 to 2: (2)^3 - (0)^3 = 8.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This only evaluates x^3 at x=2 correctly (8) but then adds an extra unnecessary factor rather than subtracting the lower bound value (0).", "misconception_tag": "forgets-to-evaluate-at-both-bounds"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Integration and Accumulation of Change",
        "topic_name": "Integrating Using Substitution",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Find the indefinite integral: integral of 2x*cos(x^2) dx.",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["u-substitution", "integration"],
        "misconception_tags": ["drops-constant-of-integration"],
        "options": [
            {"label": "A", "text": "sin(x^2) + C", "is_correct": True},
            {"label": "B", "text": "sin(x^2)", "is_correct": False},
            {"label": "C", "text": "-sin(x^2) + C", "is_correct": False},
            {"label": "D", "text": "x^2*sin(x^2) + C", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Let u = x^2, du = 2x dx. The integral becomes integral of cos(u) du = sin(u) + C = sin(x^2) + C.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This has the correct antiderivative expression but drops the constant of integration, which is required for indefinite integrals.", "misconception_tag": "drops-constant-of-integration"},
            {"option_label": "C", "explanation": "This introduces an incorrect sign, as if integrating -sin instead of cos, or confusing the derivative and antiderivative of sine/cosine.", "misconception_tag": "sign-error-trig-integration"},
            {"option_label": "D", "explanation": "This incorrectly multiplies the result by x^2 rather than substituting back u=x^2 into sin(u).", "misconception_tag": "algebra-error-in-substitution-back-step"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Integration and Accumulation of Change",
        "topic_name": "Estimating Definite Integrals Using Riemann Sums",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Using a left Riemann sum with 4 equal subintervals, estimate the integral of f(x) = x + 1 from x=0 to x=4, given f(0)=1, f(1)=2, f(2)=3, f(3)=4.",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["riemann-sums"],
        "misconception_tags": ["uses-right-endpoints-for-left-sum"],
        "options": [
            {"label": "A", "text": "14", "is_correct": False},
            {"label": "B", "text": "10", "is_correct": True},
            {"label": "C", "text": "12", "is_correct": False},
            {"label": "D", "text": "8", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This uses the right endpoints (f(1)+f(2)+f(3)+f(4) = 2+3+4+5=14) instead of the left endpoints required for a left Riemann sum.", "misconception_tag": "uses-right-endpoints-for-left-sum"},
            {"option_label": "B", "explanation": "Correct. Left Riemann sum = width * [f(0)+f(1)+f(2)+f(3)] = 1*(1+2+3+4) = 10.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This averages the left and right sums (a trapezoidal-like estimate) rather than computing the pure left Riemann sum.", "misconception_tag": "confuses-left-sum-with-trapezoidal-sum"},
            {"option_label": "D", "explanation": "This omits one of the four rectangles from the summation.", "misconception_tag": "arithmetic-error"},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 7: Differential Equations
    # ------------------------------------------------------------------
    {
        "unit_name": "Differential Equations",
        "topic_name": "Sketching and Interpreting Slope Fields",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "In the slope field for dy/dx = x, what do the line segments look like along the vertical line x = 0?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["slope-fields"],
        "misconception_tags": ["evaluates-slope-field-using-y-instead-of-x"],
        "options": [
            {"label": "A", "text": "Horizontal segments (slope 0)", "is_correct": True},
            {"label": "B", "text": "Vertical segments (undefined slope)", "is_correct": False},
            {"label": "C", "text": "Segments with slope 1", "is_correct": False},
            {"label": "D", "text": "Segments with slope depending on y", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Since dy/dx = x, along x=0 the slope is 0 everywhere regardless of y, giving horizontal segments.", "misconception_tag": None},
            {"option_label": "B", "explanation": "A slope of 0 produces horizontal, not vertical, segments; vertical segments would require an undefined (infinite) slope.", "misconception_tag": "confuses-zero-slope-with-undefined-slope"},
            {"option_label": "C", "explanation": "This would be true along the line x=1, not x=0.", "misconception_tag": "arithmetic-error"},
            {"option_label": "D", "explanation": "This incorrectly assumes the differential equation depends on y, but dy/dx = x depends only on x.", "misconception_tag": "evaluates-slope-field-using-y-instead-of-x"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differential Equations",
        "topic_name": "Solving Separable Differential Equations",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Solve the differential equation dy/dx = y with initial condition y(0) = 2.",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["separable-differential-equations"],
        "misconception_tags": ["drops-constant-when-solving-for-c"],
        "options": [
            {"label": "A", "text": "y = e^x", "is_correct": False},
            {"label": "B", "text": "y = 2e^x", "is_correct": True},
            {"label": "C", "text": "y = e^x + 2", "is_correct": False},
            {"label": "D", "text": "y = e^(x+2)", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This finds the general shape y = Ce^x but forgets to solve for C using the initial condition y(0)=2, effectively leaving C=1.", "misconception_tag": "drops-constant-when-solving-for-c"},
            {"option_label": "B", "explanation": "Correct. Separating variables: dy/y = dx, integrating gives ln|y| = x + C1, so y = Ce^x. Using y(0)=2 gives C=2, so y = 2e^x.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This incorrectly adds the initial value as a constant term outside the exponential rather than as a multiplicative constant.", "misconception_tag": "adds-initial-condition-instead-of-multiplying"},
            {"option_label": "D", "explanation": "This incorrectly folds the initial condition into the exponent rather than solving for the multiplicative constant C.", "misconception_tag": "adds-initial-condition-instead-of-multiplying"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Differential Equations",
        "topic_name": "Exponential Models with Differential Equations",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A population P grows according to dP/dt = kP. If the population doubles every 5 years, which statement is true about k?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["exponential-growth-decay"],
        "misconception_tags": ["confuses-doubling-time-with-growth-constant"],
        "options": [
            {"label": "A", "text": "k = 5", "is_correct": False},
            {"label": "B", "text": "k = 2", "is_correct": False},
            {"label": "C", "text": "k = 1/5", "is_correct": False},
            {"label": "D", "text": "k = ln(2)/5", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This mistakes the doubling time (5 years) directly for the growth constant k, but they are related through a logarithm, not equal.", "misconception_tag": "confuses-doubling-time-with-growth-constant"},
            {"option_label": "B", "explanation": "This mistakes the doubling factor (2) for k directly.", "misconception_tag": "confuses-doubling-time-with-growth-constant"},
            {"option_label": "C", "explanation": "This takes the reciprocal of the doubling time but forgets the required natural logarithm factor from solving 2=e^(5k).", "misconception_tag": "drops-logarithm-when-solving-for-k"},
            {"option_label": "D", "explanation": "Correct. P(t) = P0*e^(kt); doubling means P0*e^(5k) = 2P0, so e^(5k)=2, giving 5k = ln(2), so k = ln(2)/5.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Unit 8: Applications of Integration
    # ------------------------------------------------------------------
    {
        "unit_name": "Applications of Integration",
        "topic_name": "Average Value of a Function",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Find the average value of f(x) = x^2 on the interval [0, 3].",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["average-value"],
        "misconception_tags": ["forgets-to-divide-by-interval-length"],
        "options": [
            {"label": "A", "text": "9", "is_correct": False},
            {"label": "B", "text": "27", "is_correct": False},
            {"label": "C", "text": "3", "is_correct": True},
            {"label": "D", "text": "1", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is f(3) = 9, the function's value at the right endpoint, not the average value over the interval.", "misconception_tag": "confuses-average-value-with-endpoint-value"},
            {"option_label": "B", "explanation": "This is the value of the definite integral (integral of x^2 from 0 to 3 = 9), but forgets to divide by the interval length (3-0=3) to get the average value.", "misconception_tag": "forgets-to-divide-by-interval-length"},
            {"option_label": "C", "explanation": "Correct. Average value = (1/(3-0)) * integral from 0 to 3 of x^2 dx = (1/3)(9) = 3.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This divides by the wrong quantity (interval length squared, or similar), producing too small a result.", "misconception_tag": "arithmetic-error"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Applications of Integration",
        "topic_name": "Finding the Area Between Curves",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Find the area between y = x and y = x^2 on the interval where x is between 0 and 1.",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["area-between-curves"],
        "misconception_tags": ["subtracts-curves-in-wrong-order"],
        "options": [
            {"label": "A", "text": "1/6", "is_correct": True},
            {"label": "B", "text": "1/2", "is_correct": False},
            {"label": "C", "text": "5/6", "is_correct": False},
            {"label": "D", "text": "-1/6", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. On [0,1], x >= x^2, so Area = integral from 0 to 1 of (x - x^2) dx = [x^2/2 - x^3/3] from 0 to 1 = 1/2 - 1/3 = 1/6.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This computes only the integral of x from 0 to 1, forgetting to subtract the integral of x^2.", "misconception_tag": "forgets-to-subtract-second-curve"},
            {"option_label": "C", "explanation": "This computes 1 minus the correct answer, suggesting confusion about which region is being measured.", "misconception_tag": "computes-complementary-region"},
            {"option_label": "D", "explanation": "This subtracts the curves in the wrong order (x^2 - x), giving a negative value for area, which should be taken as an absolute value.", "misconception_tag": "subtracts-curves-in-wrong-order"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Applications of Integration",
        "topic_name": "Volume of Solids of Revolution Using Disc and Washer Methods",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "The region bounded by y = x^2, y = 0, and x = 1 is revolved about the x-axis. Which integral gives the volume of the resulting solid using the disc method?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["volume", "disc-washer-method"],
        "misconception_tags": ["forgets-to-square-radius-in-disc-method"],
        "options": [
            {"label": "A", "text": "pi * integral from 0 to 1 of x^2 dx", "is_correct": False},
            {"label": "B", "text": "pi * integral from 0 to 1 of x^4 dx", "is_correct": True},
            {"label": "C", "text": "integral from 0 to 1 of x^4 dx", "is_correct": False},
            {"label": "D", "text": "pi * integral from 0 to 1 of x dx", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This forgets to square the radius function y=x^2 before integrating, using x^2 instead of (x^2)^2 = x^4.", "misconception_tag": "forgets-to-square-radius-in-disc-method"},
            {"option_label": "B", "explanation": "Correct. Disc method: V = pi * integral from a to b of [R(x)]^2 dx, where R(x) = x^2, so [R(x)]^2 = x^4.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This has the correct integrand x^4 but forgets to include the factor of pi required by the disc method formula.", "misconception_tag": "forgets-pi-factor-in-volume-formula"},
            {"option_label": "D", "explanation": "This uses the un-squared, un-simplified radius x rather than the correct radius function x^2 squared.", "misconception_tag": "forgets-to-square-radius-in-disc-method"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Applications of Integration",
        "topic_name": "Position, Velocity, and Acceleration Using Integrals",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "A particle has velocity v(t) = 4t and starts at position s(0) = 3. What is its position at t = 2?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["motion", "integration"],
        "misconception_tags": ["forgets-initial-condition-constant"],
        "options": [
            {"label": "A", "text": "8", "is_correct": False},
            {"label": "B", "text": "16", "is_correct": False},
            {"label": "C", "text": "11", "is_correct": True},
            {"label": "D", "text": "5", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This computes the antiderivative 2t^2 evaluated at t=2 (giving 8) but forgets to add the initial position s(0)=3.", "misconception_tag": "forgets-initial-condition-constant"},
            {"option_label": "B", "explanation": "This incorrectly integrates v(t) as if it were 8t rather than 4t, doubling the coefficient in error.", "misconception_tag": "arithmetic-error"},
            {"option_label": "C", "explanation": "Correct. s(t) = integral of 4t dt = 2t^2 + C. Using s(0)=3 gives C=3, so s(t)=2t^2+3, and s(2)=8+3=11.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This computes v(2)=8 and combines it incorrectly with the initial position via subtraction instead of properly integrating.", "misconception_tag": "confuses-velocity-value-with-position"},
        ],
        "rubric_json": None,
    },
    # ------------------------------------------------------------------
    # Free Response Questions (single self-contained prompts, spread
    # across units)
    # ------------------------------------------------------------------
    {
        "unit_name": "Analytical Applications of Differentiation",
        "topic_name": "Solving Optimization Problems",
        "type": "frq",
        "difficulty": 4,
        "prompt": "A closed box with a square base is to have a volume of 64 cubic feet. Let x be the side length of the base. Express the surface area S of the box as a function of x, and find the value of x that minimizes the surface area. Show the work that justifies your answer is a minimum.",
        "correct_answer": "S(x) = 2x^2 + 256/x; minimized at x = 4 feet, verified by the first or second derivative test.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["optimization", "derivatives"],
        "misconception_tags": ["forgets-to-justify-minimum-with-derivative-test"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "Let x = side length of the square base and h = height. Volume: x^2*h = 64, so h = 64/x^2. Surface area (closed box, 2 square faces plus 4 rectangular sides): S = 2x^2 + 4xh = 2x^2 + 4x(64/x^2) = 2x^2 + 256/x. Differentiate: S'(x) = 4x - 256/x^2. Set S'(x) = 0: 4x = 256/x^2, so 4x^3 = 256, x^3 = 64, x = 4. Confirm this is a minimum using the second derivative: S''(x) = 4 + 512/x^3, and S''(4) = 4 + 8 = 12 > 0, so x=4 gives a minimum (concave up at the critical point). The minimum surface area is S(4) = 2(16) + 256/4 = 32 + 64 = 96 square feet.",
                "misconception_tag": "forgets-to-justify-minimum-with-derivative-test",
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Correctly expresses h in terms of x using the volume constraint", "keywords": ["32", "x^2", "h ="], "points": 1},
                {"point": "Correctly derives S(x) = 2x^2 + 128/x", "keywords": ["2x^2", "128/x", "surface area"], "points": 1},
                {"point": "Sets S'(x) = 0 and solves for the critical value of x", "keywords": ["S'(x)", "derivative", "= 0"], "points": 1},
                {"point": "Justifies the critical point is a minimum using the first or second derivative test", "keywords": ["second derivative", "concave up", "minimum", "S''(x)"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Integration and Accumulation of Change",
        "topic_name": "Using Accumulation Functions and the Second Fundamental Theorem",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Let g(x) = integral from 0 to x of (t^2 + 1) dt. Find g'(x) and evaluate g'(2). Explain which theorem justifies your method.",
        "correct_answer": "g'(x) = x^2 + 1 by the Second Fundamental Theorem of Calculus; g'(2) = 5.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["fundamental-theorem-of-calculus", "accumulation-functions"],
        "misconception_tags": ["tries-to-evaluate-integral-before-differentiating"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "The Second Fundamental Theorem of Calculus states that if g(x) = integral from a to x of f(t) dt, then g'(x) = f(x). Here f(t) = t^2 + 1, so g'(x) = x^2 + 1 directly, without needing to first compute the antiderivative and evaluate it at the bounds. Evaluating at x=2: g'(2) = 2^2 + 1 = 5.",
                "misconception_tag": None,
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies and correctly states the Second Fundamental Theorem of Calculus", "keywords": ["second fundamental theorem", "g'(x) = f(x)"], "points": 1},
                {"point": "Correctly finds g'(x) = x^2 + 1 without unnecessarily integrating first", "keywords": ["x^2 + 1"], "points": 2},
                {"point": "Correctly evaluates g'(2) = 5", "keywords": ["g'(2)", "5"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Contextual Applications of Differentiation",
        "topic_name": "Introduction to Related Rates",
        "type": "frq",
        "difficulty": 4,
        "prompt": "A ladder 10 feet long rests against a vertical wall. The bottom of the ladder slides away from the wall at a rate of 1 ft/s. How fast is the top of the ladder sliding down the wall when the bottom of the ladder is 6 feet from the wall?",
        "correct_answer": "The top of the ladder is sliding down at 0.75 ft/s when the bottom is 6 feet from the wall.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["related-rates"],
        "misconception_tags": ["forgets-negative-sign-indicating-decreasing-height"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "Let x = distance of the ladder's bottom from the wall, y = height of the ladder's top on the wall. Since the ladder has fixed length 10: x^2 + y^2 = 100. Differentiating with respect to time: 2x(dx/dt) + 2y(dy/dt) = 0. When x=6, y = sqrt(100-36) = 8. Given dx/dt = 1 ft/s, substitute: 2(6)(1) + 2(8)(dy/dt) = 0, so 12 + 16(dy/dt) = 0, giving dy/dt = -12/16 = -0.75 ft/s. The negative sign indicates the height y is decreasing, i.e., the top slides down at 0.75 ft/s.",
                "misconception_tag": "forgets-negative-sign-indicating-decreasing-height",
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Sets up the Pythagorean relationship x^2 + y^2 = 100", "keywords": ["x^2", "y^2", "100"], "points": 1},
                {"point": "Differentiates implicitly with respect to time", "keywords": ["2x", "dx/dt", "2y", "dy/dt"], "points": 1},
                {"point": "Solves for y when x=6 using the constraint", "keywords": ["y = 8", "sqrt"], "points": 1},
                {"point": "Correctly solves for dy/dt and interprets the negative sign as decreasing height", "keywords": ["-0.75", "decreasing", "dy/dt"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Limits and Continuity",
        "topic_name": "Connecting Limits, Asymptotes, and Continuity",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Let f(x) = (x^2 - 9)/(x - 3) for x != 3, and f(3) = k. Find the value of k that makes f continuous at x = 3, and justify your answer using the definition of continuity.",
        "correct_answer": "k = 6, since the limit of f(x) as x approaches 3 equals 6, and continuity requires f(3) to equal that limit.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["continuity", "limits"],
        "misconception_tags": ["confuses-removable-discontinuity-with-nonexistent-limit"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "For f to be continuous at x=3, three conditions must hold: f(3) is defined, lim(x->3) f(x) exists, and lim(x->3) f(x) = f(3). Factor the numerator: (x^2-9)/(x-3) = (x-3)(x+3)/(x-3) = x+3 for x != 3. Thus lim(x->3) f(x) = lim(x->3) (x+3) = 6. This limit exists (it's a removable discontinuity, not an essential one) despite f(x) being undefined in its original form at x=3. Setting k = f(3) = 6 satisfies the continuity condition.",
                "misconception_tag": "confuses-removable-discontinuity-with-nonexistent-limit",
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "States the three-part definition of continuity at a point", "keywords": ["f(3)", "limit exists", "equal"], "points": 1},
                {"point": "Factors and simplifies f(x) to find the limit as x approaches 3", "keywords": ["x+3", "factor", "(x-3)"], "points": 2},
                {"point": "Correctly concludes k = 6", "keywords": ["k = 6"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Differential Equations",
        "topic_name": "Solving Separable Differential Equations",
        "type": "frq",
        "difficulty": 5,
        "prompt": "Solve the differential equation dy/dx = xy^2 with initial condition y(0) = 1. Write y as an explicit function of x.",
        "correct_answer": "y = -1/(x^2/2 - 1), equivalently y = 2/(2 - x^2).",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["separable-differential-equations"],
        "misconception_tags": ["incorrectly-integrates-one-over-y-squared"],
        "explanations": [
            {
                "option_label": None,
                "explanation": "Separate variables: dy/y^2 = x dx. Integrate both sides: integral of y^(-2) dy = integral of x dx, giving -1/y = x^2/2 + C. Apply the initial condition y(0)=1: -1/1 = 0 + C, so C = -1. Thus -1/y = x^2/2 - 1. Solving for y: y = -1/(x^2/2 - 1) = 2/(2 - x^2). Students should verify the domain excludes x = sqrt(2) where the denominator is zero.",
                "misconception_tag": "incorrectly-integrates-one-over-y-squared",
            }
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Separates variables correctly as dy/y^2 = x dx", "keywords": ["dy/y^2", "x dx", "separate"], "points": 1},
                {"point": "Integrates both sides correctly to get -1/y = x^2/2 + C", "keywords": ["-1/y", "x^2/2", "C"], "points": 1},
                {"point": "Uses the initial condition to solve for C = -1", "keywords": ["C = -1", "y(0)=1"], "points": 1},
                {"point": "Solves explicitly for y in terms of x", "keywords": ["y =", "2 - x^2"], "points": 1},
            ]
        },
    },
]
