"""Demo-scale AP Chemistry question seed bank.

This is NOT an exhaustive question bank -- it is a modest seed set meant to
exercise the app's flows end-to-end (practice sessions, mistake memory,
FRQ grading) across all 9 CED units. Each question's unit_name/topic_name
must match scripts/seed_data/units_topics/chemistry.py exactly.
"""

QUESTIONS = [
    # ---------------------------------------------------------------
    # Unit 1: Atomic Structure and Properties
    # ---------------------------------------------------------------
    {
        "unit_name": "Atomic Structure and Properties",
        "topic_name": "Moles and Molar Mass",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "How many moles of carbon atoms are present in 22.0 g of CO2? (Molar mass of CO2 = 44.0 g/mol)",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["stoichiometry", "moles"],
        "misconception_tags": ["confuses-compound-moles-with-atom-moles"],
        "options": [
            {"label": "A", "text": "0.25 mol", "is_correct": False},
            {"label": "B", "text": "0.50 mol", "is_correct": True},
            {"label": "C", "text": "1.0 mol", "is_correct": False},
            {"label": "D", "text": "2.0 mol", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This halves the moles of CO2 again instead of just finding moles of CO2, an arithmetic error.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct: 22.0 g / 44.0 g/mol = 0.50 mol CO2, and each CO2 has exactly one carbon atom, so moles of C = 0.50 mol.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This assumes 1 mole of CO2 is present without dividing by molar mass correctly, or confuses mass with moles.", "misconception_tag": "confuses-compound-moles-with-atom-moles"},
            {"option_label": "D", "explanation": "This incorrectly multiplies moles of CO2 by 2, likely counting oxygen atoms instead of carbon.", "misconception_tag": "confuses-compound-moles-with-atom-moles"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Atomic Structure and Properties",
        "topic_name": "Electron Configuration and Orbitals",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "What is the ground-state electron configuration of a sulfur atom (Z = 16)?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["electron-configuration"],
        "misconception_tags": ["misapplies-aufbau-order"],
        "options": [
            {"label": "A", "text": "1s2 2s2 2p6 3s2 3p4", "is_correct": True},
            {"label": "B", "text": "1s2 2s2 2p6 3s2 3p6", "is_correct": False},
            {"label": "C", "text": "1s2 2s2 2p6 3s2 3p2 3d2", "is_correct": False},
            {"label": "D", "text": "1s2 2s2 2p6 3s2 4s2 3p2", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: sulfur has 16 electrons, filling 1s, 2s, 2p, 3s, and 4 electrons in 3p.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This is the configuration for argon (18 electrons), two too many for sulfur.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This incorrectly places electrons in 3d before 3p is filled, violating the Aufbau filling order.", "misconception_tag": "misapplies-aufbau-order"},
            {"option_label": "D", "explanation": "This fills 4s before 3p is complete, violating the correct energy ordering of subshells.", "misconception_tag": "misapplies-aufbau-order"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Atomic Structure and Properties",
        "topic_name": "Periodic Trends",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Which of the following lists the elements Na, Mg, and Al in order of increasing first ionization energy?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["periodic-trends"],
        "misconception_tags": ["ignores-subshell-stability-exception"],
        "options": [
            {"label": "A", "text": "Al < Mg < Na", "is_correct": False},
            {"label": "B", "text": "Mg < Na < Al", "is_correct": False},
            {"label": "C", "text": "Na < Al < Mg", "is_correct": True},
            {"label": "D", "text": "Na < Mg < Al", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reverses the overall left-to-right increasing trend entirely.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This places Na above Mg, ignoring that ionization energy generally increases across a period.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct: ionization energy generally increases across period 3, but Mg's full 3s subshell makes it higher than Al, giving Na < Al < Mg.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This assumes ionization energy increases strictly and smoothly across the period, missing the extra stability of Mg's filled 3s2 subshell.", "misconception_tag": "ignores-subshell-stability-exception"},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 2: Molecular and Ionic Compound Structure and Properties
    # ---------------------------------------------------------------
    {
        "unit_name": "Molecular and Ionic Compound Structure and Properties",
        "topic_name": "Lewis Diagrams",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "How many lone pairs of electrons are on the central atom in the Lewis structure of NH3?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["lewis-structures"],
        "misconception_tags": ["miscounts-valence-electrons"],
        "options": [
            {"label": "A", "text": "0", "is_correct": False},
            {"label": "B", "text": "1", "is_correct": True},
            {"label": "C", "text": "2", "is_correct": False},
            {"label": "D", "text": "3", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This ignores nitrogen's unshared electron pair, treating all 5 valence electrons as bonding.", "misconception_tag": "miscounts-valence-electrons"},
            {"option_label": "B", "explanation": "Correct: nitrogen contributes 5 valence electrons, 3 are used in bonds to hydrogen, leaving one lone pair.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This overcounts lone pairs, possibly by miscounting nitrogen's valence electrons as 7 (like a halogen).", "misconception_tag": "miscounts-valence-electrons"},
            {"option_label": "D", "explanation": "This treats nitrogen as if it forms no bonds at all, which is inconsistent with NH3's known formula.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Molecular and Ionic Compound Structure and Properties",
        "topic_name": "VSEPR and Bond Hybridization",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the molecular geometry of CH4?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["molecular-geometry", "vsepr"],
        "misconception_tags": ["confuses-electron-geometry-with-molecular-geometry"],
        "options": [
            {"label": "A", "text": "Trigonal planar", "is_correct": False},
            {"label": "B", "text": "Bent", "is_correct": False},
            {"label": "C", "text": "Trigonal pyramidal", "is_correct": False},
            {"label": "D", "text": "Tetrahedral", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Trigonal planar geometry corresponds to 3 bonding groups and no lone pairs, not 4 bonding groups.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Bent geometry occurs with 2 bonding groups and 1-2 lone pairs on the central atom, unlike CH4.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This is the geometry of NH3, which has one lone pair on the central atom; CH4's carbon has no lone pairs.", "misconception_tag": "confuses-electron-geometry-with-molecular-geometry"},
            {"option_label": "D", "explanation": "Correct: carbon has 4 bonding pairs and 0 lone pairs, giving a tetrahedral shape with 109.5-degree bond angles.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Molecular and Ionic Compound Structure and Properties",
        "topic_name": "Bond Polarity and Molecular Polarity",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which molecule is nonpolar despite having polar bonds?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["polarity"],
        "misconception_tags": ["assumes-polar-bonds-mean-polar-molecule"],
        "options": [
            {"label": "A", "text": "CO2", "is_correct": True},
            {"label": "B", "text": "H2O", "is_correct": False},
            {"label": "C", "text": "NH3", "is_correct": False},
            {"label": "D", "text": "HCl", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: CO2 is linear and symmetric, so the two polar C=O bond dipoles point in opposite directions and cancel.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Water's bent geometry means its two O-H bond dipoles do not cancel, making it polar.", "misconception_tag": "assumes-polar-bonds-mean-polar-molecule"},
            {"option_label": "C", "explanation": "Ammonia's trigonal pyramidal shape leaves a net dipole because the bond dipoles and lone pair do not cancel.", "misconception_tag": "assumes-polar-bonds-mean-polar-molecule"},
            {"option_label": "D", "explanation": "HCl is a simple diatomic molecule with only one bond, so its bond dipole is the molecular dipole; it is polar.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 3: Intermolecular Forces and Properties
    # ---------------------------------------------------------------
    {
        "unit_name": "Intermolecular Forces and Properties",
        "topic_name": "Intermolecular Forces",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which type of intermolecular force is primarily responsible for the unusually high boiling point of water compared to H2S?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["intermolecular-forces"],
        "misconception_tags": ["confuses-intermolecular-with-intramolecular-forces"],
        "options": [
            {"label": "A", "text": "Ionic bonding", "is_correct": False},
            {"label": "B", "text": "London dispersion forces", "is_correct": False},
            {"label": "C", "text": "Hydrogen bonding", "is_correct": True},
            {"label": "D", "text": "Covalent bonding", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Water is a covalent molecule, not an ionic compound, so ionic bonding is not present between molecules.", "misconception_tag": None},
            {"option_label": "B", "explanation": "London dispersion forces exist in all molecules but are weaker in water than the special dipole force present due to O-H bonds.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct: O-H bonds allow strong hydrogen bonding between water molecules, raising the boiling point far above H2S, which cannot hydrogen bond.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Covalent bonding is an intramolecular force holding atoms together within a water molecule, not a force between separate molecules.", "misconception_tag": "confuses-intermolecular-with-intramolecular-forces"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Intermolecular Forces and Properties",
        "topic_name": "Ideal Gas Law",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A 2.00 L container holds 0.500 mol of an ideal gas at 300 K. What is the pressure in atm? (R = 0.0821 L*atm/(mol*K))",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["gas-laws", "ideal-gas-law"],
        "misconception_tags": ["forgets-to-convert-temperature-to-kelvin"],
        "options": [
            {"label": "A", "text": "3.08 atm", "is_correct": False},
            {"label": "B", "text": "6.16 atm", "is_correct": True},
            {"label": "C", "text": "12.3 atm", "is_correct": False},
            {"label": "D", "text": "24.6 atm", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is half the correct value, likely from dividing by volume twice or a setup error.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct: P = nRT/V = (0.500)(0.0821)(300)/2.00 = 6.16 atm.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This is double the correct answer, likely from forgetting to divide by volume (2.00 L).", "misconception_tag": None},
            {"option_label": "D", "explanation": "This is four times too large, consistent with omitting the volume division and also mishandling another factor.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Intermolecular Forces and Properties",
        "topic_name": "Colligative Properties",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Which aqueous solution has the lowest freezing point, assuming complete dissociation and equal molality?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["colligative-properties"],
        "misconception_tags": ["ignores-van-t-hoff-factor"],
        "options": [
            {"label": "A", "text": "0.10 m glucose (nonelectrolyte)", "is_correct": False},
            {"label": "B", "text": "0.10 m NaCl", "is_correct": False},
            {"label": "C", "text": "0.10 m CaCl2", "is_correct": False},
            {"label": "D", "text": "0.10 m AlCl3", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Glucose does not dissociate (i = 1), giving the smallest freezing point depression of the choices.", "misconception_tag": None},
            {"option_label": "B", "explanation": "NaCl dissociates into 2 ions (i = 2), giving a moderate freezing point depression, but less than AlCl3.", "misconception_tag": "ignores-van-t-hoff-factor"},
            {"option_label": "C", "explanation": "CaCl2 dissociates into 3 ions (i = 3), giving a larger depression than NaCl but still less than AlCl3.", "misconception_tag": "ignores-van-t-hoff-factor"},
            {"option_label": "D", "explanation": "Correct: AlCl3 dissociates into 4 ions (i = 4), producing the greatest van't Hoff factor and thus the largest freezing point depression, so the lowest freezing point.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 4: Chemical Reactions
    # ---------------------------------------------------------------
    {
        "unit_name": "Chemical Reactions",
        "topic_name": "Net Ionic Equations",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the net ionic equation for the reaction between aqueous AgNO3 and aqueous NaCl?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["net-ionic-equations"],
        "misconception_tags": ["includes-spectator-ions"],
        "options": [
            {"label": "A", "text": "Ag+(aq) + Cl-(aq) -> AgCl(s)", "is_correct": True},
            {"label": "B", "text": "AgNO3(aq) + NaCl(aq) -> AgCl(s) + NaNO3(aq)", "is_correct": False},
            {"label": "C", "text": "Ag+(aq) + NO3-(aq) + Na+(aq) + Cl-(aq) -> AgCl(s) + Na+(aq) + NO3-(aq)", "is_correct": False},
            {"label": "D", "text": "Na+(aq) + NO3-(aq) -> NaNO3(aq)", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: Na+ and NO3- are spectator ions and are removed, leaving only the ions that form the AgCl precipitate.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This is the molecular (formula unit) equation, not the net ionic equation.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This is the complete ionic equation but still includes the spectator ions Na+ and NO3-, which should be canceled.", "misconception_tag": "includes-spectator-ions"},
            {"option_label": "D", "explanation": "This incorrectly treats the spectator ions as the reaction of interest instead of canceling them.", "misconception_tag": "includes-spectator-ions"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Chemical Reactions",
        "topic_name": "Stoichiometry and Limiting Reagents",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In the reaction N2 + 3H2 -> 2NH3, if 2.0 mol N2 reacts with 3.0 mol H2, which reagent is limiting?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["stoichiometry", "limiting-reagent"],
        "misconception_tags": ["compares-moles-without-using-mole-ratio"],
        "options": [
            {"label": "A", "text": "N2, because there is less of it in moles", "is_correct": False},
            {"label": "B", "text": "H2, because 2.0 mol N2 requires 6.0 mol H2 but only 3.0 mol is available", "is_correct": True},
            {"label": "C", "text": "Neither; they are both used up at exactly the same time", "is_correct": False},
            {"label": "D", "text": "NH3, because it is the product", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This compares raw mole amounts directly without applying the 1:3 mole ratio from the balanced equation.", "misconception_tag": "compares-moles-without-using-mole-ratio"},
            {"option_label": "B", "explanation": "Correct: the stoichiometric ratio requires 3 mol H2 per mol N2, so 2.0 mol N2 needs 6.0 mol H2, far more than the 3.0 mol available, making H2 limiting.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The mole ratio required (1:3) does not match the mole ratio provided (2:3), so they are not consumed simultaneously.", "misconception_tag": None},
            {"option_label": "D", "explanation": "NH3 is a product, not a reactant, so it cannot be the limiting reagent.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Chemical Reactions",
        "topic_name": "Introduction to Reactions",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Which of the following is a physical change, not a chemical change?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["chemical-reactions"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "Iron rusting", "is_correct": False},
            {"label": "B", "text": "Wood burning", "is_correct": False},
            {"label": "C", "text": "Ice melting into liquid water", "is_correct": True},
            {"label": "D", "text": "Bread dough rising due to yeast fermentation", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Rusting forms a new substance (iron oxide), so it is a chemical change.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Burning is combustion, which produces new substances like CO2 and H2O, so it is a chemical change.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct: melting only changes the state of water, not its chemical identity, so it is a physical change.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Fermentation produces new substances such as carbon dioxide gas, making it a chemical change.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 5: Kinetics
    # ---------------------------------------------------------------
    {
        "unit_name": "Kinetics",
        "topic_name": "Rate Law and Reaction Order",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "For the reaction A + B -> C, doubling [A] while holding [B] constant quadruples the rate. What is the order with respect to A?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["kinetics", "rate-law"],
        "misconception_tags": ["confuses-rate-multiplier-with-order"],
        "options": [
            {"label": "A", "text": "0", "is_correct": False},
            {"label": "B", "text": "1", "is_correct": False},
            {"label": "C", "text": "2", "is_correct": True},
            {"label": "D", "text": "4", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Zero order would mean no change in rate when [A] doubles, which contradicts the quadrupled rate.", "misconception_tag": None},
            {"option_label": "B", "explanation": "First order would mean the rate doubles when [A] doubles, not quadruples.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct: since 2^n = 4, n = 2, so the reaction is second order in A.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This mistakes the rate multiplier itself (4x) for the reaction order, rather than solving 2^n = 4 for n.", "misconception_tag": "confuses-rate-multiplier-with-order"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Kinetics",
        "topic_name": "Effect of Temperature and Catalysts on Rate",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "According to collision theory, why does increasing temperature generally increase reaction rate?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["catalysts", "arrhenius-equation"],
        "misconception_tags": ["confuses-activation-energy-with-kinetic-energy"],
        "options": [
            {"label": "A", "text": "It lowers the activation energy of the reaction", "is_correct": False},
            {"label": "B", "text": "It increases the fraction of molecules with kinetic energy exceeding the activation energy", "is_correct": True},
            {"label": "C", "text": "It increases the concentration of reactants", "is_correct": False},
            {"label": "D", "text": "It shifts the equilibrium constant to favor products", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Temperature does not change the activation energy; that is the role of a catalyst.", "misconception_tag": "confuses-activation-energy-with-kinetic-energy"},
            {"option_label": "B", "explanation": "Correct: higher temperature shifts the Maxwell-Boltzmann distribution so more molecules have enough energy to react, increasing effective collision frequency.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Temperature changes do not directly change the number of moles of reactant present in a fixed volume.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This confuses kinetics (reaction rate) with thermodynamics (equilibrium position), which are separate concepts.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 6: Thermodynamics
    # ---------------------------------------------------------------
    {
        "unit_name": "Thermodynamics",
        "topic_name": "Endothermic and Exothermic Processes",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "A reaction releases heat to its surroundings. What is the sign of delta H for this reaction?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["thermochemistry", "enthalpy"],
        "misconception_tags": ["sign-error-in-enthalpy"],
        "options": [
            {"label": "A", "text": "Negative", "is_correct": True},
            {"label": "B", "text": "Positive", "is_correct": False},
            {"label": "C", "text": "Zero", "is_correct": False},
            {"label": "D", "text": "Cannot be determined without more information", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: releasing heat to the surroundings means the system loses energy, so delta H is negative (exothermic).", "misconception_tag": None},
            {"option_label": "B", "explanation": "A positive delta H describes an endothermic process that absorbs heat, the opposite of what is described.", "misconception_tag": "sign-error-in-enthalpy"},
            {"option_label": "C", "explanation": "A delta H of zero would mean no net heat transfer, which contradicts the reaction releasing heat.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The sign of delta H is fully determined by the direction of heat flow described, which is given here.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Thermodynamics",
        "topic_name": "Hess's Law and Bond Energies",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Given: C(s) + O2(g) -> CO2(g), delta H = -394 kJ, and 2CO(g) + O2(g) -> 2CO2(g), delta H = -566 kJ, find delta H for 2C(s) + O2(g) -> 2CO(g).",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["hess-law", "bond-energy"],
        "misconception_tags": ["fails-to-scale-enthalpy-with-equation-coefficients"],
        "options": [
            {"label": "A", "text": "-222 kJ", "is_correct": True},
            {"label": "B", "text": "-960 kJ", "is_correct": False},
            {"label": "C", "text": "-172 kJ", "is_correct": False},
            {"label": "D", "text": "222 kJ", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: double the first equation (-788 kJ) and reverse the second (+566 kJ), sum to get -788 + 566 = -222 kJ.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This simply adds the two given enthalpies without scaling the first equation by 2 or reversing the second.", "misconception_tag": "fails-to-scale-enthalpy-with-equation-coefficients"},
            {"option_label": "C", "explanation": "This uses the unscaled first equation (-394) with the reversed second equation (+566), forgetting to double the first.", "misconception_tag": "fails-to-scale-enthalpy-with-equation-coefficients"},
            {"option_label": "D", "explanation": "This finds the correct magnitude but with the wrong sign, likely from mishandling which equation to reverse.", "misconception_tag": "sign-error-in-enthalpy"},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 7: Equilibrium
    # ---------------------------------------------------------------
    {
        "unit_name": "Equilibrium",
        "topic_name": "Le Chatelier's Principle",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "For the exothermic reaction 2SO2(g) + O2(g) <-> 2SO3(g), what happens to the equilibrium position if the temperature is increased?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["le-chateliers-principle"],
        "misconception_tags": ["treats-heat-as-ordinary-reactant"],
        "options": [
            {"label": "A", "text": "Shifts toward products, increasing SO3", "is_correct": False},
            {"label": "B", "text": "Shifts toward reactants, decreasing SO3", "is_correct": True},
            {"label": "C", "text": "No shift occurs; only the rate changes", "is_correct": False},
            {"label": "D", "text": "The equilibrium constant K stays the same, so nothing changes", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This treats added heat like it favors the exothermic forward direction, but added heat actually favors the endothermic reverse direction.", "misconception_tag": "treats-heat-as-ordinary-reactant"},
            {"option_label": "B", "explanation": "Correct: for an exothermic reaction, heat acts like a product; adding heat shifts equilibrium toward reactants, decreasing SO3.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Temperature changes affect both rate and the equilibrium position (and K), not just rate.", "misconception_tag": None},
            {"option_label": "D", "explanation": "K is temperature-dependent, so increasing temperature does change the value of K and the equilibrium position.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Equilibrium",
        "topic_name": "Solubility Equilibria (Ksp)",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "The Ksp of AgCl is 1.8 x 10^-10. What is the molar solubility of AgCl in pure water?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["ksp", "solubility-equilibria"],
        "misconception_tags": ["forgets-square-root-for-1-1-salt"],
        "options": [
            {"label": "A", "text": "1.8 x 10^-10 M", "is_correct": False},
            {"label": "B", "text": "9.0 x 10^-11 M", "is_correct": False},
            {"label": "C", "text": "1.3 x 10^-5 M", "is_correct": True},
            {"label": "D", "text": "3.6 x 10^-10 M", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This treats Ksp itself as the solubility without taking the square root, since Ksp = [Ag+][Cl-] = s^2 for a 1:1 salt.", "misconception_tag": "forgets-square-root-for-1-1-salt"},
            {"option_label": "B", "explanation": "This incorrectly halves Ksp instead of taking its square root.", "misconception_tag": "forgets-square-root-for-1-1-salt"},
            {"option_label": "C", "explanation": "Correct: s = sqrt(Ksp) = sqrt(1.8 x 10^-10) = 1.3 x 10^-5 M.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This doubles Ksp instead of taking the square root, an incorrect algebraic manipulation.", "misconception_tag": "forgets-square-root-for-1-1-salt"},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 8: Acids and Bases
    # ---------------------------------------------------------------
    {
        "unit_name": "Acids and Bases",
        "topic_name": "pH and pOH Calculations",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "What is the pH of a 0.010 M solution of HCl, a strong acid?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["ph-calculations"],
        "misconception_tags": ["confuses-molarity-with-ph-directly"],
        "options": [
            {"label": "A", "text": "0.010", "is_correct": False},
            {"label": "B", "text": "2.00", "is_correct": True},
            {"label": "C", "text": "12.00", "is_correct": False},
            {"label": "D", "text": "1.00", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reports the molarity itself rather than computing pH = -log[H+].", "misconception_tag": "confuses-molarity-with-ph-directly"},
            {"option_label": "B", "explanation": "Correct: since HCl fully dissociates, [H+] = 0.010 M, so pH = -log(0.010) = 2.00.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This calculates pOH instead of pH, or otherwise subtracts pH from 14 incorrectly.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This miscalculates the logarithm, perhaps by treating 0.010 as 0.1 M.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Acids and Bases",
        "topic_name": "Buffers",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A buffer contains 0.20 M acetic acid (Ka = 1.8 x 10^-5) and 0.20 M sodium acetate. What is the approximate pH of this buffer?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["buffers", "henderson-hasselbalch"],
        "misconception_tags": ["forgets-log-in-henderson-hasselbalch"],
        "options": [
            {"label": "A", "text": "4.74", "is_correct": True},
            {"label": "B", "text": "5.00", "is_correct": False},
            {"label": "C", "text": "1.8 x 10^-5", "is_correct": False},
            {"label": "D", "text": "9.26", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: pH = pKa + log([A-]/[HA]) = -log(1.8x10^-5) + log(1) = 4.74 + 0 = 4.74, since the concentrations are equal.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This rounds pKa incorrectly rather than computing -log(1.8 x 10^-5) precisely.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This reports Ka directly instead of applying the Henderson-Hasselbalch equation to find pH.", "misconception_tag": "forgets-log-in-henderson-hasselbalch"},
            {"option_label": "D", "explanation": "This is 14 minus the correct pH, suggesting a pOH-to-pH conversion error was mistakenly applied.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Acids and Bases",
        "topic_name": "Acid-Base Titrations",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "At the equivalence point of a titration of a weak acid with a strong base, the resulting solution pH is expected to be:",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["titrations"],
        "misconception_tags": ["assumes-equivalence-point-is-always-ph-7"],
        "options": [
            {"label": "A", "text": "Less than 7, because acid remains in excess", "is_correct": False},
            {"label": "B", "text": "Exactly 7, because moles of acid equal moles of base", "is_correct": False},
            {"label": "C", "text": "Greater than 7, because the conjugate base formed makes the solution basic", "is_correct": True},
            {"label": "D", "text": "Undefined without knowing the exact volumes used", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "At the equivalence point, moles of acid and base are exactly equal, so no excess acid remains.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This assumes equivalence point always means neutral pH, which is only true for strong acid-strong base titrations.", "misconception_tag": "assumes-equivalence-point-is-always-ph-7"},
            {"option_label": "C", "explanation": "Correct: the weak acid is fully converted to its conjugate base at equivalence, which hydrolyzes water to produce a basic solution (pH > 7).", "misconception_tag": None},
            {"option_label": "D", "explanation": "The qualitative direction of the pH (basic) can be determined from the chemistry alone, without needing exact volumes.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Unit 9: Applications of Thermodynamics
    # ---------------------------------------------------------------
    {
        "unit_name": "Applications of Thermodynamics",
        "topic_name": "Entropy and Gibbs Free Energy",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A reaction has delta H = +40 kJ and delta S = +120 J/K. At what approximate temperature does the reaction become spontaneous?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["entropy", "gibbs-free-energy"],
        "misconception_tags": ["forgets-unit-conversion-between-kj-and-j"],
        "options": [
            {"label": "A", "text": "Above 3 K", "is_correct": False},
            {"label": "B", "text": "Above 333 K", "is_correct": True},
            {"label": "C", "text": "Below 333 K", "is_correct": False},
            {"label": "D", "text": "The reaction is spontaneous at all temperatures", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This fails to convert delta H from kJ to J before dividing by delta S in J/K, giving a value 1000x too small.", "misconception_tag": "forgets-unit-conversion-between-kj-and-j"},
            {"option_label": "B", "explanation": "Correct: T = delta H / delta S = 40000 J / 120 J/K = 333 K; since both delta H and delta S are positive, the reaction becomes spontaneous (delta G < 0) above this temperature.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This reverses the inequality; with positive delta H and delta S, spontaneity is favored at high temperature, not low.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Since delta H is positive, the reaction is not spontaneous at low temperatures where the TdeltaS term is too small to overcome it.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Applications of Thermodynamics",
        "topic_name": "Galvanic and Electrolytic Cells",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "In a galvanic cell with standard reduction potentials E(Cu2+/Cu) = +0.34 V and E(Zn2+/Zn) = -0.76 V, what is the standard cell potential?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["electrochemistry", "galvanic-cells"],
        "misconception_tags": ["subtracts-potentials-in-wrong-order"],
        "options": [
            {"label": "A", "text": "-1.10 V", "is_correct": False},
            {"label": "B", "text": "-0.42 V", "is_correct": False},
            {"label": "C", "text": "0.42 V", "is_correct": False},
            {"label": "D", "text": "1.10 V", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This subtracts cathode minus anode with the signs flipped, giving the correct magnitude but wrong sign.", "misconception_tag": "subtracts-potentials-in-wrong-order"},
            {"option_label": "B", "explanation": "This incorrectly adds the two potentials with a sign error instead of subtracting E(anode) from E(cathode).", "misconception_tag": "subtracts-potentials-in-wrong-order"},
            {"option_label": "C", "explanation": "This has the correct process but an arithmetic slip; 0.34 - (-0.76) = 1.10, not 0.42.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct: Cu2+/Cu (higher potential) is the cathode and Zn2+/Zn is the anode, so E_cell = E(cathode) - E(anode) = 0.34 - (-0.76) = 1.10 V.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    # ---------------------------------------------------------------
    # Free Response Questions (single-part, MVP simplicity)
    # ---------------------------------------------------------------
    {
        "unit_name": "Chemical Reactions",
        "topic_name": "Stoichiometry and Limiting Reagents",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Given the balanced equation 2Al(s) + 3CuSO4(aq) -> Al2(SO4)3(aq) + 3Cu(s), calculate the mass of Cu produced when 5.40 g of Al reacts completely with excess CuSO4. (Molar mass Al = 27.0 g/mol, Cu = 63.5 g/mol)",
        "correct_answer": "Approximately 19.1 g of Cu is produced (0.200 mol Al -> 0.300 mol Cu -> 19.1 g).",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["stoichiometry", "moles"],
        "misconception_tags": ["uses-wrong-mole-ratio"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response converts 5.40 g Al to moles (5.40/27.0 = 0.200 mol Al), applies the 2:3 mole ratio of Al to Cu from the balanced equation (0.200 mol Al x 3/2 = 0.300 mol Cu), and converts to mass (0.300 mol x 63.5 g/mol = 19.1 g Cu). A common error is using a 1:1 mole ratio instead of the correct 2:3 ratio from the balanced equation.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Converts given mass of Al to moles using correct molar mass", "keywords": ["27.0", "moles Al", "0.200 mol"], "points": 1},
                {"point": "Applies the correct 2:3 mole ratio of Al to Cu from the balanced equation", "keywords": ["mole ratio", "2:3", "3/2"], "points": 1},
                {"point": "Converts moles of Cu to mass using correct molar mass and reports a correctly rounded final answer with units", "keywords": ["63.5", "19.1 g", "grams"], "points": 2},
            ]
        },
    },
    {
        "unit_name": "Thermodynamics",
        "topic_name": "Calorimetry",
        "type": "frq",
        "difficulty": 2,
        "prompt": "A 50.0 g sample of water at 25.0 C absorbs 2510 J of heat. What is the final temperature of the water? (Specific heat of water = 4.18 J/(g*C))",
        "correct_answer": "Final temperature is approximately 37.0 C (delta T = 12.0 C, so 25.0 + 12.0 = 37.0 C).",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["calorimetry"],
        "misconception_tags": ["forgets-to-add-initial-temperature"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response uses q = mCdeltaT, solving for deltaT = q/(mC) = 2510/(50.0 x 4.18) = 12.0 C, then adds this to the initial temperature: 25.0 + 12.0 = 37.0 C. A common error is reporting deltaT (12.0 C) alone as the final answer instead of adding it to the initial temperature.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Sets up q = mCdeltaT correctly with given values", "keywords": ["q = mC", "2510", "4.18"], "points": 1},
                {"point": "Solves correctly for delta T with correct units", "keywords": ["delta T", "12.0"], "points": 1},
                {"point": "Adds delta T to initial temperature to report a correct final answer", "keywords": ["37.0", "final temperature"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Equilibrium",
        "topic_name": "Calculating the Equilibrium Constant",
        "type": "frq",
        "difficulty": 4,
        "prompt": "For the reaction H2(g) + I2(g) <-> 2HI(g), at equilibrium [H2] = 0.020 M, [I2] = 0.020 M, and [HI] = 0.160 M. Calculate the value of Kc.",
        "correct_answer": "Kc = 64 (calculated as (0.160)^2 / [(0.020)(0.020)] = 0.0256 / 0.0004 = 64).",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["equilibrium-constant", "ice-table"],
        "misconception_tags": ["writes-equilibrium-expression-upside-down"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response writes Kc = [HI]^2/([H2][I2]), substitutes the equilibrium concentrations, and calculates Kc = (0.160)^2/((0.020)(0.020)) = 64. A common error is inverting the expression (placing reactants over products), which would give 1/64 instead.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Writes the correct equilibrium constant expression with products over reactants", "keywords": ["Kc", "[HI]^2", "[H2][I2]"], "points": 1},
                {"point": "Substitutes the correct equilibrium concentrations into the expression", "keywords": ["0.160", "0.020"], "points": 1},
                {"point": "Calculates and reports the correct numerical value of Kc", "keywords": ["64"], "points": 2},
            ]
        },
    },
    {
        "unit_name": "Acids and Bases",
        "topic_name": "pH and pOH Calculations",
        "type": "frq",
        "difficulty": 3,
        "prompt": "A solution has a pOH of 4.00. Calculate the pH of this solution and state whether it is acidic or basic.",
        "correct_answer": "pH = 10.00 (since pH + pOH = 14.00); the solution is basic because pH > 7.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["ph-calculations"],
        "misconception_tags": ["confuses-ph-and-poh-relationship"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response applies pH + pOH = 14.00 at 25 C, solves pH = 14.00 - 4.00 = 10.00, and correctly identifies the solution as basic since pH > 7. A common error is reporting pOH itself as the pH, or misjudging acidity/basicity from the pOH value directly.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Applies the correct relationship pH + pOH = 14.00", "keywords": ["pH + pOH", "14.00"], "points": 1},
                {"point": "Calculates the correct numerical pH value", "keywords": ["10.00"], "points": 1},
                {"point": "Correctly classifies the solution as basic with valid reasoning (pH > 7)", "keywords": ["basic", "pH > 7"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Intermolecular Forces and Properties",
        "topic_name": "Ideal Gas Law",
        "type": "frq",
        "difficulty": 2,
        "prompt": "A sample of gas occupies 4.00 L at a pressure of 1.50 atm. If the pressure is increased to 3.00 atm at constant temperature, what is the new volume?",
        "correct_answer": "New volume is 2.00 L, using Boyle's Law: P1V1 = P2V2, so V2 = (1.50 x 4.00)/3.00 = 2.00 L.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["gas-laws", "ideal-gas-law"],
        "misconception_tags": ["inverts-boyles-law-ratio"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response applies Boyle's Law (P1V1 = P2V2) since temperature and moles are constant, solving V2 = P1V1/P2 = (1.50 atm x 4.00 L)/3.00 atm = 2.00 L. A common error is inverting the ratio and multiplying instead of dividing, producing 8.00 L.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies and correctly sets up Boyle's Law (P1V1 = P2V2) for the constant-temperature scenario", "keywords": ["P1V1", "P2V2", "Boyle"], "points": 1},
                {"point": "Solves algebraically for the new volume with correct substitution", "keywords": ["V2", "1.50", "3.00"], "points": 1},
                {"point": "Reports a correct final answer with appropriate units", "keywords": ["2.00 L"], "points": 1},
            ]
        },
    },
]
