"""Original Java and data-reasoning practice for the current CSA course map."""
from scripts.seed_data.questions.authored_mcq import build_questions
from scripts.seed_data.units_topics.computer_science_a import UNITS

ITEMS = [
    ("Expressions and Assignment Statements",
     "What is printed by this Java code?\nint a = 7;\nint b = 2;\nSystem.out.println(a / b);",
     "3", ["3.5", "4", "The code does not compile"],
     "Both operands are int values, so Java performs integer division and truncates toward zero. The result of 7 / 2 is 3. A floating-point operand would be needed to obtain 3.5."),
    ("Compound Assignment Operators",
     "What is the final value of x?\nint x = 4;\nx += 3;\nx *= 2;",
     "14", ["10", "11", "8"],
     "The first compound assignment changes x from 4 to 7. The second multiplies that updated value by 2, yielding 14. Each statement changes the variable before the next statement executes."),
    ("Objects: Instances of Classes",
     "A class Counter contains a nonstatic int field count. Two distinct Counter objects are created. Which statement is correct?",
     "Each object has its own count field",
     ["All objects necessarily share the same nonstatic count field", "An instance field exists only once per class", "Creating a second object deletes the first object's fields"],
     "Nonstatic fields belong to individual instances. Distinct objects have distinct field storage, even when their values happen to match. A static field, by contrast, is associated with the class rather than with each object."),
    ("Calling a Void Method",
     "A class defines public void reset(). Which use is valid when c refers to an instance of that class?",
     "c.reset();", ["int n = c.reset();", "boolean b = c.reset();", "String s = c.reset();"],
     "A void method does not return a value for assignment. It can be invoked as a statement, such as c.reset(). Its effects may include changing object state, but there is no int, boolean, or String result to store."),
    ("Documentation with Comments",
     "Which Java comment best documents the purpose of a method that returns the number of positive values in an array?",
     "/** Returns the count of elements greater than zero in values. */",
     ["/** Increases i by one. */", "/** This method always changes every array element. */", "/** Ignores its input and returns an arbitrary number. */"],
     "Useful method documentation describes its contract and behavior, not just an incidental implementation step. Here the contract is to count elements greater than zero; zero and negative values do not contribute."),
    ("Algorithms and Compilers",
     "A Java program contains a missing semicolon. At which stage is this syntax problem typically detected?",
     "Compilation", ["Only after the program has produced correct output", "Only during a database backup", "Only when the user changes the computer's clock"],
     "A compiler checks source-code syntax and types while translating the program. A missing required semicolon is a compile-time issue, unlike a logical error that may allow execution but produce an incorrect result."),
    ("APIs and Method Signatures",
     "A method has signature public static int clamp(int value, int low, int high). Which call matches its parameter types and count?",
     "clamp(8, 0, 10)", ["clamp(8)", "clamp(8.5, 0, 10)", "clamp(\"8\", 0, 10)"],
     "The method requires three int arguments in the stated order. A double or String is not implicitly accepted where an int is required, and omitting two arguments does not match this signature."),
    ("Math Class Methods",
     "Which Java expression produces an int uniformly selected from 1 through 6, assuming the usual behavior of Math.random()?",
     "(int)(Math.random() * 6) + 1",
     ["(int)Math.random() * 6 + 1", "(int)(Math.random() * 5) + 1", "(int)(Math.random() * 6)"],
     "Math.random() is at least 0 and less than 1. Multiplying by 6 and casting gives an integer from 0 through 5; adding 1 yields 1 through 6. Casting before multiplication would always produce zero."),
    ("Boolean Expressions",
     "If x is 5 and y is 8, what is the value of (x < y) && (y < 10)?",
     "true", ["false", "5", "A compile-time error because && cannot combine comparisons"],
     "Both comparisons are true: 5 < 8 and 8 < 10. Logical AND returns true only when both operands are true. Each comparison produces a boolean, so && can combine them."),
    ("Equivalent Boolean Expressions",
     "Which expression is equivalent to !(a || b) for boolean variables a and b?",
     "!a && !b", ["!a || !b", "a && b", "a || !b"],
     "De Morgan's law distributes negation while changing OR to AND. Not having either a or b means both a and b are false. Negating the operands without changing the operator would produce a different truth table."),
    ("Developing Algorithms Using Strings",
     "What value does count have after this code?\nString s = \"banana\";\nint count = 0;\nfor (int i = 0; i < s.length(); i++)\n    if (s.substring(i, i + 1).equals(\"a\")) count++;",
     "3", ["2", "5", "6"],
     "The loop examines each one-character substring, including the final character. The letter a appears at indices 1, 3, and 5, so the counter increments three times. String content is compared with equals."),
    ("Informal Run-Time Analysis",
     "How many times does total++ execute, as a function of positive integer n?\nfor (int i = 0; i < n; i++)\n    for (int j = 0; j < n; j++)\n        total++;",
     "n²", ["n", "2n", "n + 1"],
     "For each of n outer iterations, the inner loop runs n times. Multiplying gives n × n executions. Two separate consecutive loops would give approximately 2n, but these loops are nested."),
    ("Anatomy of a Class",
     "Which declaration best encapsulates an integer balance inside a BankAccount class while allowing public methods to control access?",
     "private int balance;", ["public int balance;", "public static int balance;", "An undeclared variable used only by callers"],
     "A private instance field hides the representation from direct outside access and gives each account its own balance. Public methods can enforce rules for changing it. A static field would instead be shared by the class."),
    ("Constructors",
     "Which declaration is a valid constructor for a Java class named Book?",
     "public Book(String title) { }", ["public void Book(String title) { }", "public int Book(String title) { return 0; }", "public constructor(String title) { }"],
     "A constructor has the class's name and no return type. Adding void or int makes the declaration a method rather than a constructor. The name constructor does not match the class name Book."),
    ("Scope and Access",
     "An int variable is declared inside the body of a for loop. Which statement about its scope is correct?",
     "It cannot be referenced after that loop body's block ends",
     ["It automatically becomes a public field", "It is accessible from every method in the program", "It remains in scope for the rest of the source file"],
     "A local variable declared within a block is scoped to that block after its declaration. Once execution leaves the block, code outside it cannot refer to that local name. This differs from an instance or class field."),
    ("Abstraction and Responsible Program Design",
     "A library exposes a method that returns a customer's age without exposing its internal storage format. What design principle is illustrated?",
     "Abstraction through a stable interface", ["Making every field public", "Requiring callers to copy the library's internal code", "Preventing all future implementation changes"],
     "An interface specifies what an operation provides while hiding how data is represented. Callers can use the behavior without depending on implementation details, making internal changes easier when the public contract stays consistent."),
    ("Passing Object References",
     "What is printed?\nstatic void change(int[] a) { a[0] = 9; }\n// In a calling method:\nint[] values = {1, 2};\nchange(values);\nSystem.out.println(values[0]);",
     "9", ["1", "2", "The method receives a complete copy of the array"],
     "Java passes the reference value by value. The parameter and caller's variable initially refer to the same array, so changing its element is visible to the caller. Reassigning the local parameter to a different array would be a different operation."),
    ("The this Keyword",
     "A constructor parameter has the same name as an instance field. What does this.name = name; do inside the constructor?",
     "Assigns the parameter value to the current object's name field",
     ["Assigns the field to itself and ignores the parameter", "Creates a new static variable", "Changes every object's name field"],
     "this.name identifies the field belonging to the current object. The unqualified name resolves to the parameter that shadows it. The assignment initializes one object's field, not a static field shared by all objects."),
    ("Enhanced for Loop for Arrays",
     "What is printed after this code?\nint[] a = {2, 4};\nfor (int value : a) value = 0;\nSystem.out.println(a[0]);",
     "2", ["0", "4", "The loop removes all array elements"],
     "For a primitive array, the enhanced-for variable receives a copy of each element's value. Assigning to that local variable does not assign to the array slot. An indexed assignment such as a[i] = 0 would change the array."),
    ("Introduction to ArrayList",
     "Which declaration creates an initially empty ArrayList that stores String references? Assume the appropriate import is present.",
     "ArrayList<String> words = new ArrayList<String>();",
     ["ArrayList<int> words = new ArrayList<int>();", "String words = new ArrayList<String>();", "ArrayList<String> words = new String[10];"],
     "The generic type String specifies the element reference type, and the constructor creates an empty list. Primitive int cannot be a generic type argument; Integer is its wrapper. Arrays and ArrayLists are distinct types."),
    ("Data Ethics and Privacy",
     "A school app needs aggregate study-time statistics. Which design best follows data minimization?",
     "Collect only the information needed for the stated purpose and restrict access",
     ["Collect precise location continuously because it might be useful someday", "Publish identifiable student records without consent", "Keep every unused personal field indefinitely by default"],
     "Data minimization limits collection and retention to a defined purpose, reducing unnecessary privacy exposure. Restricting access adds protection. Collecting unrelated personal data or publishing identifying information does not become justified merely because a system can do it."),
    ("Using Data Sets",
     "An app estimates the study habits of all students using responses only from volunteers in an advanced programming club. What is a key limitation?",
     "The sample may not represent the broader student population",
     ["A large spreadsheet automatically removes sampling bias", "Every volunteer sample exactly represents all students", "Sorting the rows alphabetically guarantees generalizability"],
     "Club membership and voluntary response can select people whose habits differ from the target population. Data volume or sorting cannot by itself correct that selection problem. Conclusions should acknowledge the sampling process."),
    ("Using Text Files",
     "A Scanner named input is connected to a text file containing integers. Which loop safely reads integers until the next token is no longer an integer or no tokens remain?",
     "while (input.hasNextInt()) { int n = input.nextInt(); }",
     ["while (true) { int n = input.nextInt(); }", "while (input.nextInt()) { }", "while (input.hasNextInt()) { }"],
     "hasNextInt checks whether the next token can be read as an int, and nextInt consumes it. Without consuming input the condition can remain true forever. Unconditional reads can fail at end-of-file or on a noninteger token."),
    ("Searching Algorithms",
     "Which precondition is necessary for a standard binary search to work correctly on an array of integers?",
     "The array is sorted in the ordering assumed by the search",
     ["The array contains exactly two elements", "Every value is positive", "Every value has the same number of digits"],
     "Binary search eliminates half the remaining positions using the ordering relationship with the middle element. Without sorted order, an eliminated half might contain the target. Positivity, digit count, and an array size of two are not required."),
    ("Sorting Algorithms",
     "Selection sort chooses the smallest remaining element for each position. What is the array after the first pass over {4, 1, 3, 2}, sorting in ascending order?",
     "{1, 4, 3, 2}", ["{1, 2, 3, 4}", "{4, 1, 2, 3}", "{2, 1, 3, 4}"],
     "The first pass finds the smallest element, 1, and exchanges it with the element at index 0. The remaining elements need not yet be sorted, so one pass yields {1, 4, 3, 2}, not the final sorted array."),
]
QUESTIONS = build_questions(UNITS, ITEMS)
