"""Demo-scale seed question bank for AP Computer Science A.

This is NOT an exhaustive question bank -- it is a modest seed set meant to
exercise the app's flows end-to-end (roughly 2-3 MCQs per unit plus a
handful of FRQs). Every unit_name/topic_name pair below matches a name
defined in units_topics/computer_science_a.py exactly.
"""

QUESTIONS = [
    # --- Unit 1: Primitive Types ---
    {
        "unit_name": "Primitive Types",
        "topic_name": "Variables and Data Types",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Which of the following is a valid declaration and initialization of an int variable in Java?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["variables", "primitive-types"],
        "misconception_tags": ["confuses-string-and-numeric-literal-syntax"],
        "options": [
            {"label": "A", "text": "int x = \"5\";", "is_correct": False},
            {"label": "B", "text": "Int x = 5;", "is_correct": False},
            {"label": "C", "text": "int x = 5;", "is_correct": True},
            {"label": "D", "text": "int x == 5;", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "A quoted value is a String literal, not an int; this would not compile.", "misconception_tag": "confuses-string-and-numeric-literal-syntax"},
            {"option_label": "B", "explanation": "Java is case-sensitive; 'Int' is not a recognized type keyword.", "misconception_tag": "ignores-case-sensitivity"},
            {"option_label": "C", "explanation": "Correct: lowercase 'int' type, valid identifier, single '=' for assignment.", "misconception_tag": None},
            {"option_label": "D", "explanation": "'==' is the equality comparison operator, not assignment, and cannot appear in a declaration this way.", "misconception_tag": "confuses-equals-with-double-equals"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Primitive Types",
        "topic_name": "Casting and Ranges of Variables",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nint x = 5;\nint y = 2;\nSystem.out.println(x / y);",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["casting", "integer-division"],
        "misconception_tags": ["expects-float-division-result"],
        "options": [
            {"label": "A", "text": "2.5", "is_correct": False},
            {"label": "B", "text": "2", "is_correct": True},
            {"label": "C", "text": "3", "is_correct": False},
            {"label": "D", "text": "2.0", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This assumes floating-point division, but both operands are int, so the result is truncated, not rounded to a decimal.", "misconception_tag": "expects-float-division-result"},
            {"option_label": "B", "explanation": "Correct: int divided by int performs integer division, truncating toward zero, giving 2.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This incorrectly rounds up instead of truncating the fractional part.", "misconception_tag": "rounds-instead-of-truncates"},
            {"option_label": "D", "explanation": "The result of int/int is an int, not a double, so there is no decimal point in the output.", "misconception_tag": "expects-float-division-result"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Primitive Types",
        "topic_name": "Casting and Ranges of Variables",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "What is the output of the following code?\ndouble d = 7.9;\nint x = (int) d;\nSystem.out.println(x);",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["casting", "type-conversion"],
        "misconception_tags": ["rounds-instead-of-truncates"],
        "options": [
            {"label": "A", "text": "7", "is_correct": True},
            {"label": "B", "text": "8", "is_correct": False},
            {"label": "C", "text": "7.9", "is_correct": False},
            {"label": "D", "text": "A compile-time error occurs", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: casting a double to int truncates the fractional part rather than rounding, giving 7.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This assumes casting rounds to the nearest integer, but (int) truncates instead.", "misconception_tag": "rounds-instead-of-truncates"},
            {"option_label": "C", "explanation": "Assigning to an int variable cannot retain the decimal portion of the value.", "misconception_tag": "ignores-cast-effect"},
            {"option_label": "D", "explanation": "Narrowing a double to an int is legal in Java as long as an explicit cast is used, so this compiles fine.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # --- Unit 2: Using Objects ---
    {
        "unit_name": "Using Objects",
        "topic_name": "String Class",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "What is the output of the following code?\nString s = \"waypoint\";\nSystem.out.println(s.substring(2, 5));",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["strings", "substring"],
        "misconception_tags": ["off-by-one-substring-bound"],
        "options": [
            {"label": "A", "text": "way", "is_correct": False},
            {"label": "B", "text": "poin", "is_correct": False},
            {"label": "C", "text": "ypo", "is_correct": True},
            {"label": "D", "text": "ypoi", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This uses the wrong starting index; index 2 corresponds to 'y', not 'w'.", "misconception_tag": "off-by-one-substring-bound"},
            {"option_label": "B", "explanation": "This does not match the requested start index of 2.", "misconception_tag": "off-by-one-substring-bound"},
            {"option_label": "C", "explanation": "Correct: substring(2, 5) returns characters from index 2 up to but not including index 5: 'y','p','o'.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This incorrectly includes the character at the end index, treating the range as inclusive.", "misconception_tag": "off-by-one-substring-bound"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Using Objects",
        "topic_name": "Calling a Method That Returns a Value",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Given the method:\npublic int square(int n) {\n    return n * n;\n}\nWhat is the result of the call square(4) + 1?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["methods", "return-values"],
        "misconception_tags": ["ignores-operator-precedence"],
        "options": [
            {"label": "A", "text": "8", "is_correct": False},
            {"label": "B", "text": "25", "is_correct": False},
            {"label": "C", "text": "9", "is_correct": False},
            {"label": "D", "text": "17", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This computes 4 * 2 instead of squaring, misreading the method body.", "misconception_tag": "misreads-method-body"},
            {"option_label": "B", "explanation": "This squares 5 (as if the +1 happened before the call), instead of adding 1 after squaring 4.", "misconception_tag": "ignores-operator-precedence"},
            {"option_label": "C", "explanation": "This is 3 squared, not 4 squared plus one; the argument value was misapplied.", "misconception_tag": "misreads-method-body"},
            {"option_label": "D", "explanation": "Correct: square(4) returns 16, and 16 + 1 = 17.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Using Objects",
        "topic_name": "Wrapper Classes and Autoboxing",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nInteger a = 100;\nint b = a;\nSystem.out.println(a + b);",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["wrapper-classes", "autoboxing"],
        "misconception_tags": ["thinks-wrapper-cannot-mix-with-primitive"],
        "options": [
            {"label": "A", "text": "A compile-time error occurs", "is_correct": False},
            {"label": "B", "text": "200", "is_correct": True},
            {"label": "C", "text": "100100", "is_correct": False},
            {"label": "D", "text": "0", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Autoboxing and auto-unboxing let Integer and int mix freely in arithmetic; this is legal code.", "misconception_tag": "thinks-wrapper-cannot-mix-with-primitive"},
            {"option_label": "B", "explanation": "Correct: a auto-unboxes to 100, b is 100, and 100 + 100 = 200.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This treats + as string concatenation, but both operands are numeric here, so they are added.", "misconception_tag": "confuses-plus-with-concatenation"},
            {"option_label": "D", "explanation": "There is no reason the sum would be zero; both variables hold valid values of 100.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # --- Unit 3: Boolean Expressions and if Statements ---
    {
        "unit_name": "Boolean Expressions and if Statements",
        "topic_name": "if-else Statements",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "What is the output of the following code?\nint x = 7;\nif (x > 10) {\n    System.out.println(\"big\");\n} else if (x > 5) {\n    System.out.println(\"medium\");\n} else {\n    System.out.println(\"small\");\n}",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["conditionals", "control-flow"],
        "misconception_tags": ["thinks-multiple-branches-execute"],
        "options": [
            {"label": "A", "text": "big", "is_correct": False},
            {"label": "B", "text": "medium", "is_correct": True},
            {"label": "C", "text": "small", "is_correct": False},
            {"label": "D", "text": "medium and small", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "7 is not greater than 10, so this branch is skipped.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct: 7 is not greater than 10 but is greater than 5, so 'medium' prints and no further branch runs.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The else branch only runs if none of the earlier conditions are true; 7 > 5 is true, so this is never reached.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Only one branch of an if/else-if/else chain ever executes, not multiple.", "misconception_tag": "thinks-multiple-branches-execute"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Boolean Expressions and if Statements",
        "topic_name": "Compound Boolean Expressions",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "What is the output of the following code?\nint a = 5, b = 10;\nif (!(a > b) && (b % 5 == 0)) {\n    System.out.println(\"yes\");\n} else {\n    System.out.println(\"no\");\n}",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["boolean-logic", "compound-expressions"],
        "misconception_tags": ["misapplies-negation-to-compound-expression"],
        "options": [
            {"label": "A", "text": "yes", "is_correct": True},
            {"label": "B", "text": "no", "is_correct": False},
            {"label": "C", "text": "A compile-time error occurs", "is_correct": False},
            {"label": "D", "text": "yes, printed twice", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: a > b is false, so !(a > b) is true; b % 5 == 0 is true; true && true is true, printing 'yes'.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This likely mis-evaluates the negation, treating !(a > b) as false when a > b is actually false.", "misconception_tag": "misapplies-negation-to-compound-expression"},
            {"option_label": "C", "explanation": "The expression is valid Java syntax with matched parentheses and legal operators.", "misconception_tag": None},
            {"option_label": "D", "explanation": "An if/else block executes exactly one branch exactly once.", "misconception_tag": "thinks-multiple-branches-execute"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Boolean Expressions and if Statements",
        "topic_name": "if Statements and Control Flow",
        "type": "frq",
        "difficulty": 2,
        "prompt": "Write a Java method called isEligible that takes an int age and a boolean hasPermission, and returns true if age is at least 18 OR hasPermission is true; otherwise it returns false.",
        "correct_answer": "public boolean isEligible(int age, boolean hasPermission) {\n    if (age >= 18 || hasPermission) {\n        return true;\n    } else {\n        return false;\n    }\n}",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["conditionals", "boolean-logic"],
        "misconception_tags": ["confuses-and-with-or"],
        "explanations": [
            {"option_label": None, "explanation": "A correct solution declares a boolean method with parameters age and hasPermission, and returns true when age >= 18 OR hasPermission is true (equivalently, 'return age >= 18 || hasPermission;'), returning false otherwise.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Uses correct method signature/return type (public boolean isEligible(int age, boolean hasPermission))", "keywords": ["public", "boolean", "isEligible", "return"], "points": 1},
                {"point": "Uses logical OR (||) to combine the two conditions, not AND", "keywords": ["||", ">="], "points": 2},
                {"point": "Returns correct boolean values for edge cases (e.g., age exactly 18, hasPermission true with low age)", "keywords": ["true", "false"], "points": 1},
            ]
        },
    },

    # --- Unit 4: Iteration ---
    {
        "unit_name": "Iteration",
        "topic_name": "for Loops",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "What is the output of the following code?\nfor (int i = 0; i < 5; i++) {\n    System.out.print(i + \" \");\n}",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["loops", "for-loop"],
        "misconception_tags": ["off-by-one-loop-bound"],
        "options": [
            {"label": "A", "text": "1 2 3 4 5", "is_correct": False},
            {"label": "B", "text": "0 1 2 3 4", "is_correct": True},
            {"label": "C", "text": "0 1 2 3 4 5", "is_correct": False},
            {"label": "D", "text": "1 2 3 4", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This assumes the loop starts at 1, but i is initialized to 0.", "misconception_tag": "off-by-one-loop-bound"},
            {"option_label": "B", "explanation": "Correct: i starts at 0 and the loop runs while i < 5, printing 0 through 4.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This incorrectly includes 5, treating the bound as inclusive rather than exclusive.", "misconception_tag": "off-by-one-loop-bound"},
            {"option_label": "D", "explanation": "This starts at 1 and stops one iteration too early, mishandling both the start value and the bound.", "misconception_tag": "off-by-one-loop-bound"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Iteration",
        "topic_name": "while Loops",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nint count = 0;\nint total = 0;\nwhile (count < 4) {\n    total += count;\n    count++;\n}\nSystem.out.println(total);",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["loops", "while-loop"],
        "misconception_tags": ["miscounts-loop-iterations"],
        "options": [
            {"label": "A", "text": "4", "is_correct": False},
            {"label": "B", "text": "10", "is_correct": False},
            {"label": "C", "text": "6", "is_correct": True},
            {"label": "D", "text": "0", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This confuses the final value of count with the accumulated total.", "misconception_tag": "confuses-counter-with-accumulator"},
            {"option_label": "B", "explanation": "This assumes the loop runs one extra time and sums 0 through 4, but count stops at 4 and the loop body does not execute when count == 4.", "misconception_tag": "off-by-one-loop-bound"},
            {"option_label": "C", "explanation": "Correct: total accumulates 0 + 1 + 2 + 3 = 6 over four iterations (count = 0,1,2,3).", "misconception_tag": None},
            {"option_label": "D", "explanation": "This assumes total is never updated, but += modifies it each iteration.", "misconception_tag": "miscounts-loop-iterations"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Iteration",
        "topic_name": "Nested Iteration",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "What is the output of the following code?\nfor (int i = 1; i <= 3; i++) {\n    for (int j = 1; j <= i; j++) {\n        System.out.print(\"*\");\n    }\n    System.out.println();\n}",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["loops", "nested-loops"],
        "misconception_tags": ["confuses-inner-and-outer-loop-bound"],
        "options": [
            {"label": "A", "text": "*\n**\n***", "is_correct": True},
            {"label": "B", "text": "***\n***\n***", "is_correct": False},
            {"label": "C", "text": "***\n**\n*", "is_correct": False},
            {"label": "D", "text": "*\n**\n***\n****", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: the inner loop runs i times for each outer iteration, producing rows of 1, 2, then 3 asterisks.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This assumes the inner loop always runs 3 times, ignoring that its bound depends on i.", "misconception_tag": "confuses-inner-and-outer-loop-bound"},
            {"option_label": "C", "explanation": "This reverses the pattern, as if the row lengths decreased instead of increased.", "misconception_tag": "confuses-inner-and-outer-loop-bound"},
            {"option_label": "D", "explanation": "This adds an extra row beyond what the outer loop bound (i <= 3) allows.", "misconception_tag": "off-by-one-loop-bound"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Iteration",
        "topic_name": "for Loops",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Write a Java method called sumEvens that takes an int parameter n and returns the sum of all even integers from 1 to n, inclusive. For example, sumEvens(10) should return 30 (2+4+6+8+10).",
        "correct_answer": "public int sumEvens(int n) {\n    int sum = 0;\n    for (int i = 1; i <= n; i++) {\n        if (i % 2 == 0) {\n            sum += i;\n        }\n    }\n    return sum;\n}",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["loops", "for-loop", "conditionals"],
        "misconception_tags": ["off-by-one-loop-bound"],
        "explanations": [
            {"option_label": None, "explanation": "A correct solution declares an int method returning the accumulated sum, iterates from 1 through n inclusive, checks each value for evenness with i % 2 == 0, and adds qualifying values to a running total before returning it.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Uses correct method signature/return type (public int sumEvens(int n))", "keywords": ["public", "int", "sumEvens", "return"], "points": 1},
                {"point": "Implements a loop that iterates through 1 to n inclusive", "keywords": ["for", "<=", "i++"], "points": 1},
                {"point": "Correctly checks for even numbers using modulo", "keywords": ["%", "== 0"], "points": 1},
                {"point": "Accumulates and returns the correct sum for edge cases (e.g., n=1 returns 0)", "keywords": ["sum", "+="], "points": 1},
            ]
        },
    },

    # --- Unit 5: Writing Classes ---
    {
        "unit_name": "Writing Classes",
        "topic_name": "Accessor and Mutator Methods",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which method below correctly follows the convention for a mutator (setter) method for a private instance variable named age in a class Person?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["encapsulation", "accessors-mutators"],
        "misconception_tags": ["confuses-accessor-and-mutator"],
        "options": [
            {"label": "A", "text": "public void setAge(int age) { this.age = age; }", "is_correct": True},
            {"label": "B", "text": "public int setAge() { return age; }", "is_correct": False},
            {"label": "C", "text": "public void getAge(int age) { this.age = age; }", "is_correct": False},
            {"label": "D", "text": "private void setAge(int age) { this.age = age; }", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: a public void method named setAge that takes the new value and assigns it to the instance variable using 'this'.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This has the structure of an accessor (returns a value, no parameter) but is named like a mutator.", "misconception_tag": "confuses-accessor-and-mutator"},
            {"option_label": "C", "explanation": "This performs mutator behavior but is misleadingly named 'getAge', confusing the naming convention.", "misconception_tag": "confuses-accessor-and-mutator"},
            {"option_label": "D", "explanation": "Marking the setter private would prevent other classes from calling it, defeating its purpose as a public interface method.", "misconception_tag": "misuses-access-modifier-on-setter"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Writing Classes",
        "topic_name": "Static Variables and Methods",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Given the class:\npublic class Counter {\n    private static int count = 0;\n    public Counter() {\n        count++;\n    }\n}\nWhat is the value of Counter.count after the code 'new Counter(); new Counter(); new Counter();' executes?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["classes", "static-members"],
        "misconception_tags": ["thinks-static-resets-per-instance"],
        "options": [
            {"label": "A", "text": "0", "is_correct": False},
            {"label": "B", "text": "1", "is_correct": False},
            {"label": "C", "text": "3", "is_correct": True},
            {"label": "D", "text": "A compile-time error occurs because count is private", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The constructor increments count each time it runs, so it does not remain at its initial value.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This assumes static fields reset for each new object, but a static field is shared across all instances of the class.", "misconception_tag": "thinks-static-resets-per-instance"},
            {"option_label": "C", "explanation": "Correct: count is static, so it is shared by all instances; each of the three constructor calls increments the same field, giving 3.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The private modifier restricts access from outside the class, but the class's own constructor can still access and modify its own private static field.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # --- Unit 6: Array ---
    {
        "unit_name": "Array",
        "topic_name": "Array Creation and Access",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "What is the output of the following code?\nint[] nums = {10, 20, 30, 40};\nSystem.out.println(nums[2]);",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["arrays", "indexing"],
        "misconception_tags": ["off-by-one-array-index"],
        "options": [
            {"label": "A", "text": "10", "is_correct": False},
            {"label": "B", "text": "20", "is_correct": False},
            {"label": "C", "text": "30", "is_correct": True},
            {"label": "D", "text": "40", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This corresponds to index 0, not index 2.", "misconception_tag": "off-by-one-array-index"},
            {"option_label": "B", "explanation": "This corresponds to index 1; array indices are zero-based, so index 2 is the third element.", "misconception_tag": "off-by-one-array-index"},
            {"option_label": "C", "explanation": "Correct: arrays are zero-indexed, so nums[2] refers to the third element, 30.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This assumes indexing starts at 1, treating nums[2] as the second element.", "misconception_tag": "off-by-one-array-index"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Array",
        "topic_name": "Traversing Arrays",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nint[] arr = {2, 4, 6, 8};\nint sum = 0;\nfor (int i = 0; i <= arr.length; i++) {\n    sum += arr[i];\n}\nSystem.out.println(sum);",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["arrays", "loops"],
        "misconception_tags": ["off-by-one-array-index"],
        "options": [
            {"label": "A", "text": "20", "is_correct": False},
            {"label": "B", "text": "0", "is_correct": False},
            {"label": "C", "text": "14", "is_correct": False},
            {"label": "D", "text": "An ArrayIndexOutOfBoundsException occurs", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is the correct sum of all elements, but it assumes the loop terminates safely, which it does not with this bound.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The loop does execute and does accumulate values before it fails; it does not simply produce zero.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This omits an element as if the loop stopped early, but the actual issue is the loop reads one index too far.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct: using i <= arr.length allows i to reach arr.length (4), which is out of bounds for a length-4 array (valid indices 0-3), throwing an exception.", "misconception_tag": "off-by-one-array-index"},
        ],
        "rubric_json": None,
    },

    # --- Unit 7: ArrayList ---
    {
        "unit_name": "ArrayList",
        "topic_name": "ArrayList Methods",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nArrayList<Integer> list = new ArrayList<Integer>();\nlist.add(5);\nlist.add(10);\nlist.add(15);\nlist.remove(1);\nSystem.out.println(list);",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["arraylist", "methods"],
        "misconception_tags": ["confuses-remove-index-with-remove-value"],
        "options": [
            {"label": "A", "text": "[10, 15]", "is_correct": False},
            {"label": "B", "text": "[5, 15]", "is_correct": True},
            {"label": "C", "text": "[5, 10]", "is_correct": False},
            {"label": "D", "text": "[5, 10, 15]", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This assumes remove(1) drops the first element (index 0), but it actually removes the element at index 1.", "misconception_tag": "off-by-one-array-index"},
            {"option_label": "B", "explanation": "Correct: remove(1) with an int argument removes the element at index 1 (the value 10), leaving [5, 15].", "misconception_tag": None},
            {"option_label": "C", "explanation": "This assumes the last element was removed, but remove(1) targets index 1, not the end of the list.", "misconception_tag": "confuses-remove-index-with-remove-value"},
            {"option_label": "D", "explanation": "This shows the list as if remove(1) had no effect at all, but the call does remove one element.", "misconception_tag": "confuses-remove-index-with-remove-value"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "ArrayList",
        "topic_name": "Traversing an ArrayList",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which loop correctly prints every element of an ArrayList<String> named names?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["arraylist", "loops"],
        "misconception_tags": ["uses-array-syntax-on-arraylist"],
        "options": [
            {"label": "A", "text": "for (String n : names) { System.out.println(n); }", "is_correct": True},
            {"label": "B", "text": "for (int i = 0; i < names.length; i++) { System.out.println(names[i]); }", "is_correct": False},
            {"label": "C", "text": "for (int i = 0; i <= names.size(); i++) { System.out.println(names.get(i)); }", "is_correct": False},
            {"label": "D", "text": "while (names) { System.out.println(names); }", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: the enhanced for loop works with ArrayList and correctly prints each String element.", "misconception_tag": None},
            {"option_label": "B", "explanation": "ArrayList has no .length field or [] indexing; it uses .size() and .get(i) instead, since those are array-only syntax.", "misconception_tag": "uses-array-syntax-on-arraylist"},
            {"option_label": "C", "explanation": "Using <= with names.size() causes an IndexOutOfBoundsException on the last iteration since valid indices only go up to size()-1.", "misconception_tag": "off-by-one-loop-bound"},
            {"option_label": "D", "explanation": "An ArrayList is not a boolean condition and cannot be used directly as a while-loop condition; this will not compile.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # --- Unit 8: 2D Array ---
    {
        "unit_name": "2D Array",
        "topic_name": "2D Array Creation and Access",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "What is the output of the following code?\nint[][] grid = {{1, 2, 3}, {4, 5, 6}};\nSystem.out.println(grid[1][2]);",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["2d-arrays", "indexing"],
        "misconception_tags": ["swaps-row-and-column-index"],
        "options": [
            {"label": "A", "text": "2", "is_correct": False},
            {"label": "B", "text": "3", "is_correct": False},
            {"label": "C", "text": "5", "is_correct": False},
            {"label": "D", "text": "6", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is grid[0][1], swapping which index represents the row and using the wrong row entirely.", "misconception_tag": "swaps-row-and-column-index"},
            {"option_label": "B", "explanation": "This is the value at grid[0][2], the wrong row.", "misconception_tag": "swaps-row-and-column-index"},
            {"option_label": "C", "explanation": "This is grid[1][1], one column short of the requested index.", "misconception_tag": "off-by-one-array-index"},
            {"option_label": "D", "explanation": "Correct: grid[1] is the second row {4, 5, 6}, and index 2 of that row is 6.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "2D Array",
        "topic_name": "2D Array Algorithms",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "What is the output of the following code?\nint[][] grid = {{1, 2}, {3, 4}, {5, 6}};\nint sum = 0;\nfor (int i = 0; i < grid.length; i++) {\n    sum += grid[i][0];\n}\nSystem.out.println(sum);",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["2d-arrays", "algorithms"],
        "misconception_tags": ["sums-all-elements-instead-of-one-column"],
        "options": [
            {"label": "A", "text": "9", "is_correct": True},
            {"label": "B", "text": "21", "is_correct": False},
            {"label": "C", "text": "12", "is_correct": False},
            {"label": "D", "text": "6", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: the loop only adds grid[i][0] for each row, summing the first column: 1 + 3 + 5 = 9.", "misconception_tag": None},
            {"option_label": "B", "explanation": "21 is the sum of every element in the grid, but the code only accesses column index 0, not the whole row.", "misconception_tag": "sums-all-elements-instead-of-one-column"},
            {"option_label": "C", "explanation": "12 is the sum of the second column (2 + 4 + 6), but the code uses index 0, not index 1.", "misconception_tag": "swaps-row-and-column-index"},
            {"option_label": "D", "explanation": "This assumes the loop only runs once, but grid.length is 3, so the loop executes three times.", "misconception_tag": "miscounts-loop-iterations"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "2D Array",
        "topic_name": "Traversing 2D Arrays",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Write a Java method called rowSums that takes a 2D int array named grid and returns a 1D int array where each element is the sum of the corresponding row in grid. For example, if grid is {{1,2,3},{4,5,6}}, rowSums(grid) should return {6, 15}.",
        "correct_answer": "public int[] rowSums(int[][] grid) {\n    int[] sums = new int[grid.length];\n    for (int i = 0; i < grid.length; i++) {\n        int sum = 0;\n        for (int j = 0; j < grid[i].length; j++) {\n            sum += grid[i][j];\n        }\n        sums[i] = sum;\n    }\n    return sums;\n}",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["2d-arrays", "nested-loops"],
        "misconception_tags": ["confuses-inner-and-outer-loop-bound"],
        "explanations": [
            {"option_label": None, "explanation": "A correct solution creates a result array sized to the number of rows (grid.length), then for each row uses a nested loop over that row's columns (grid[i].length) to accumulate a sum, storing each row's total in the result array before returning it.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Uses correct method signature/return type (public int[] rowSums(int[][] grid))", "keywords": ["public", "int[]", "rowSums", "return"], "points": 1},
                {"point": "Creates a result array sized to the number of rows", "keywords": ["new int", "grid.length"], "points": 1},
                {"point": "Implements correct nested loop structure summing each row", "keywords": ["for", "grid[i]", "sum"], "points": 2},
            ]
        },
    },

    # --- Unit 9: Inheritance ---
    {
        "unit_name": "Inheritance",
        "topic_name": "Overriding Methods",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Given:\npublic class Animal {\n    public String speak() { return \"...\"; }\n}\npublic class Dog extends Animal {\n    public String speak() { return \"Woof\"; }\n}\nWhat is the output of:\nAnimal a = new Dog();\nSystem.out.println(a.speak());",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["inheritance", "polymorphism"],
        "misconception_tags": ["uses-static-type-instead-of-dynamic-type"],
        "options": [
            {"label": "A", "text": "...", "is_correct": False},
            {"label": "B", "text": "Woof", "is_correct": True},
            {"label": "C", "text": "A compile-time error occurs", "is_correct": False},
            {"label": "D", "text": "null", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This assumes the declared (static) type Animal determines which method runs, but Java uses the actual object's runtime type for overridden methods.", "misconception_tag": "uses-static-type-instead-of-dynamic-type"},
            {"option_label": "B", "explanation": "Correct: method calls on overridden methods use dynamic (runtime) dispatch, so the Dog object's speak() method runs, printing 'Woof'.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Assigning a Dog object to an Animal reference is valid because Dog is a subclass of Animal.", "misconception_tag": None},
            {"option_label": "D", "explanation": "speak() returns a String value in both classes; it never returns null here.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Inheritance",
        "topic_name": "Writing Constructors for Subclasses",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Given:\npublic class Shape {\n    public Shape(String name) { System.out.println(\"Shape: \" + name); }\n}\npublic class Circle extends Shape {\n    public Circle() {\n        super(\"circle\");\n        System.out.println(\"Circle created\");\n    }\n}\nWhat is the output of 'new Circle();'?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["inheritance", "constructors"],
        "misconception_tags": ["reverses-super-constructor-order"],
        "options": [
            {"label": "A", "text": "Shape: circle\nCircle created", "is_correct": True},
            {"label": "B", "text": "Circle created\nShape: circle", "is_correct": False},
            {"label": "C", "text": "Shape: circle", "is_correct": False},
            {"label": "D", "text": "A compile-time error occurs because Shape has no no-arg constructor", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: super(\"circle\") calls the Shape constructor first, printing 'Shape: circle', then the rest of the Circle constructor runs, printing 'Circle created'.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This reverses the actual order; the superclass constructor always completes before the subclass constructor body continues.", "misconception_tag": "reverses-super-constructor-order"},
            {"option_label": "C", "explanation": "This omits the subclass constructor's own print statement, which still executes after the super() call returns.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Circle explicitly calls super(\"circle\"), so Java does not need or insert an implicit no-arg super() call.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Inheritance",
        "topic_name": "The Object Superclass",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Write a toString method for a class Point that has private int fields x and y. The method should override Object's toString and return a String in the format \"(x, y)\", for example \"(3, 4)\".",
        "correct_answer": "public String toString() {\n    return \"(\" + x + \", \" + y + \")\";\n}",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["inheritance", "object-class"],
        "misconception_tags": ["wrong-tostring-signature"],
        "explanations": [
            {"option_label": None, "explanation": "A correct solution overrides toString with the exact signature public String toString() (no parameters), and returns a String built via concatenation that matches the required \"(x, y)\" format exactly, including the comma and space.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Uses correct method signature (public String toString())", "keywords": ["public", "String", "toString"], "points": 1},
                {"point": "Returns a String built from x and y using concatenation", "keywords": ["return", "+", "x", "y"], "points": 2},
                {"point": "Matches the exact required format with parentheses and comma-space separator", "keywords": ["(", ")", ","], "points": 1},
            ]
        },
    },

    # --- Unit 10: Recursion ---
    {
        "unit_name": "Recursion",
        "topic_name": "Tracing Recursive Calls",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "Given the method:\npublic int mystery(int n) {\n    if (n <= 1) {\n        return 1;\n    }\n    return n * mystery(n - 1);\n}\nWhat is the value of mystery(4)?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["recursion", "tracing"],
        "misconception_tags": ["miscomputes-factorial-base-case"],
        "options": [
            {"label": "A", "text": "4", "is_correct": False},
            {"label": "B", "text": "10", "is_correct": False},
            {"label": "C", "text": "24", "is_correct": True},
            {"label": "D", "text": "16", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This only accounts for the outermost call's multiplier n, ignoring the recursive results being multiplied in.", "misconception_tag": None},
            {"option_label": "B", "explanation": "10 is the sum 4+3+2+1, which would be the result of an additive recursive method, not this multiplicative one.", "misconception_tag": "confuses-recursive-sum-with-product"},
            {"option_label": "C", "explanation": "Correct: mystery(4) computes 4 * mystery(3) = 4 * 3 * mystery(2) = 4 * 3 * 2 * mystery(1) = 4 * 3 * 2 * 1 = 24, the factorial of 4.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This computes 4 * 4 as if the method used a fixed n instead of decrementing it, rather than tracing the actual recursive multiplication chain.", "misconception_tag": "miscomputes-factorial-base-case"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Recursion",
        "topic_name": "Recursive Method Structure",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Which of the following is required for a recursive method to terminate correctly?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["recursion", "base-case"],
        "misconception_tags": ["omits-base-case"],
        "options": [
            {"label": "A", "text": "A loop inside the method body", "is_correct": False},
            {"label": "B", "text": "A base case that stops further recursive calls", "is_correct": True},
            {"label": "C", "text": "At least two recursive calls per method", "is_correct": False},
            {"label": "D", "text": "A static variable to track call count", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Recursive methods do not require a loop; recursion itself replaces iteration.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct: without a base case that halts recursion under some condition, the method would call itself indefinitely, causing a stack overflow.", "misconception_tag": None},
            {"option_label": "C", "explanation": "A recursive method needs at least one recursive call, but not necessarily two; many correct recursive methods make only a single recursive call.", "misconception_tag": None},
            {"option_label": "D", "explanation": "A static counter is not required for correct recursive termination; the base case condition alone determines when recursion stops.", "misconception_tag": "omits-base-case"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Recursion",
        "topic_name": "Recursive Searching and Sorting",
        "type": "frq",
        "difficulty": 5,
        "prompt": "Write a recursive Java method called binarySearch that takes a sorted int array arr, and two ints lo and hi representing the current search bounds, and a target int value. The method should return the index of target in arr if found within [lo, hi], or -1 if not found. Assume arr is sorted in ascending order.",
        "correct_answer": "public int binarySearch(int[] arr, int lo, int hi, int target) {\n    if (lo > hi) {\n        return -1;\n    }\n    int mid = (lo + hi) / 2;\n    if (arr[mid] == target) {\n        return mid;\n    } else if (arr[mid] < target) {\n        return binarySearch(arr, mid + 1, hi, target);\n    } else {\n        return binarySearch(arr, lo, mid - 1, target);\n    }\n}",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["recursion", "algorithms"],
        "misconception_tags": ["omits-base-case", "off-by-one-loop-bound"],
        "explanations": [
            {"option_label": None, "explanation": "A correct solution includes a base case returning -1 when lo > hi (search space exhausted), computes a middle index, and recursively searches the left or right half depending on the comparison between arr[mid] and target, always narrowing the range to make progress toward the base case.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Uses correct method signature/return type (public int binarySearch(int[] arr, int lo, int hi, int target))", "keywords": ["public", "int", "binarySearch", "return"], "points": 1},
                {"point": "Includes a base case that returns -1 when the search range is exhausted", "keywords": ["lo", "hi", "-1"], "points": 1},
                {"point": "Computes the midpoint and compares arr[mid] to target", "keywords": ["mid", "arr[mid]", "target"], "points": 1},
                {"point": "Makes correct recursive calls narrowing to the left or right half", "keywords": ["binarySearch", "mid + 1", "mid - 1"], "points": 1},
            ]
        },
    },
]
