"""Original, offline-authored psychology practice with explanatory feedback."""
from scripts.seed_data.questions.authored_mcq import build_questions
from scripts.seed_data.units_topics.psychology import UNITS

ITEMS = [
    ("Introducing Psychology",
     "A student claims that listening to music always improves memory. Which response best reflects psychology as an empirical science?",
     "Define memory performance, collect systematic evidence, and consider alternative explanations",
     ["Accept the claim because one friend agrees", "Reject all claims about mental processes as untestable", "Use personal preference as the only measure of truth"],
     "Empirical psychology evaluates claims using systematically collected observations. Operational definitions and comparison conditions allow researchers to test a claim rather than rely only on intuition or anecdotes."),
    ("Perspectives in Psychology",
     "A researcher explains test anxiety by examining students' interpretations of possible failure. Which perspective is most directly represented?",
     "Cognitive", ["Biological, focusing only on neural anatomy", "Behavioral, focusing only on reinforcement schedules", "Evolutionary, focusing only on inherited reproductive advantages"],
     "The cognitive perspective examines thinking, interpretation, attention, and other mental processes. The same behavior can also be studied at biological or behavioral levels, but the explanation here specifically emphasizes interpretation."),
    ("Interaction of Heredity and Environment",
     "Identical twins have similar genetic backgrounds but can develop different interests and habits. Which conclusion is most appropriate?",
     "Genetic influences interact with experience rather than determining every outcome alone",
     ["Identical twins necessarily share every experience", "Genes have no influence on behavior", "Any behavioral difference proves that the twins are unrelated"],
     "Development reflects both genetic and environmental influences. Similar inherited tendencies can lead to different outcomes in different experiences; a difference does not erase shared genetic influences."),
    ("The Endocrine System",
     "Which description distinguishes endocrine communication from communication across a typical synapse?",
     "Hormones travel through the bloodstream to target cells with suitable receptors",
     ["Hormones travel only through axons as electrical impulses", "Every hormone affects every cell equally", "Endocrine glands release neurotransmitters exclusively into synaptic clefts"],
     "Endocrine glands release hormones into circulation. Target-cell receptors determine responsiveness. Synaptic communication usually involves neurotransmitter release across a small gap between cells, rather than hormone transport throughout the bloodstream."),
    ("Overview of the Nervous System and the Neuron",
     "After a frightening event ends, a person's heart rate slows and digestion resumes. Which division most directly supports this return toward rest?",
     "Parasympathetic nervous system", ["Sympathetic nervous system", "Somatic motor system alone", "Spinal skeletal-muscle reflexes alone"],
     "The parasympathetic branch of the autonomic nervous system supports rest-and-digest functions. The sympathetic branch typically mobilizes energy during a threat. The somatic system controls skeletal muscles rather than these autonomic functions."),
    ("The Visual System",
     "In dim light, a person can detect an object more easily by looking slightly to its side. Which retinal feature helps explain this?",
     "Rods outside the fovea are especially sensitive in low light",
     ["Cones in the fovea are the only receptors that work at night", "The blind spot contains the highest density of rods", "The lens detects light directly and replaces retinal activity"],
     "Rods support vision under low illumination and are absent from the central foveola. Looking slightly away can place an image on a rod-rich area. Cones provide high acuity and color vision under brighter conditions; the blind spot lacks photoreceptors."),
    ("Chemical Senses, Touch, Kinesthesis, and Vestibular Sense",
     "A dancer can sense the position of an arm with closed eyes. Which sense most directly provides this information?",
     "Kinesthesis", ["Olfaction", "Gustation", "Audition"],
     "Kinesthesis, or the sense of body position and movement, uses information from muscles, tendons, and joints. Vestibular information contributes to balance and head movement, while smell, taste, and hearing describe different sensory systems."),
    ("Sleep and Circadian Rhythms",
     "A traveler feels sleepy in the afternoon after crossing several time zones. Which explanation best accounts for this pattern?",
     "The internal circadian rhythm is temporarily misaligned with local time cues",
     ["The traveler has permanently lost the ability to enter REM sleep", "Sleep is controlled entirely by conscious choice", "Circadian rhythms reset instantly whenever a clock is changed"],
     "Circadian rhythms track an approximately daily cycle and are influenced by environmental cues such as light. Rapid travel can create a mismatch between internal timing and the local day. Adjustment is not necessarily immediate."),
    ("Statistical Analysis in Psychology",
     "A study reports r = −0.70 between hours of sleep lost and attention-test scores. What is the most justified interpretation?",
     "Greater sleep loss tends to be associated with lower attention scores",
     ["Sleep loss explains exactly 70% of all attention differences", "The correlation proves sleep loss is the only cause", "The negative sign means there is no relationship"],
     "The negative sign indicates an inverse association, and the magnitude suggests a fairly strong linear relationship. Correlation alone does not establish causation. The correlation coefficient is not itself a percentage of variance explained."),
    ("Principles of Perception",
     "Two people interpret an ambiguous sound differently after reading different contextual clues. Which process does this best illustrate?",
     "Top-down processing", ["Sensory adaptation alone", "A change in the physical sound wave", "Complete absence of bottom-up sensory information"],
     "Top-down processing uses expectations and context to interpret sensory input. Different interpretations can occur even when the incoming stimulus is the same. This does not mean the sensory signal or bottom-up processing is absent."),
    ("Introduction to Memory",
     "A person repeats a phone number mentally while looking for a place to write it down. Which process is most directly involved?",
     "Maintaining information in working memory through rehearsal",
     ["Storing the number permanently without further processing", "Using only an unconscious motor skill", "Erasing the number from sensory memory by intention"],
     "Working memory temporarily maintains and manipulates information. Rehearsal helps keep the number available, but does not guarantee permanent long-term storage. This task concerns consciously accessible information rather than a procedural skill."),
    ("Storing",
     "After a brain injury, a patient can still ride a bicycle but cannot remember a recent conversation. Which distinction does this pattern most directly illustrate?",
     "Procedural memory and episodic memory can depend on partly different systems",
     ["All memories are stored in one indivisible system", "Riding a bicycle requires only episodic recollection", "Forgetting one conversation proves all learned skills are lost"],
     "Procedural memory supports learned skills, while episodic memory concerns experienced events. Selective impairment shows that memory is not a single undifferentiated store. Preserved skill performance does not guarantee recall of recent events."),
    ("Forgetting and Memory Distortion",
     "After learning a new password, a student has trouble recalling an older password. Which concept best describes the newer information interfering with the older memory?",
     "Retroactive interference", ["Proactive interference", "Classical conditioning", "Sensory adaptation"],
     "Retroactive interference occurs when newer learning disrupts retrieval of older information. Proactive interference is the reverse: older learning makes newer information harder to remember. The direction of interference determines the label."),
    ("Evidence-Based Psychological Arguments",
     "Students are randomly assigned to spaced practice or one long study session. The spaced-practice group later recalls more words. Which claim stays closest to the evidence?",
     "Under the tested conditions, spacing practice improved average word recall in this sample",
     ["Spacing guarantees a perfect score for every student on every subject", "The study proves that individual differences never matter", "Random assignment makes replication unnecessary"],
     "Random assignment strengthens a causal interpretation of the manipulated study schedule. The claim should remain limited to the measured outcome and tested conditions; it does not guarantee individual success or eliminate the need to examine generalizability and replication."),
    ("Theories of Development",
     "A child believes a taller, narrower glass contains more water after the same water is poured from a shorter, wider glass. Which Piagetian concept is most directly relevant?",
     "A lack of conservation", ["Formal operational reasoning", "Object permanence being absent in all children", "A fully developed understanding of reversibility"],
     "Conservation is the understanding that quantity remains constant despite a change in appearance. Focusing on height while ignoring width illustrates the difficulty described in Piaget's account of preoperational thinking."),
    ("Influences on Development",
     "A researcher follows the same participants from age 10 to age 30. What is an advantage of this longitudinal design?",
     "It directly observes developmental changes within the same people",
     ["It eliminates participant dropout by definition", "It compares different age groups only once", "It guarantees that every observed change is caused by age alone"],
     "Longitudinal studies repeatedly observe the same participants, making within-person change visible. They can still face attrition and historical influences. A cross-sectional study instead compares different age groups at a single time."),
    ("Gender and Sexual Orientation",
     "Which statement correctly distinguishes gender identity from sexual orientation?",
     "Gender identity concerns one's sense of gender, while sexual orientation concerns patterns of attraction",
     ["The two terms always describe exactly the same characteristic", "Gender identity can be inferred with certainty from a person's hobbies", "Sexual orientation is defined only by a person's clothing"],
     "Gender identity and sexual orientation describe distinct aspects of a person. Interests, clothing, and other outward traits do not reliably establish either. Scientific description should avoid treating stereotypes as evidence about an individual."),
    ("Physical Development Across the Lifespan",
     "Which finding most clearly illustrates an interaction between maturation and experience in motor development?",
     "Infants typically need sufficient physical maturation, while opportunities for movement can influence skill development",
     ["Practice permits all newborns to walk independently immediately", "Environment can never affect motor development", "All children acquire every motor skill on the same exact day"],
     "Biological development creates capacities that interact with practice and environmental opportunity. Typical developmental patterns allow variation; neither maturation alone nor experience alone fixes every milestone to an exact date."),
    ("Communication and Language Development",
     "A child says 'goed' instead of 'went.' Which interpretation best explains this error?",
     "The child is overgeneralizing a grammatical rule",
     ["The child has never learned any grammatical pattern", "The child is correctly repeating the adult irregular form", "The child cannot distinguish any speech sounds"],
     "Overregularization applies a common rule, such as adding -ed for past tense, to an irregular word. The error can reveal productive learning of a rule rather than simple imitation or an absence of grammatical knowledge."),
    ("Theories of Motivation",
     "A student studies a favorite topic because learning it is enjoyable, even when no grade is offered. Which motivation is most evident?",
     "Intrinsic motivation", ["Motivation based only on external rewards", "A fixed-ratio reinforcement schedule", "An involuntary spinal reflex"],
     "Intrinsic motivation comes from interest or satisfaction in an activity itself. Extrinsic motivation depends on separable outcomes such as prizes or grades. Both can influence behavior, but no external reward is described here."),
    ("Specific Topics in Motivation",
     "After intense exercise without water, a person feels thirsty and seeks a drink. Which account best describes the role of homeostasis?",
     "A physiological imbalance produces a drive toward restoring a regulated condition",
     ["The body seeks an unlimited increase in every internal variable", "Thirst is unrelated to physiological regulation", "Drinking is always caused solely by a social reward"],
     "Homeostasis involves maintaining internal conditions within regulated ranges. Fluid loss can create signals that motivate drinking. This example fits drive reduction, although not every motivated behavior can be explained by reducing a physiological deficit."),
    ("Personality Assessment",
     "A personality questionnaire produces similar scores when administered twice under comparable conditions. What property does this observation most directly support?",
     "Test–retest reliability", ["Validity for every possible use", "Freedom from all response bias", "A causal explanation of personality"],
     "Test–retest reliability concerns consistency over time. A consistent instrument can still measure the wrong construct or reflect systematic response biases. Reliability supports measurement quality but is not identical to validity."),
    ("Group Influences on Behavior and Mental Processes",
     "During a group task, each member exerts less effort than when working alone because individual contributions are difficult to identify. Which phenomenon is most relevant?",
     "Social loafing", ["Social facilitation on a well-practiced task", "The mere-exposure effect", "Reciprocal determinism alone"],
     "Social loafing describes reduced individual effort when contributions are pooled and accountability is low. It differs from social facilitation, in which the presence of others can improve performance on familiar or easy tasks."),
    ("Interpersonal Attraction",
     "Two classmates become more comfortable with each other after repeated friendly encounters. Which principle may help explain the increase in liking?",
     "The mere-exposure effect", ["Retroactive interference", "Negative reinforcement by definition", "The absolute threshold"],
     "Repeated exposure to a familiar, nonaversive stimulus can increase liking. This is the mere-exposure effect. It is a tendency rather than a guarantee, and repeated unpleasant encounters need not produce attraction."),
    ("Stress and Coping",
     "A student reduces exam stress by making a study schedule and seeking help with difficult material. Which type of coping is most directly illustrated?",
     "Problem-focused coping", ["Avoiding every aspect of the stressor", "Changing only emotional interpretation without addressing the task", "An automatic sensory reflex"],
     "Problem-focused coping acts on a stressor or its practical demands. Planning and seeking instructional help address the exam preparation problem. Emotion-focused coping instead aims primarily to regulate the emotional response."),
    ("Introduction to Psychological Disorders",
     "Why is unusual behavior alone insufficient to classify a psychological disorder?",
     "Assessment also considers distress, dysfunction, context, and culturally informed criteria",
     ["Every statistically rare behavior is automatically a disorder", "Cultural context can never affect interpretation", "Disorders are defined solely by whether an observer dislikes a behavior"],
     "Rarity by itself does not establish a disorder. Psychological assessment considers impairment, distress, relevant criteria, and context. A person's difference from a majority or an observer's preference is not a sufficient basis for classification."),
    ("Anxiety Disorders, OCD, and PTSD",
     "In an educational case description, a person repeatedly checks a locked door to reduce distress from an intrusive fear. Which distinction best fits the description?",
     "The intrusive fear is an obsession and the repeated checking is a compulsion",
     ["The checking is an obsession and the intrusive fear is a compulsion", "Both terms refer only to hallucinations", "A single description establishes every criterion for a clinical diagnosis"],
     "Obsessions are intrusive, unwanted thoughts or urges; compulsions are repetitive behaviors or mental acts used to reduce distress or prevent a feared outcome. This distinction explains the terms without establishing a diagnosis from a brief vignette."),
    ("Health Psychology",
     "A study examines how sleep habits, social support, and beliefs about exercise relate to physical health. Which approach is most clearly represented?",
     "A biopsychosocial approach", ["An account that excludes behavior and social context", "A claim that biology never matters", "A theory based only on inherited eye color"],
     "The biopsychosocial approach considers biological, psychological, and social influences together. Health psychology examines how behavior and mental processes interact with physical health, without assuming that a single factor explains all outcomes."),
    ("Positive Psychology",
     "Which research question most directly fits positive psychology?",
     "How do supportive relationships and a sense of purpose relate to well-being?",
     ["How can researchers ignore all unpleasant experiences?", "How can happiness be guaranteed by one activity for everyone?", "Why should all evidence about distress be discarded?"],
     "Positive psychology studies strengths, flourishing, meaning, and well-being using empirical methods. It does not require denying distress or promising universal outcomes. Research should still examine the limits of any measured association or intervention."),
]
QUESTIONS = build_questions(UNITS, ITEMS)
