QUESTIONS = [
    # ---------- Unit 1: Scientific Foundations of Psychology ----------
    {
        "unit_name": "Scientific Foundations of Psychology",
        "topic_name": "Psychological Research Methods",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "A researcher finds that ice cream sales and drowning incidents both increase during the summer months. Which of the following best explains this relationship?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["research-methods"],
        "misconception_tags": ["confuses-correlation-with-causation"],
        "options": [
            {"label": "A", "text": "Eating ice cream causes people to drown.", "is_correct": False},
            {"label": "B", "text": "Drowning causes people to buy more ice cream.", "is_correct": False},
            {"label": "C", "text": "A third variable, warm weather, increases both ice cream sales and swimming, which raises drowning risk.", "is_correct": True},
            {"label": "D", "text": "The correlation proves that ice cream consumption is dangerous.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This assumes a causal link from a mere correlation; no experiment manipulated ice cream consumption.", "misconception_tag": "confuses-correlation-with-causation"},
            {"option_label": "B", "explanation": "This reverses cause and effect without any experimental evidence supporting it.", "misconception_tag": "confuses-correlation-with-causation"},
            {"option_label": "C", "explanation": "Correct. This is a classic example of a third (confounding) variable, warm weather, producing a spurious correlation.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correlation alone never proves causation or danger; it only shows the variables move together.", "misconception_tag": "confuses-correlation-with-causation"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Scientific Foundations of Psychology",
        "topic_name": "Psychological Research Methods",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In an experiment testing whether a new study app improves test scores, students are randomly assigned to use the app or not, and their exam scores are compared. What is the independent variable?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["research-methods"],
        "misconception_tags": ["mixes-up-independent-and-dependent-variable"],
        "options": [
            {"label": "A", "text": "Whether students used the study app or not.", "is_correct": True},
            {"label": "B", "text": "The students' exam scores.", "is_correct": False},
            {"label": "C", "text": "The random assignment procedure.", "is_correct": False},
            {"label": "D", "text": "The number of students in the study.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. The independent variable is the factor the researcher manipulates, here, app use versus no app use.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Exam scores are the outcome being measured, which makes this the dependent variable, not the independent variable.", "misconception_tag": "mixes-up-independent-and-dependent-variable"},
            {"option_label": "C", "explanation": "Random assignment is a control procedure used to reduce confounds, not a variable being tested.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Sample size affects statistical power but is not the manipulated variable in this design.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Scientific Foundations of Psychology",
        "topic_name": "Ethical Guidelines in Psychology",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "Before participating in a psychology experiment, participants are told the general purpose of the study and any foreseeable risks, and they agree to take part. This process is called",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["research-ethics"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "debriefing.", "is_correct": False},
            {"label": "B", "text": "informed consent.", "is_correct": True},
            {"label": "C", "text": "random sampling.", "is_correct": False},
            {"label": "D", "text": "operational definition.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Debriefing happens after the study, explaining its true nature and any deception used.", "misconception_tag": "confuses-debriefing-with-informed-consent"},
            {"option_label": "B", "explanation": "Correct. Informed consent is the process of informing participants of the study's purpose and risks before they agree to participate.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Random sampling refers to how participants are selected from a population, not to obtaining their agreement to participate.", "misconception_tag": None},
            {"option_label": "D", "explanation": "An operational definition specifies how a variable is measured or manipulated, unrelated to participant consent.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 2: Biological Bases of Behavior ----------
    {
        "unit_name": "Biological Bases of Behavior",
        "topic_name": "Neurotransmitters",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A drug that blocks the reuptake of serotonin at the synapse would most likely result in which immediate effect?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["neurotransmitters"],
        "misconception_tags": ["confuses-reuptake-with-agonist-binding"],
        "options": [
            {"label": "A", "text": "Decreased serotonin activity in the synapse.", "is_correct": False},
            {"label": "B", "text": "Increased serotonin activity in the synapse.", "is_correct": True},
            {"label": "C", "text": "Immediate destruction of serotonin by enzymes.", "is_correct": False},
            {"label": "D", "text": "Serotonin being converted into dopamine.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Blocking reuptake leaves more serotonin in the synapse, increasing rather than decreasing its activity.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Reuptake normally clears neurotransmitter from the synapse; blocking it leaves more serotonin available to bind receptors, increasing its effect.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Reuptake inhibitors block reabsorption; they do not trigger enzymatic breakdown, that is the role of enzymes like MAO in a separate process.", "misconception_tag": "confuses-reuptake-with-agonist-binding"},
            {"option_label": "D", "explanation": "Neurotransmitters are not converted into other neurotransmitters by reuptake blockers.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Biological Bases of Behavior",
        "topic_name": "The Brain",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Damage to Broca's area is most likely to result in difficulty with",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["brain-structures"],
        "misconception_tags": ["confuses-brocas-with-wernickes-area"],
        "options": [
            {"label": "A", "text": "producing fluent, grammatically correct speech.", "is_correct": True},
            {"label": "B", "text": "comprehending spoken language.", "is_correct": False},
            {"label": "C", "text": "maintaining balance and coordination.", "is_correct": False},
            {"label": "D", "text": "regulating hunger and body temperature.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Broca's area, in the frontal lobe, is critical for speech production; damage causes slow, labored, non-fluent speech.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Comprehension deficits are more associated with damage to Wernicke's area, not Broca's area.", "misconception_tag": "confuses-brocas-with-wernickes-area"},
            {"option_label": "C", "explanation": "Balance and coordination are primarily controlled by the cerebellum, not Broca's area.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Hunger and temperature regulation are functions of the hypothalamus, not Broca's area.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Biological Bases of Behavior",
        "topic_name": "Tools to Examine Brain Structure and Function",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A researcher wants to observe which brain areas become more active while a participant performs a language task, in real time. Which technique is best suited for this purpose?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["neuroimaging"],
        "misconception_tags": ["confuses-structural-with-functional-imaging"],
        "options": [
            {"label": "A", "text": "CT scan, because it provides detailed structural images.", "is_correct": False},
            {"label": "B", "text": "MRI, because it uses magnetic fields to image soft tissue.", "is_correct": False},
            {"label": "C", "text": "EEG, because it records structural changes in neurons.", "is_correct": False},
            {"label": "D", "text": "fMRI, because it detects changes in blood oxygen levels associated with neural activity.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "CT scans show brain structure using X-rays but do not capture ongoing functional activity.", "misconception_tag": "confuses-structural-with-functional-imaging"},
            {"option_label": "B", "explanation": "Standard MRI produces detailed structural images but does not track moment-to-moment functional activity.", "misconception_tag": "confuses-structural-with-functional-imaging"},
            {"option_label": "C", "explanation": "EEG measures electrical activity with excellent timing but poor spatial localization; it does not record structural changes.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct. fMRI tracks blood-oxygen-level changes to show which brain regions are active during a task, offering good spatial detail of function.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 3: Sensation and Perception ----------
    {
        "unit_name": "Sensation and Perception",
        "topic_name": "Principles of Sensation",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "After sitting in a room with a scented candle for twenty minutes, a person no longer notices the smell. This phenomenon is best explained by",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["sensory-thresholds"],
        "misconception_tags": ["confuses-sensory-adaptation-with-habituation"],
        "options": [
            {"label": "A", "text": "the absolute threshold rising above the candle's scent intensity.", "is_correct": False},
            {"label": "B", "text": "signal detection theory's response bias.", "is_correct": False},
            {"label": "C", "text": "sensory adaptation, where receptors respond less to an unchanging stimulus.", "is_correct": True},
            {"label": "D", "text": "the difference threshold being too large to detect the smell.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The absolute threshold is the minimum intensity needed to detect a stimulus at all; it is not what changes here since the candle was originally detected.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Response bias refers to a person's tendency to report detecting a stimulus regardless of sensory evidence, not physiological adaptation.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Sensory adaptation occurs when receptor cells become less responsive to a constant, unchanging stimulus over time.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The difference threshold concerns detecting differences between two stimuli, not the fading response to one constant stimulus.", "misconception_tag": "confuses-sensory-adaptation-with-habituation"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Sensation and Perception",
        "topic_name": "Visual Perception",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "When viewing a series of dots that appear to form a triangle even though the triangle's outline is not actually drawn, perceivers are demonstrating which Gestalt principle?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["gestalt-principles"],
        "misconception_tags": ["confuses-closure-with-proximity"],
        "options": [
            {"label": "A", "text": "Closure", "is_correct": True},
            {"label": "B", "text": "Proximity", "is_correct": False},
            {"label": "C", "text": "Similarity", "is_correct": False},
            {"label": "D", "text": "Figure-ground", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Closure describes the tendency to fill in gaps to perceive a complete, whole object, such as an implied triangle.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Proximity refers to grouping objects that are close together, not filling in missing contours.", "misconception_tag": "confuses-closure-with-proximity"},
            {"option_label": "C", "explanation": "Similarity refers to grouping objects that look alike, which is not the phenomenon described here.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Figure-ground refers to distinguishing an object from its background, not inferring missing contours.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Sensation and Perception",
        "topic_name": "The Auditory System",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Place theory best explains how we perceive which aspect of sound?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["auditory-system"],
        "misconception_tags": ["confuses-place-theory-with-frequency-theory"],
        "options": [
            {"label": "A", "text": "Loudness, based on the amplitude of the sound wave.", "is_correct": False},
            {"label": "B", "text": "High-pitched sounds, based on the specific location on the basilar membrane that is stimulated.", "is_correct": True},
            {"label": "C", "text": "Low-pitched sounds, based on the rate at which the entire basilar membrane vibrates.", "is_correct": False},
            {"label": "D", "text": "The location a sound is coming from in space.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Loudness is primarily determined by wave amplitude and the intensity of hair cell stimulation, not by place theory.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Place theory holds that different frequencies stimulate different locations on the basilar membrane, which works well for explaining high-pitched sounds.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Low-pitched sounds are better explained by frequency theory, where the whole membrane vibrates at the rate of the sound wave; this is the opposite pairing.", "misconception_tag": "confuses-place-theory-with-frequency-theory"},
            {"option_label": "D", "explanation": "Sound localization relies on timing and intensity differences between the two ears, not place theory.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 4: Learning ----------
    {
        "unit_name": "Learning",
        "topic_name": "Classical Conditioning",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "In Pavlov's original experiment, after a bell was repeatedly paired with food, dogs began salivating to the bell alone. In this scenario, the bell (once conditioning is complete) is the",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["classical-conditioning"],
        "misconception_tags": ["confuses-conditioned-and-unconditioned-stimulus"],
        "options": [
            {"label": "A", "text": "unconditioned stimulus.", "is_correct": False},
            {"label": "B", "text": "unconditioned response.", "is_correct": False},
            {"label": "C", "text": "conditioned stimulus.", "is_correct": True},
            {"label": "D", "text": "conditioned response.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The unconditioned stimulus is the food, which naturally triggers salivation without learning.", "misconception_tag": "confuses-conditioned-and-unconditioned-stimulus"},
            {"option_label": "B", "explanation": "The unconditioned response is the natural salivation to food, not the salivation to the bell.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. The bell becomes the conditioned stimulus because it acquires the ability to trigger salivation only after being paired with food.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The salivation to the bell is the conditioned response; the bell itself is the stimulus, not the response.", "misconception_tag": "mixes-up-conditioned-stimulus-and-response"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Learning",
        "topic_name": "Operant Conditioning",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A slot machine pays out an unpredictable number of times after an unpredictable number of pulls. Which schedule of reinforcement does this represent, and why does it produce such persistent behavior?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["operant-conditioning"],
        "misconception_tags": ["confuses-ratio-and-interval-schedules"],
        "options": [
            {"label": "A", "text": "Fixed-ratio schedule, because reinforcement is highly predictable and produces steady responding.", "is_correct": False},
            {"label": "B", "text": "Variable-ratio schedule, because unpredictable reinforcement based on number of responses produces high, steady rates resistant to extinction.", "is_correct": True},
            {"label": "C", "text": "Fixed-interval schedule, because reinforcement depends on a set amount of time passing.", "is_correct": False},
            {"label": "D", "text": "Variable-interval schedule, because reinforcement depends on an unpredictable amount of time passing.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "A fixed-ratio schedule provides reinforcement after a set, predictable number of responses, unlike a slot machine's unpredictable payout.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Slot machines reward based on an unpredictable number of responses (pulls), which is a variable-ratio schedule, known for producing high and very resistant response rates.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Interval schedules depend on time elapsed, not number of responses, which does not match a slot machine's pull-based payout.", "misconception_tag": "confuses-ratio-and-interval-schedules"},
            {"option_label": "D", "explanation": "This is an interval schedule, based on time, but the slot machine scenario is based on number of pulls (responses), not time elapsed.", "misconception_tag": "confuses-ratio-and-interval-schedules"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Learning",
        "topic_name": "Social and Cognitive Factors in Learning",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "A child watches an older sibling get praised for sharing toys, and the child begins sharing toys more often without ever being directly reinforced. This best illustrates",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["observational-learning"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "observational learning through vicarious reinforcement.", "is_correct": True},
            {"label": "B", "text": "classical conditioning through stimulus pairing.", "is_correct": False},
            {"label": "C", "text": "operant conditioning through direct positive reinforcement.", "is_correct": False},
            {"label": "D", "text": "extinction of a previously reinforced behavior.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. The child learns by observing the consequences experienced by someone else, which is vicarious reinforcement within observational learning.", "misconception_tag": None},
            {"option_label": "B", "explanation": "No neutral stimulus is being paired with an unconditioned stimulus here, so this is not classical conditioning.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The child was not directly reinforced; the sibling was, so this is not direct operant conditioning.", "misconception_tag": "confuses-vicarious-and-direct-reinforcement"},
            {"option_label": "D", "explanation": "Extinction involves a behavior decreasing after reinforcement stops, not a new behavior increasing.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 5: Cognitive Psychology ----------
    {
        "unit_name": "Cognitive Psychology",
        "topic_name": "Retrieving",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "After witnessing a car accident, a witness is later asked misleading questions about the event and subsequently recalls details that never actually occurred. This best illustrates",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["memory-retrieval"],
        "misconception_tags": ["confuses-misinformation-effect-with-source-amnesia"],
        "options": [
            {"label": "A", "text": "state-dependent memory.", "is_correct": False},
            {"label": "B", "text": "the serial position effect.", "is_correct": False},
            {"label": "C", "text": "source amnesia.", "is_correct": False},
            {"label": "D", "text": "the misinformation effect.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "State-dependent memory refers to recall being better when in the same physiological state as during encoding, unrelated to misleading questions.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The serial position effect describes better recall for items at the beginning and end of a list, not distortion from misleading information.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Source amnesia involves misattributing where a memory came from, which is a different error from having false details incorporated into memory.", "misconception_tag": "confuses-misinformation-effect-with-source-amnesia"},
            {"option_label": "D", "explanation": "Correct. The misinformation effect occurs when exposure to misleading information after an event distorts one's memory of that event.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cognitive Psychology",
        "topic_name": "Biases and Errors in Thinking",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "After hearing several vivid news stories about shark attacks, a person overestimates the likelihood of being attacked by a shark while swimming in the ocean. This best illustrates",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["cognitive-biases"],
        "misconception_tags": ["confuses-availability-heuristic-with-representativeness-heuristic"],
        "options": [
            {"label": "A", "text": "the availability heuristic.", "is_correct": True},
            {"label": "B", "text": "the representativeness heuristic.", "is_correct": False},
            {"label": "C", "text": "confirmation bias.", "is_correct": False},
            {"label": "D", "text": "belief perseverance.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. The availability heuristic leads people to judge the likelihood of an event based on how easily examples come to mind, such as vivid news stories.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The representativeness heuristic involves judging likelihood by how much something resembles a typical case or prototype, not by ease of recall.", "misconception_tag": "confuses-availability-heuristic-with-representativeness-heuristic"},
            {"option_label": "C", "explanation": "Confirmation bias involves favoring information that confirms existing beliefs, not overestimating risk due to memorable examples.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Belief perseverance is clinging to a belief even after it has been disproven, which does not describe this scenario.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Cognitive Psychology",
        "topic_name": "Psychometric Principles",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "A newly developed intelligence test gives wildly different scores for the same person when retaken two weeks later under identical conditions, but the test author claims it accurately measures intelligence. What is the most significant problem with this test?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["test-validity-reliability"],
        "misconception_tags": ["confuses-validity-with-reliability"],
        "options": [
            {"label": "A", "text": "The test lacks content validity because it does not sample a broad range of items.", "is_correct": False},
            {"label": "B", "text": "The test lacks standardization because it was not normed on a representative sample.", "is_correct": False},
            {"label": "C", "text": "The test lacks reliability, and a test cannot be valid if it does not produce consistent results.", "is_correct": True},
            {"label": "D", "text": "The test lacks predictive validity because it does not forecast future academic performance.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Content validity concerns whether test items adequately sample the construct, but the problem described is inconsistency across retesting, not item content.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Standardization concerns uniform administration and scoring norms, which is not the issue highlighted, inconsistent scores upon retesting.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. Producing very different scores on retest under the same conditions indicates poor test-retest reliability, and reliability is a prerequisite for validity.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Predictive validity concerns whether scores forecast future outcomes, which is not addressed by the retest inconsistency described here.", "misconception_tag": "confuses-validity-with-reliability"},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 6: Developmental Psychology ----------
    {
        "unit_name": "Developmental Psychology",
        "topic_name": "Social Development",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "In Ainsworth's Strange Situation, an infant becomes very distressed when the caregiver leaves but is not comforted upon return, sometimes even resisting contact. This pattern best describes",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["attachment-theory"],
        "misconception_tags": ["confuses-avoidant-and-anxious-resistant-attachment"],
        "options": [
            {"label": "A", "text": "secure attachment.", "is_correct": False},
            {"label": "B", "text": "insecure anxious-resistant (ambivalent) attachment.", "is_correct": True},
            {"label": "C", "text": "insecure avoidant attachment.", "is_correct": False},
            {"label": "D", "text": "disorganized attachment only.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Securely attached infants are distressed at separation but are easily comforted and seek contact upon reunion, unlike this scenario.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Correct. Anxious-resistant attachment is marked by intense distress at separation combined with resistance to comfort upon reunion.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Avoidant infants typically show little distress at separation and avoid or ignore the caregiver upon return, which does not match the intense distress described here.", "misconception_tag": "confuses-avoidant-and-anxious-resistant-attachment"},
            {"option_label": "D", "explanation": "While related, this description specifically matches the classic anxious-resistant pattern rather than the inconsistent, fearful behaviors that define disorganized attachment.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Developmental Psychology",
        "topic_name": "Moral Development",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A teenager decides not to cheat on a test, reasoning that if everyone cheated, the whole system of grades would become meaningless and unfair to society. According to Kohlberg, this reasoning best reflects which level of moral development?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["kohlberg-moral-development"],
        "misconception_tags": ["confuses-conventional-and-postconventional-morality"],
        "options": [
            {"label": "A", "text": "Preconventional morality, focused on avoiding punishment.", "is_correct": False},
            {"label": "B", "text": "Preconventional morality, focused on self-interest and rewards.", "is_correct": False},
            {"label": "C", "text": "Conventional morality, focused on maintaining social order and rules.", "is_correct": True},
            {"label": "D", "text": "Postconventional morality, focused on self-chosen ethical principles that may override laws.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reasoning is not centered on personal punishment but on the broader social consequence of everyone cheating.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The reasoning is not about what the teenager personally gains, but about maintaining fairness within the social system.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Correct. This reflects conventional morality, where moral reasoning is based on maintaining social order and the rules that keep systems functioning fairly.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Postconventional reasoning involves abstract, self-defined ethical principles, sometimes conflicting with laws or social rules, which is not demonstrated here since the reasoning appeals to preserving the existing system.", "misconception_tag": "confuses-conventional-and-postconventional-morality"},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 7: Motivation, Emotion, and Personality ----------
    {
        "unit_name": "Motivation, Emotion, and Personality",
        "topic_name": "Theories of Emotion",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "According to the Cannon-Bard theory of emotion, when a person encounters a threatening bear, which sequence of events occurs?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["emotion-theories"],
        "misconception_tags": ["confuses-james-lange-and-cannon-bard-theories"],
        "options": [
            {"label": "A", "text": "The person first experiences physiological arousal, then interprets that arousal to feel fear.", "is_correct": False},
            {"label": "B", "text": "The person simultaneously experiences physiological arousal and the subjective feeling of fear.", "is_correct": True},
            {"label": "C", "text": "The person first cognitively appraises the bear as dangerous, then experiences arousal, which produces the emotion.", "is_correct": False},
            {"label": "D", "text": "The person feels fear only after consciously deciding to run away.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This sequence, arousal first and then interpretation producing the emotion, describes the James-Lange theory, not Cannon-Bard.", "misconception_tag": "confuses-james-lange-and-cannon-bard-theories"},
            {"option_label": "B", "explanation": "Correct. Cannon-Bard theory proposes that the physiological response and the subjective emotional experience occur simultaneously and independently.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This sequential appraisal-then-arousal-then-emotion model is closer to the Schachter-Singer two-factor theory's cognitive labeling process, not Cannon-Bard.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Cannon-Bard does not require a conscious behavioral decision before the emotion is felt; arousal and emotion occur together.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Motivation, Emotion, and Personality",
        "topic_name": "Introduction to Personality",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A trait theorist would most likely explain a person's consistent shyness across many different situations by pointing to",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["personality-theories"],
        "misconception_tags": ["confuses-trait-and-psychodynamic-perspectives"],
        "options": [
            {"label": "A", "text": "a stable, enduring characteristic of the person, such as low extraversion.", "is_correct": True},
            {"label": "B", "text": "unconscious conflicts stemming from early childhood experiences.", "is_correct": False},
            {"label": "C", "text": "a lack of unconditional positive regard from caregivers.", "is_correct": False},
            {"label": "D", "text": "reinforcement history that has shaped shy behavior through operant conditioning.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Trait theorists explain consistent behavior patterns across situations as reflecting stable personality traits, such as low extraversion.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Explaining behavior via unconscious childhood conflicts is characteristic of the psychodynamic perspective, not the trait perspective.", "misconception_tag": "confuses-trait-and-psychodynamic-perspectives"},
            {"option_label": "C", "explanation": "Unconditional positive regard is a concept from the humanistic perspective (Rogers), not the trait perspective.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Explaining shyness through reinforcement history reflects the social-cognitive/behaviorist perspective, not the trait perspective.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 8: Clinical Psychology ----------
    {
        "unit_name": "Clinical Psychology",
        "topic_name": "Depressive and Bipolar Disorders",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "A person experiences an unusually elevated, expansive mood, inflated self-esteem, and a decreased need for sleep for a full week, followed weeks later by a period of deep depression. This pattern is most consistent with",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["mood-disorders"],
        "misconception_tags": ["confuses-major-depressive-disorder-with-bipolar-disorder"],
        "options": [
            {"label": "A", "text": "major depressive disorder.", "is_correct": False},
            {"label": "B", "text": "generalized anxiety disorder.", "is_correct": False},
            {"label": "C", "text": "persistent depressive disorder (dysthymia).", "is_correct": False},
            {"label": "D", "text": "bipolar disorder.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Major depressive disorder involves depressive episodes only, without the manic episode of elevated mood and grandiosity described here.", "misconception_tag": "confuses-major-depressive-disorder-with-bipolar-disorder"},
            {"option_label": "B", "explanation": "Generalized anxiety disorder is characterized by chronic excessive worry, not alternating manic and depressive episodes.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Persistent depressive disorder involves a chronic, milder depressed mood over at least two years, not manic episodes.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Correct. The alternation between a manic episode (elevated mood, grandiosity, reduced sleep) and a depressive episode is the hallmark of bipolar disorder.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Clinical Psychology",
        "topic_name": "Schizophrenia",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Which of the following is classified as a negative symptom of schizophrenia?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["schizophrenia"],
        "misconception_tags": ["confuses-positive-and-negative-symptoms"],
        "options": [
            {"label": "A", "text": "Hallucinations, such as hearing voices that are not present.", "is_correct": False},
            {"label": "B", "text": "Delusions of persecution.", "is_correct": False},
            {"label": "C", "text": "Flat affect and social withdrawal.", "is_correct": True},
            {"label": "D", "text": "Disorganized speech patterns.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Hallucinations are an excess or distortion of normal function, which makes them a positive symptom, not a negative one.", "misconception_tag": "confuses-positive-and-negative-symptoms"},
            {"option_label": "B", "explanation": "Delusions are also an excess of normal thought processes, classifying them as a positive symptom.", "misconception_tag": "confuses-positive-and-negative-symptoms"},
            {"option_label": "C", "explanation": "Correct. Negative symptoms involve a decrease or absence of normal functioning, such as flat affect (reduced emotional expression) and social withdrawal.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Disorganized speech is considered a positive symptom because it represents an aberration added to normal speech function.", "misconception_tag": "confuses-positive-and-negative-symptoms"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Clinical Psychology",
        "topic_name": "Treatment of Disorders",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "A therapist helps a client with a phobia of elevators gradually confront elevators, starting with looking at pictures of elevators and eventually riding one, while practicing relaxation techniques at each step. This treatment technique is called",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["psychotherapy"],
        "misconception_tags": ["confuses-systematic-desensitization-with-flooding"],
        "options": [
            {"label": "A", "text": "systematic desensitization.", "is_correct": True},
            {"label": "B", "text": "flooding.", "is_correct": False},
            {"label": "C", "text": "psychoanalysis.", "is_correct": False},
            {"label": "D", "text": "aversive conditioning.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Systematic desensitization pairs relaxation with a gradual, step-by-step hierarchy of exposure to the feared stimulus.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Flooding involves immediate, intense exposure to the feared stimulus all at once, not a gradual hierarchy, so this describes the opposite technique.", "misconception_tag": "confuses-systematic-desensitization-with-flooding"},
            {"option_label": "C", "explanation": "Psychoanalysis focuses on uncovering unconscious conflicts through techniques like free association, not gradual exposure.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Aversive conditioning pairs an unwanted behavior with an unpleasant stimulus to reduce that behavior, which is unrelated to treating phobias through exposure.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- Unit 9: Social Psychology ----------
    {
        "unit_name": "Social Psychology",
        "topic_name": "Attribution Theory and Person Perception",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "After a classmate snaps angrily at a friend, an observer assumes the classmate must just be a rude person, without considering that the classmate may be having an extremely stressful day. This best illustrates",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["attribution-theory"],
        "misconception_tags": ["confuses-fundamental-attribution-error-with-self-serving-bias"],
        "options": [
            {"label": "A", "text": "the self-serving bias.", "is_correct": False},
            {"label": "B", "text": "the fundamental attribution error.", "is_correct": True},
            {"label": "C", "text": "the just-world hypothesis.", "is_correct": False},
            {"label": "D", "text": "the actor-observer bias applied to one's own behavior.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Self-serving bias involves attributing one's own successes to internal factors and failures to external factors, not judging another person's behavior.", "misconception_tag": "confuses-fundamental-attribution-error-with-self-serving-bias"},
            {"option_label": "B", "explanation": "Correct. The fundamental attribution error is the tendency to overemphasize personal disposition (rudeness) and underemphasize situational factors (stress) when explaining others' behavior.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The just-world hypothesis is the belief that people generally get what they deserve, which is not what is being illustrated here.", "misconception_tag": None},
            {"option_label": "D", "explanation": "This scenario describes judging someone else's behavior, not the actor's own explanation for their behavior, so it is not about the actor's perspective.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Social Psychology",
        "topic_name": "Conformity, Compliance, and Obedience",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "In Asch's line-judgment studies, participants often gave an obviously incorrect answer that matched the unanimous incorrect answers given by confederates. This best demonstrates",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["conformity-obedience"],
        "misconception_tags": ["confuses-conformity-with-obedience"],
        "options": [
            {"label": "A", "text": "conformity to group norms.", "is_correct": True},
            {"label": "B", "text": "obedience to a legitimate authority figure.", "is_correct": False},
            {"label": "C", "text": "the bystander effect.", "is_correct": False},
            {"label": "D", "text": "social loafing.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct. Asch's study specifically demonstrates conformity, changing behavior or beliefs to match a group, even peers with no authority over the participant.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Obedience involves following the direct commands of an authority figure, as in Milgram's studies, not matching the judgments of equal-status peers.", "misconception_tag": "confuses-conformity-with-obedience"},
            {"option_label": "C", "explanation": "The bystander effect concerns the reduced likelihood of helping when other people are present, unrelated to matching group answers.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Social loafing refers to individuals exerting less effort in a group task, not conforming to a group's stated judgment.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Social Psychology",
        "topic_name": "Prosocial Behavior, Aggression, Altruism",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "A person collapses on a crowded subway platform. Research on the bystander effect suggests that the likelihood any single bystander will help is",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["prosocial-behavior"],
        "misconception_tags": ["believes-more-bystanders-increases-helping"],
        "options": [
            {"label": "A", "text": "higher than if only one bystander were present, because more people can share the responsibility of helping.", "is_correct": False},
            {"label": "B", "text": "lower than if only one bystander were present, due to diffusion of responsibility.", "is_correct": True},
            {"label": "C", "text": "unaffected by the number of bystanders present.", "is_correct": False},
            {"label": "D", "text": "entirely determined by the bystander's personality traits, regardless of situational factors.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is the opposite of the actual finding; more bystanders leads each individual to feel less personal responsibility to act.", "misconception_tag": "believes-more-bystanders-increases-helping"},
            {"option_label": "B", "explanation": "Correct. The bystander effect shows that as the number of onlookers increases, each individual feels less personally responsible, reducing the likelihood any one person will help, known as diffusion of responsibility.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The number of bystanders present has been shown experimentally to significantly affect helping behavior, so this option ignores a well-established situational effect.", "misconception_tag": None},
            {"option_label": "D", "explanation": "While personality plays some role, research emphasizes that situational factors, like the number of other bystanders, strongly influence helping behavior.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # ---------- FRQ questions (spread across units) ----------
    {
        "unit_name": "Scientific Foundations of Psychology",
        "topic_name": "Psychological Research Methods",
        "type": "frq",
        "difficulty": 3,
        "prompt": "A researcher wants to test whether listening to classical music improves memory for word lists in college students. Design a simple experiment to test this hypothesis, identifying the independent variable, the dependent variable, how participants would be assigned to conditions, and one confound the researcher should control for.",
        "correct_answer": "A strong response identifies listening to classical music (vs. silence or another condition) as the IV, memory performance (e.g., words recalled) as the DV, describes random assignment to conditions, and names a plausible confound (e.g., prior musical training, time of day, baseline memory ability) with a control method.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["research-methods"],
        "misconception_tags": ["mixes-up-independent-and-dependent-variable"],
        "explanations": [
            {"option_label": None, "explanation": "A complete response clearly labels the independent variable (the manipulated condition, music vs. no music) and dependent variable (the measured outcome, memory score), describes random assignment to reduce pre-existing group differences, and identifies a specific confound with a concrete way to control it (e.g., holding testing conditions constant, screening for musical background).", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Correctly identifies the independent variable (music condition) and dependent variable (memory performance)", "keywords": ["independent variable", "dependent variable", "classical music", "memory", "word recall"], "points": 1},
                {"point": "Describes an appropriate experimental design including random assignment to conditions", "keywords": ["random assignment", "control group", "experimental group"], "points": 1},
                {"point": "Identifies a plausible confounding variable relevant to the scenario", "keywords": ["confound", "prior musical training", "time of day", "baseline memory"], "points": 1},
                {"point": "Explains a specific method to control for the identified confound", "keywords": ["control", "hold constant", "randomize", "screen participants"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Learning",
        "topic_name": "Operant Conditioning",
        "type": "frq",
        "difficulty": 2,
        "prompt": "A parent wants to reduce a young child's tantrums in a grocery store while increasing the child's habit of helping put items in the cart. Using principles of operant conditioning, explain one strategy involving punishment to reduce the tantrums and one strategy involving reinforcement to increase the helping behavior.",
        "correct_answer": "A strong response describes a specific punishment technique (e.g., time-out as negative punishment, removing a privilege) to reduce tantrums, and a specific reinforcement technique (e.g., praise or a small reward as positive reinforcement) to increase helping behavior, correctly applying operant conditioning terminology.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["operant-conditioning"],
        "misconception_tags": ["confuses-punishment-with-negative-reinforcement"],
        "explanations": [
            {"option_label": None, "explanation": "The correct approach names a specific punishment (something added or removed to decrease tantrum behavior, e.g., taking away a toy) and clearly distinguishes it from reinforcement, then names a specific reinforcer (something added to increase helping behavior, e.g., verbal praise) applied consistently and immediately after the desired behavior.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific and appropriate punishment strategy to decrease tantrums", "keywords": ["time-out", "removing privilege", "negative punishment", "positive punishment"], "points": 1},
                {"point": "Correctly explains why the strategy counts as punishment (decreases behavior)", "keywords": ["decrease", "punishment", "consequence"], "points": 1},
                {"point": "Identifies a specific and appropriate reinforcement strategy to increase helping behavior", "keywords": ["praise", "reward", "positive reinforcement", "sticker"], "points": 1},
                {"point": "Correctly explains why the strategy counts as reinforcement (increases behavior)", "keywords": ["increase", "reinforcement", "strengthen"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Cognitive Psychology",
        "topic_name": "Encoding",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Explain how using the method of loci (a mnemonic device) helps a student encode a list of items into long-term memory more effectively than simple rote repetition, referencing at least one specific memory principle.",
        "correct_answer": "A strong response explains that the method of loci uses visual imagery and organization (linking items to familiar locations), producing deeper, more elaborative encoding than shallow rote repetition, referencing a principle such as levels of processing or elaborative rehearsal.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["encoding"],
        "misconception_tags": ["confuses-maintenance-and-elaborative-rehearsal"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response explains that the method of loci creates vivid, meaningful associations between items and familiar spatial locations, which is a form of elaborative rehearsal or deep processing, and contrasts this with rote/maintenance rehearsal, which only involves shallow repetition and produces weaker long-term retention.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Accurately describes how the method of loci works (associating items with familiar locations/imagery)", "keywords": ["method of loci", "visual imagery", "familiar locations", "association"], "points": 1},
                {"point": "Identifies the relevant memory principle (e.g., levels of processing, elaborative rehearsal)", "keywords": ["levels of processing", "elaborative rehearsal", "deep processing"], "points": 1},
                {"point": "Explains why this produces better encoding than rote repetition", "keywords": ["rote repetition", "maintenance rehearsal", "shallow processing", "long-term memory"], "points": 2},
            ]
        },
    },
    {
        "unit_name": "Clinical Psychology",
        "topic_name": "Psychological Perspectives and Etiology of Disorders",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Using the biopsychosocial model, explain how biological, psychological, and social factors might each contribute to the development of major depressive disorder in a teenager, giving one specific example for each factor.",
        "correct_answer": "A strong response gives one biological factor (e.g., genetic predisposition, neurotransmitter imbalance such as low serotonin), one psychological factor (e.g., negative thinking patterns, learned helplessness), and one social factor (e.g., chronic peer bullying, family conflict), each specifically tied to the teenager's depression.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["disorder-etiology"],
        "misconception_tags": ["treats-mental-disorders-as-having-a-single-cause"],
        "explanations": [
            {"option_label": None, "explanation": "A complete answer treats depression as multiply determined, providing a distinct, concrete biological example (e.g., low serotonin activity or family history of depression), a distinct psychological example (e.g., a pessimistic explanatory style or learned helplessness), and a distinct social example (e.g., bullying, social isolation, or family stress), rather than attributing the disorder to any single cause.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Gives a specific, accurate biological factor contributing to depression", "keywords": ["serotonin", "genetics", "neurotransmitter", "family history"], "points": 1},
                {"point": "Gives a specific, accurate psychological factor contributing to depression", "keywords": ["negative thinking", "learned helplessness", "pessimistic", "rumination"], "points": 1},
                {"point": "Gives a specific, accurate social factor contributing to depression", "keywords": ["bullying", "family conflict", "isolation", "peer relationships"], "points": 1},
                {"point": "Frames the explanation using the biopsychosocial model as an integrated, multi-causal approach", "keywords": ["biopsychosocial", "multiple factors", "interact"], "points": 1},
            ]
        },
    },
    {
        "unit_name": "Social Psychology",
        "topic_name": "Attitude Formation and Attitude Change",
        "type": "frq",
        "difficulty": 3,
        "prompt": "A student who strongly believes exercise is a waste of time is required to write and present a persuasive speech arguing that exercise is essential for health. Afterward, the student's attitude toward exercise becomes more positive. Explain this attitude change using cognitive dissonance theory.",
        "correct_answer": "A strong response explains that arguing against one's own prior belief with insufficient external justification creates cognitive dissonance (an uncomfortable inconsistency between belief and behavior), which the student resolves by shifting their attitude to align with the behavior they performed.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["cognitive-dissonance"],
        "misconception_tags": ["confuses-cognitive-dissonance-with-self-serving-bias"],
        "explanations": [
            {"option_label": None, "explanation": "A full-credit response identifies the inconsistency between the student's original belief and their public behavior (arguing for exercise) as the source of cognitive dissonance, notes that this creates psychological discomfort, and explains that since the behavior cannot be undone and was not strongly externally justified, the student reduces the dissonance by changing their attitude to match their behavior.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Correctly defines cognitive dissonance as discomfort from inconsistent beliefs and behaviors", "keywords": ["cognitive dissonance", "inconsistency", "discomfort"], "points": 1},
                {"point": "Applies the theory specifically to the student's situation (belief vs. speech behavior)", "keywords": ["belief", "speech", "behavior", "exercise"], "points": 1},
                {"point": "Explains that attitude change occurs to reduce/resolve the dissonance", "keywords": ["reduce dissonance", "attitude change", "align"], "points": 1},
            ]
        },
    },
]
