QUESTIONS = [
    # Period 1: 1491-1607
    {
        "unit_name": "Period 1: 1491-1607",
        "topic_name": "Native American Societies Before European Contact",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which of the following best describes a key difference between Native American societies of the Great Plains and those of the Pacific Northwest before European contact?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["comparison"],
        "misconception_tags": ["assumes-uniform-native-culture"],
        "options": [
            {"label": "A", "text": "Great Plains societies relied primarily on fishing, while Pacific Northwest societies relied primarily on bison hunting.", "is_correct": False},
            {"label": "B", "text": "Pacific Northwest societies developed permanent settlements based on abundant fish resources, while many Great Plains societies were seasonally mobile and depended on bison.", "is_correct": True},
            {"label": "C", "text": "Both regions developed identical agricultural systems based on maize cultivation.", "is_correct": False},
            {"label": "D", "text": "Neither region developed complex trade networks before European contact.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reverses the actual resource bases of the two regions.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "B", "explanation": "Correct: abundant salmon runs supported permanent Pacific Northwest villages, while bison migration patterns encouraged mobility on the Plains.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This incorrectly assumes all Native societies shared one economic base; Pacific Northwest peoples relied on fishing, not maize.", "misconception_tag": "assumes-uniform-native-culture"},
            {"option_label": "D", "explanation": "Extensive pre-contact trade networks existed across North America, contradicting this option.", "misconception_tag": "overstates-isolation"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 1: 1491-1607",
        "topic_name": "Columbian Exchange",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "The Columbian Exchange most directly contributed to which of the following outcomes in the Americas during the sixteenth century?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["overstates-single-cause"],
        "options": [
            {"label": "A", "text": "Catastrophic population decline among Native Americans due to the introduction of Old World diseases.", "is_correct": True},
            {"label": "B", "text": "An immediate rise in Native American population due to new agricultural techniques introduced by Europeans.", "is_correct": False},
            {"label": "C", "text": "The elimination of European interest in colonizing the Americas.", "is_correct": False},
            {"label": "D", "text": "The introduction of horses to Europe from the Americas.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: Native populations lacked immunity to diseases like smallpox, leading to devastating losses, often over 90% in some regions.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This inverts the actual demographic outcome, which was decline, not growth.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "European colonization intensified rather than ended after the Columbian Exchange began.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "Horses moved from the Old World to the Americas, not the reverse.", "misconception_tag": "reverses-direction-of-exchange"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 1: 1491-1607",
        "topic_name": "Labor, Slavery, and Caste in the Spanish Colonial System",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "The encomienda system established by Spanish colonizers in the Americas is best understood as a system that",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": ["conflates-two-different-systems"],
        "options": [
            {"label": "A", "text": "granted Native Americans full Spanish citizenship in exchange for military service.", "is_correct": False},
            {"label": "B", "text": "was identical to the chattel slavery later practiced in British North America.", "is_correct": False},
            {"label": "C", "text": "granted Spanish colonizers the right to demand labor and tribute from Native Americans in exchange for supposed protection and religious instruction.", "is_correct": True},
            {"label": "D", "text": "was abolished immediately after the first voyages of Columbus due to Spanish crown objections.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The encomienda did not grant citizenship; it imposed labor and tribute obligations on Native Americans.", "misconception_tag": "assumes-equal-legal-status"},
            {"option_label": "B", "explanation": "This conflates encomienda with chattel slavery; encomienda was nominally about labor/tribute obligations tied to land grants, not the same legal property status as chattel slavery.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "C", "explanation": "Correct: encomenderos received the right to Indigenous labor and tribute in exchange for claimed protection and Christianization.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The encomienda system persisted for decades and was only gradually curtailed, not abolished immediately.", "misconception_tag": "overstates-early-reform"},
        ],
        "rubric_json": None,
    },

    # Period 2: 1607-1754
    {
        "unit_name": "Period 2: 1607-1754",
        "topic_name": "The English Colonies: Regional Development",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Which factor best explains why the New England colonies developed a more diversified economy than the Southern colonies during the seventeenth century?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["ignores-geographic-factors"],
        "options": [
            {"label": "A", "text": "New England colonists were legally prohibited from growing cash crops.", "is_correct": False},
            {"label": "B", "text": "New England received far more direct financial investment from the English crown than the Southern colonies.", "is_correct": False},
            {"label": "C", "text": "Southern colonists lacked access to any port cities for trade.", "is_correct": False},
            {"label": "D", "text": "New England's rocky soil and shorter growing season discouraged large-scale cash-crop agriculture, encouraging shipbuilding, fishing, and trade instead.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "There was no such legal prohibition; the limitation was environmental, not legal.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "B", "explanation": "There is no historical basis for greater crown investment in New England relative to the South.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "C", "explanation": "Southern colonies had significant port access, such as Charleston, which contradicts this claim.", "misconception_tag": "ignores-geographic-factors"},
            {"option_label": "D", "explanation": "Correct: New England's geography and climate pushed its economy toward maritime trade, fishing, and small-scale farming rather than plantation agriculture.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 2: 1607-1754",
        "topic_name": "Transatlantic Trade and the Expansion of Slavery",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "The shift from indentured servitude to chattel slavery as the primary labor source in the Chesapeake colonies during the late seventeenth century was most directly caused by",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["conflates-two-different-time-periods"],
        "options": [
            {"label": "A", "text": "planter elites' desire for a more permanent, controllable labor force after events like Bacon's Rebellion exposed the dangers of a large class of free, landless former servants.", "is_correct": True},
            {"label": "B", "text": "a sudden decline in the profitability of tobacco cultivation that made servant labor too expensive.", "is_correct": False},
            {"label": "C", "text": "the abolition of indentured servitude by royal decree in 1680.", "is_correct": False},
            {"label": "D", "text": "the immediate outcome of the first arrival of Africans in Virginia in 1619.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: Bacon's Rebellion (1676) highlighted risks posed by discontented former servants, accelerating planters' shift toward enslaved African labor for social control and permanence.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Tobacco remained profitable; the shift in labor source was about control and labor supply, not declining profitability.", "misconception_tag": "misidentifies-economic-motive"},
            {"option_label": "C", "explanation": "No such royal decree existed; indentured servitude continued to exist alongside slavery.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "This conflates 1619 with the later, gradual hardening of racial slavery decades afterward; the shift to a slave-based labor system was not immediate.", "misconception_tag": "conflates-two-different-time-periods"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 2: 1607-1754",
        "topic_name": "Interactions Between American Indians and Europeans",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Briefly explain ONE specific example of conflict between Native Americans and European colonists in the seventeenth century, and briefly explain ONE cause of that conflict.",
        "correct_answer": "A strong response identifies a specific conflict (e.g., King Philip's War, the Pequot War) and explains a specific cause such as competition over land, colonial expansion, or breakdown of trade/diplomatic relationships.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation", "evidence"],
        "misconception_tags": ["assumes-uniform-native-culture"],
        "explanations": [
            {"option_label": None, "explanation": "A strong response names a specific conflict such as the Pequot War (1636-1638) or King Philip's War (1675-1678) and ties it to a specific cause, for example, competition over land as colonial populations expanded, or the collapse of earlier cooperative trade relationships. Responses that treat 'Native Americans' as a single undifferentiated group fighting one uniform war against 'colonists' miss the specificity required.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific historical conflict between Native Americans and colonists", "keywords": ["King Philip's War", "Metacom", "Pequot War", "Powhatan"], "points": 1},
                {"point": "Explains a specific, accurate cause of that conflict", "keywords": ["land", "expansion", "trade", "encroachment"], "points": 2},
                {"point": "Avoids treating Native peoples as a single undifferentiated group", "keywords": [], "points": 1},
            ]
        },
    },

    # Period 3: 1754-1800
    {
        "unit_name": "Period 3: 1754-1800",
        "topic_name": "Taxation Without Representation and the Road to Revolution",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Colonial opposition to the Stamp Act (1765) was primarily grounded in the argument that",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["argumentation"],
        "misconception_tags": ["overstates-single-cause"],
        "options": [
            {"label": "A", "text": "the tax rate itself was far higher than any tax colonists had previously paid.", "is_correct": False},
            {"label": "B", "text": "Parliament lacked the constitutional authority to levy direct internal taxes on colonists who had no elected representation in Parliament.", "is_correct": True},
            {"label": "C", "text": "the revenue from the tax was to be used exclusively to fund the Church of England in the colonies.", "is_correct": False},
            {"label": "D", "text": "the Stamp Act applied only to colonies south of Virginia.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The core objection was constitutional/representational, not merely about the tax rate being high.", "misconception_tag": "misidentifies-economic-motive"},
            {"option_label": "B", "explanation": "Correct: colonists argued 'no taxation without representation,' asserting Parliament could not tax them directly absent colonial representation.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Stamp Act revenue was intended for general defense costs, not religious funding.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "The Stamp Act applied to all thirteen colonies, not a regional subset.", "misconception_tag": "overgeneralizes-regional-scope"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 3: 1754-1800",
        "topic_name": "The American Revolution's Effects",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "Which of the following best describes an effect of the American Revolution on enslaved people in the United States?",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["continuity-and-change"],
        "misconception_tags": ["overgeneralizes-regional-scope"],
        "options": [
            {"label": "A", "text": "Slavery was immediately abolished in all thirteen states following independence.", "is_correct": False},
            {"label": "B", "text": "The Revolution had no effect whatsoever on the institution of slavery anywhere in the new nation.", "is_correct": False},
            {"label": "C", "text": "Northern states began gradual emancipation processes, while slavery expanded and became further entrenched in the South.", "is_correct": True},
            {"label": "D", "text": "The Revolution led to the immediate enfranchisement of all formerly enslaved men in the North and South.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Abolition was not immediate or universal; it was gradual and regionally uneven.", "misconception_tag": "overgeneralizes-regional-scope"},
            {"option_label": "B", "explanation": "Revolutionary ideology did influence the gradual emancipation movement in the North, so this overstates the lack of impact.", "misconception_tag": "overstates-uniformity"},
            {"option_label": "C", "explanation": "Correct: states like Pennsylvania and Massachusetts began gradual emancipation, while Southern states saw slavery expand alongside growing cotton agriculture.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Free Black men often faced significant restrictions on voting rights even after emancipation in Northern states.", "misconception_tag": "assumes-equal-legal-status"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 3: 1754-1800",
        "topic_name": "The Articles of Confederation and the Constitution",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Briefly explain ONE specific weakness of the Articles of Confederation, and briefly explain how the Constitution of 1787 addressed that weakness.",
        "correct_answer": "A strong response identifies a specific weakness (e.g., inability to tax, no strong executive, unanimous consent for amendments) and explains a specific constitutional fix (e.g., federal taxing power, creation of the presidency, easier amendment process).",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["comparison", "evidence"],
        "misconception_tags": ["conflates-two-different-systems"],
        "explanations": [
            {"option_label": None, "explanation": "A strong response might note that the Articles gave Congress no power to levy taxes, leaving the government unable to pay war debts or fund itself, and explain that the Constitution granted Congress the power to tax directly. Other valid pairs include the lack of a strong executive/judiciary under the Articles versus the creation of the presidency and federal courts, or the unanimous-consent amendment requirement versus the Constitution's more flexible amendment process.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific, accurate weakness of the Articles of Confederation", "keywords": ["taxation", "executive", "amendment", "unanimous"], "points": 1},
                {"point": "Explains a specific constitutional provision that addressed that weakness", "keywords": ["Congress", "president", "judiciary", "ratify"], "points": 2},
                {"point": "Correctly distinguishes the two governing documents rather than treating them as equivalent", "keywords": [], "points": 1},
            ]
        },
    },

    # Period 4: 1800-1848
    {
        "unit_name": "Period 4: 1800-1848",
        "topic_name": "The Rise of Political Parties and Democracy",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "The expansion of suffrage to nearly all white men by the 1830s was most directly driven by",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["overstates-inclusivity"],
        "options": [
            {"label": "A", "text": "the elimination of property requirements for voting in most states, reflecting growing democratic and egalitarian sentiment among white men.", "is_correct": True},
            {"label": "B", "text": "a constitutional amendment guaranteeing universal suffrage regardless of race, gender, or property.", "is_correct": False},
            {"label": "C", "text": "the Supreme Court's ruling that all property requirements for voting were unconstitutional.", "is_correct": False},
            {"label": "D", "text": "pressure from newly enfranchised women voters demanding broader male suffrage.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: many states removed property qualifications during this period, driven by Jacksonian-era democratic ideals, though this expansion applied to white men only.", "misconception_tag": None},
            {"option_label": "B", "explanation": "No such amendment existed in this period; suffrage expansion was accomplished at the state level and remained limited to white men.", "misconception_tag": "overstates-inclusivity"},
            {"option_label": "C", "explanation": "This change occurred through state constitutional revisions and legislation, not a Supreme Court ruling.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "Women did not gain the vote until 1920, so they could not have driven this earlier change.", "misconception_tag": "conflates-two-different-time-periods"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 4: 1800-1848",
        "topic_name": "The Cotton Revolution and the Expansion of Slavery",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "The invention of the cotton gin in 1793 most directly contributed to which of the following developments in the antebellum South?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["reverses-cause-and-effect"],
        "options": [
            {"label": "A", "text": "A steady decline in the demand for enslaved labor as cotton processing became mechanized.", "is_correct": False},
            {"label": "B", "text": "The rapid decline of slavery in the Upper South as cotton cultivation moved westward.", "is_correct": False},
            {"label": "C", "text": "A shift in the Southern economy away from agriculture entirely and toward manufacturing.", "is_correct": False},
            {"label": "D", "text": "A dramatic increase in the profitability of short-staple cotton, fueling westward expansion of plantation slavery into the Deep South.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reverses the actual effect; demand for enslaved labor increased, since the gin made cotton processing faster but cultivation and harvesting still required intensive manual labor.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "B", "explanation": "The Upper South remained tied to slavery, in part supplying enslaved people sold to the expanding Deep South cotton economy.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "The South remained overwhelmingly agricultural and increasingly dependent on cotton, not manufacturing.", "misconception_tag": "overgeneralizes-regional-scope"},
            {"option_label": "D", "explanation": "Correct: the gin made short-staple cotton highly profitable, driving the expansion of plantation agriculture and slavery into Alabama, Mississippi, and beyond.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 4: 1800-1848",
        "topic_name": "Religious Revival and Reform Movements",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "The Second Great Awakening of the early nineteenth century directly contributed to which of the following developments?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "A decline in religious participation across the United States.", "is_correct": False},
            {"label": "B", "text": "The growth of reform movements, including abolitionism and temperance, inspired by religious ideas about individual moral responsibility.", "is_correct": True},
            {"label": "C", "text": "The establishment of an official state church for the United States.", "is_correct": False},
            {"label": "D", "text": "The end of Protestant denominational diversity in the United States.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "The Second Great Awakening was a period of religious revival and growth, not decline.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "B", "explanation": "Correct: revivalist emphasis on individual salvation and moral perfectionism fueled reform movements such as abolitionism, temperance, and education reform.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The United States never established an official state church; the First Amendment prohibited this.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "The Awakening actually increased denominational diversity through the growth of Methodists, Baptists, and other groups.", "misconception_tag": "reverses-cause-and-effect"},
        ],
        "rubric_json": None,
    },

    # Period 5: 1844-1877
    {
        "unit_name": "Period 5: 1844-1877",
        "topic_name": "Manifest Destiny and Continued Expansion",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "The concept of \"Manifest Destiny\" as used by American expansionists in the 1840s referred to the belief that",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "the United States was destined by God and its national character to expand across the North American continent.", "is_correct": True},
            {"label": "B", "text": "the United States should focus exclusively on economic development within its existing 1840 borders.", "is_correct": False},
            {"label": "C", "text": "Native American nations had a natural right to permanent sovereignty over their ancestral lands.", "is_correct": False},
            {"label": "D", "text": "European powers should be invited to jointly govern North American territories.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: Manifest Destiny was the belief, popularized by John O'Sullivan, that American expansion across the continent was inevitable and divinely sanctioned.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This is the opposite of Manifest Destiny, which explicitly promoted expansion beyond existing borders.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "Manifest Destiny ideology largely disregarded or actively undermined Native land claims rather than affirming them.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "Manifest Destiny was about unilateral American expansion, not joint European governance.", "misconception_tag": "invents-fictional-policy"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 5: 1844-1877",
        "topic_name": "The Civil War",
        "type": "mcq",
        "difficulty": 4,
        "prompt": "The Battle of Antietam (1862) is considered a significant turning point in the Civil War primarily because it",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["conflates-two-different-time-periods"],
        "options": [
            {"label": "A", "text": "resulted in the unconditional surrender of the Confederate army.", "is_correct": False},
            {"label": "B", "text": "convinced Britain and France to formally recognize the Confederacy as an independent nation.", "is_correct": False},
            {"label": "C", "text": "gave President Lincoln the political opportunity to issue the preliminary Emancipation Proclamation after a Union tactical victory.", "is_correct": True},
            {"label": "D", "text": "marked the final battle of the war in the Eastern theater.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Antietam did not end the war; Confederate forces continued fighting for nearly three more years.", "misconception_tag": "conflates-two-different-time-periods"},
            {"option_label": "B", "explanation": "The Union victory at Antietam actually discouraged British and French recognition of the Confederacy, the opposite of this claim.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "Correct: the narrow Union victory gave Lincoln the political standing to announce the preliminary Emancipation Proclamation in September 1862.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Major Eastern theater battles, including Gettysburg, occurred after Antietam.", "misconception_tag": "conflates-two-different-time-periods"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 5: 1844-1877",
        "topic_name": "Reconstruction",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Briefly explain ONE way Radical Reconstruction (1867-1877) expanded rights for African Americans in the South, and briefly explain ONE way white Southern resistance limited those gains by the end of Reconstruction.",
        "correct_answer": "A strong response cites a specific gain such as the Fourteenth or Fifteenth Amendment, Black political officeholding, or the Freedmen's Bureau, and a specific limitation such as Black Codes, the Ku Klux Klan's violence, or the Compromise of 1877 ending federal enforcement.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation", "evidence"],
        "misconception_tags": ["overstates-permanence-of-gains"],
        "explanations": [
            {"option_label": None, "explanation": "A strong response might explain that the Fifteenth Amendment (1870) guaranteed Black men the right to vote, enabling many African Americans to hold local and state office in the South, and then explain that white paramilitary violence, such as that of the Ku Klux Klan, alongside the withdrawal of federal troops after the Compromise of 1877, undermined enforcement of these rights and enabled the rise of Jim Crow. Responses that treat Reconstruction gains as permanent and unchallenged miss the key tension the CED emphasizes.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific right or gain expanded during Radical Reconstruction", "keywords": ["Fourteenth Amendment", "Fifteenth Amendment", "Freedmen's Bureau", "officeholding"], "points": 1},
                {"point": "Identifies a specific mechanism of white Southern resistance that limited those gains", "keywords": ["Black Codes", "Ku Klux Klan", "redemption", "Compromise of 1877"], "points": 2},
                {"point": "Recognizes that Reconstruction-era gains were contested and rolled back rather than permanent", "keywords": [], "points": 1},
            ]
        },
    },

    # Period 6: 1865-1898
    {
        "unit_name": "Period 6: 1865-1898",
        "topic_name": "Industrialization and Big Business",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Andrew Carnegie's use of vertical integration in the steel industry involved",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": ["conflates-two-different-systems"],
        "options": [
            {"label": "A", "text": "buying out all of his direct competitors in the steel-making business.", "is_correct": False},
            {"label": "B", "text": "controlling every stage of production, from raw materials like iron ore and coal to transportation and finished steel manufacturing.", "is_correct": True},
            {"label": "C", "text": "forming a legal trust that fixed prices across multiple unrelated industries.", "is_correct": False},
            {"label": "D", "text": "relying entirely on federal government subsidies to fund his steel mills.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This describes horizontal integration (buying out competitors in the same stage of production), which is a different strategy than Carnegie's approach.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "B", "explanation": "Correct: vertical integration meant Carnegie controlled the entire supply chain, reducing costs and reliance on outside suppliers.", "misconception_tag": None},
            {"option_label": "C", "explanation": "This describes a trust structure like Standard Oil's, not Carnegie's vertical integration model, and conflates two distinct business strategies.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "D", "explanation": "Carnegie's steel empire was built through private capital and reinvested profits, not primarily government subsidies.", "misconception_tag": "invents-fictional-policy"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 6: 1865-1898",
        "topic_name": "Immigration and Urbanization",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "The \"New Immigration\" of the late nineteenth century primarily consisted of immigrants arriving from",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["comparison"],
        "misconception_tags": ["conflates-two-different-time-periods"],
        "options": [
            {"label": "A", "text": "Northern and Western Europe, continuing the same pattern as earlier in the century.", "is_correct": False},
            {"label": "B", "text": "Latin America and the Caribbean exclusively.", "is_correct": False},
            {"label": "C", "text": "Southern and Eastern Europe, including Italy, Poland, and Russia.", "is_correct": True},
            {"label": "D", "text": "Western Africa, as part of a continuation of the transatlantic slave trade.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This describes the 'Old Immigration' pattern from earlier in the nineteenth century, not the New Immigration.", "misconception_tag": "conflates-two-different-time-periods"},
            {"option_label": "B", "explanation": "Latin American and Caribbean immigration was not the dominant pattern of this era's New Immigration.", "misconception_tag": "overgeneralizes-regional-scope"},
            {"option_label": "C", "explanation": "Correct: from roughly 1880-1920, immigration shifted heavily toward Southern and Eastern Europe.", "misconception_tag": None},
            {"option_label": "D", "explanation": "The transatlantic slave trade had been legally abolished decades earlier and was unrelated to voluntary immigration patterns.", "misconception_tag": "conflates-two-different-time-periods"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 6: 1865-1898",
        "topic_name": "Labor and the Rise of Unions",
        "type": "mcq",
        "difficulty": 5,
        "prompt": "A key difference between the Knights of Labor and the American Federation of Labor (AFL) was that",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["comparison"],
        "misconception_tags": ["conflates-two-different-systems"],
        "options": [
            {"label": "A", "text": "the Knights of Labor focused exclusively on skilled craft workers, while the AFL sought to organize all workers regardless of skill.", "is_correct": False},
            {"label": "B", "text": "the AFL was founded before the Knights of Labor and largely dissolved after the Knights' formation.", "is_correct": False},
            {"label": "C", "text": "the Knights of Labor achieved greater long-term membership and influence than the AFL by the early twentieth century.", "is_correct": False},
            {"label": "D", "text": "the AFL organized primarily skilled workers by craft and focused on concrete goals like wages and hours, while the Knights of Labor sought to include unskilled workers and pursue broader social reform.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This reverses the actual organizing strategies of the two groups.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "B", "explanation": "The Knights of Labor (founded 1869) predated the AFL (founded 1886), reversing the correct chronology.", "misconception_tag": "conflates-two-different-time-periods"},
            {"option_label": "C", "explanation": "The AFL outlasted and ultimately overshadowed the Knights of Labor, which declined sharply after the Haymarket Affair.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "Correct: the AFL under Samuel Gompers pursued practical, craft-based 'bread and butter' unionism, while the Knights pursued a more inclusive and reform-oriented vision.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },

    # Period 7: 1890-1945
    {
        "unit_name": "Period 7: 1890-1945",
        "topic_name": "The Progressive Movement",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "Progressive Era reformers who supported the passage of the Seventeenth Amendment (1913) primarily aimed to",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "increase direct democracy by allowing voters, rather than state legislatures, to elect U.S. senators.", "is_correct": True},
            {"label": "B", "text": "abolish the Electoral College entirely in presidential elections.", "is_correct": False},
            {"label": "C", "text": "grant women the right to vote in federal elections.", "is_correct": False},
            {"label": "D", "text": "establish a federal minimum wage for all industrial workers.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: the Seventeenth Amendment shifted senatorial elections from state legislatures to direct popular vote, reflecting Progressive support for direct democracy.", "misconception_tag": None},
            {"option_label": "B", "explanation": "The Electoral College was not addressed by the Seventeenth Amendment and remains in place.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "C", "explanation": "Women's suffrage was achieved by the Nineteenth Amendment in 1920, a separate reform.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "D", "explanation": "A federal minimum wage was not established until the Fair Labor Standards Act of 1938.", "misconception_tag": "conflates-two-different-time-periods"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 7: 1890-1945",
        "topic_name": "The Great Depression and the New Deal",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Which of the following best characterizes a major criticism of the New Deal from the political left in the 1930s?",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["argumentation"],
        "misconception_tags": ["overstates-uniformity"],
        "options": [
            {"label": "A", "text": "That the New Deal spent far too much federal money and should be immediately eliminated in favor of a fully unregulated market.", "is_correct": False},
            {"label": "B", "text": "That the New Deal did not go far enough in redistributing wealth and providing economic security, as argued by figures like Huey Long.", "is_correct": True},
            {"label": "C", "text": "That the New Deal unconstitutionally abolished the Supreme Court's power of judicial review.", "is_correct": False},
            {"label": "D", "text": "That the New Deal should have focused solely on foreign policy rather than domestic recovery.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This describes a conservative or business-oriented criticism, not one from the political left.", "misconception_tag": "conflates-two-different-systems"},
            {"option_label": "B", "explanation": "Correct: critics like Huey Long (Share Our Wealth) and Francis Townsend argued the New Deal was too limited in redistributing wealth and aiding the poor and elderly.", "misconception_tag": None},
            {"option_label": "C", "explanation": "The New Deal did not abolish judicial review; FDR's later court-packing plan targeted the Court's composition, not judicial review itself, and that plan failed.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "The New Deal was fundamentally a domestic economic recovery program, not a foreign policy initiative.", "misconception_tag": "misidentifies-economic-motive"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 7: 1890-1945",
        "topic_name": "World War II",
        "type": "frq",
        "difficulty": 3,
        "prompt": "Briefly explain ONE specific way World War II mobilization changed the roles of women or minorities on the home front, and briefly explain ONE piece of evidence that supports your explanation.",
        "correct_answer": "A strong response identifies a specific change, such as women entering wartime industrial jobs (e.g., 'Rosie the Riveter') or African Americans migrating to war-production cities, and supports it with specific evidence like the Double V Campaign or the growth of female factory employment.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["evidence", "continuity-and-change"],
        "misconception_tags": ["overstates-permanence-of-gains"],
        "explanations": [
            {"option_label": None, "explanation": "A strong response might explain that wartime labor shortages drew millions of women into industrial jobs previously reserved for men, symbolized by the 'Rosie the Riveter' campaign, and support this with evidence such as sharp increases in female employment in aircraft and shipbuilding plants. Alternatively, a response could explain that African Americans migrated to Northern and Western war-production centers as part of the Second Great Migration, citing the Double V Campaign as evidence of demands for equality abroad and at home. Strong responses should avoid implying these wartime gains were immediately permanent after 1945.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific change in the roles of women or minorities during WWII mobilization", "keywords": ["Rosie the Riveter", "Double V", "Great Migration", "industrial jobs"], "points": 1},
                {"point": "Provides specific, accurate historical evidence supporting the explanation", "keywords": ["aircraft", "shipbuilding", "migration", "campaign"], "points": 2},
                {"point": "Does not overstate the permanence of wartime gains after 1945", "keywords": [], "points": 1},
            ]
        },
    },

    # Period 8: 1945-1980
    {
        "unit_name": "Period 8: 1945-1980",
        "topic_name": "The Cold War and Containment",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "The policy of \"containment,\" as articulated by George Kennan and adopted by the Truman administration, called for the United States to",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "prevent the further spread of Soviet communism to new countries without necessarily attempting to roll back existing communist governments.", "is_correct": True},
            {"label": "B", "text": "pursue the immediate military invasion of the Soviet Union to eliminate communism.", "is_correct": False},
            {"label": "C", "text": "withdraw from all international alliances and adopt a policy of strict isolationism.", "is_correct": False},
            {"label": "D", "text": "formally merge the U.S. and Western European economies into a single political union.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: containment sought to stop the spread of communism through diplomatic, economic, and military means, short of direct war with the USSR.", "misconception_tag": None},
            {"option_label": "B", "explanation": "Containment explicitly avoided direct military conflict with the Soviet Union, distinguishing it from a rollback or invasion strategy.", "misconception_tag": "misidentifies-economic-motive"},
            {"option_label": "C", "explanation": "Containment involved active international engagement, such as NATO and the Marshall Plan, the opposite of isolationism.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "The U.S. built alliances like NATO and provided economic aid but did not merge into a political union with Europe.", "misconception_tag": "invents-fictional-policy"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 8: 1945-1980",
        "topic_name": "The Civil Rights Movement",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "The Supreme Court's decision in Brown v. Board of Education (1954) most directly",
        "correct_answer": "C",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["overstates-immediate-impact"],
        "options": [
            {"label": "A", "text": "immediately ended racial segregation in all Southern public schools within one year.", "is_correct": False},
            {"label": "B", "text": "upheld the 'separate but equal' doctrine established in Plessy v. Ferguson.", "is_correct": False},
            {"label": "C", "text": "declared state-sponsored segregation in public schools unconstitutional, overturning the legal basis for 'separate but equal' in education.", "is_correct": True},
            {"label": "D", "text": "granted the federal government the power to desegregate private businesses nationwide.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Implementation was slow and met with significant resistance (e.g., 'massive resistance'), not immediate compliance.", "misconception_tag": "overstates-immediate-impact"},
            {"option_label": "B", "explanation": "Brown overturned rather than upheld Plessy's 'separate but equal' doctrine in public education.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "Correct: Brown ruled that segregated public schools were inherently unequal, overturning Plessy's application to education.", "misconception_tag": None},
            {"option_label": "D", "explanation": "Brown addressed public education specifically; desegregation of private businesses was later addressed by the Civil Rights Act of 1964.", "misconception_tag": "conflates-two-different-systems"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 8: 1945-1980",
        "topic_name": "The Vietnam War and Social Movements of the 1960s-70s",
        "type": "frq",
        "difficulty": 4,
        "prompt": "Briefly explain ONE reason opposition to the Vietnam War grew among Americans between 1965 and 1975, and briefly explain ONE effect that this growing opposition had on U.S. politics or policy.",
        "correct_answer": "A strong response cites a specific cause such as rising casualties, the draft, or media coverage (e.g., the Tet Offensive), and a specific effect such as Nixon's Vietnamization policy, the War Powers Act, or LBJ's decision not to seek reelection.",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation", "evidence"],
        "misconception_tags": ["overstates-single-cause"],
        "explanations": [
            {"option_label": None, "explanation": "A strong response might explain that the Tet Offensive of 1968, broadcast on television, undermined public confidence in official claims of imminent victory, and connect this to an effect such as President Johnson's decision not to seek reelection or Congress's later passage of the War Powers Act of 1973 to limit presidential war-making authority. Other valid causes include rising draft calls and casualty counts; other valid effects include Nixon's policy of Vietnamization.", "misconception_tag": None},
        ],
        "rubric_json": {
            "checklist": [
                {"point": "Identifies a specific, accurate cause of growing antiwar opposition", "keywords": ["Tet Offensive", "draft", "casualties", "media"], "points": 1},
                {"point": "Explains a specific political or policy effect of that opposition", "keywords": ["War Powers Act", "Vietnamization", "Johnson", "reelection"], "points": 2},
                {"point": "Presents the relationship as one of multiple contributing causes rather than a single monocausal explanation", "keywords": [], "points": 1},
            ]
        },
    },

    # Period 9: 1980-Present
    {
        "unit_name": "Period 9: 1980-Present",
        "topic_name": "The Reagan Revolution and Conservative Resurgence",
        "type": "mcq",
        "difficulty": 2,
        "prompt": "\"Reaganomics,\" the economic approach associated with President Ronald Reagan in the 1980s, was centered on the idea that",
        "correct_answer": "B",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["contextualization"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "raising taxes on all income brackets would generate the revenue needed to expand social welfare programs.", "is_correct": False},
            {"label": "B", "text": "cutting taxes, particularly for businesses and higher earners, and reducing regulation would stimulate economic growth.", "is_correct": True},
            {"label": "C", "text": "the federal government should nationalize major industries to ensure economic stability.", "is_correct": False},
            {"label": "D", "text": "the United States should adopt a fully planned, centrally controlled economy.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "This is the opposite of Reaganomics, which emphasized tax cuts rather than broad tax increases.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "B", "explanation": "Correct: supply-side 'Reaganomics' emphasized tax cuts, deregulation, and reduced government spending on social programs to spur growth.", "misconception_tag": None},
            {"option_label": "C", "explanation": "Reagan's policies moved toward deregulation and privatization, not nationalization of industry.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "Reagan's approach was a free-market strategy fundamentally opposed to centrally planned economics.", "misconception_tag": "reverses-cause-and-effect"},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 9: 1980-Present",
        "topic_name": "The End of the Cold War",
        "type": "mcq",
        "difficulty": 3,
        "prompt": "Which of the following was a significant factor contributing to the collapse of the Soviet Union by 1991?",
        "correct_answer": "D",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["causation"],
        "misconception_tags": ["overstates-single-cause"],
        "options": [
            {"label": "A", "text": "A sudden U.S. military invasion of Soviet territory in the late 1980s.", "is_correct": False},
            {"label": "B", "text": "The Soviet Union's decision to adopt a fully capitalist economy a decade before its collapse.", "is_correct": False},
            {"label": "C", "text": "A unanimous vote by the United Nations to dissolve the Soviet government.", "is_correct": False},
            {"label": "D", "text": "Mikhail Gorbachev's reform policies of glasnost and perestroika, combined with economic stagnation and rising nationalist movements within Soviet republics.", "is_correct": True},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "No such U.S. invasion of Soviet territory occurred; the Cold War ended without direct military conflict between the superpowers.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "B", "explanation": "The USSR did not adopt full capitalism before its collapse; economic reforms under Gorbachev were more limited and came shortly before the breakup.", "misconception_tag": "conflates-two-different-time-periods"},
            {"option_label": "C", "explanation": "The United Nations did not vote to dissolve the Soviet government; the collapse resulted from internal political and economic pressures.", "misconception_tag": "invents-fictional-policy"},
            {"option_label": "D", "explanation": "Correct: Gorbachev's reforms, combined with long-term economic problems and nationalist independence movements in Soviet republics, led to the USSR's dissolution.", "misconception_tag": None},
        ],
        "rubric_json": None,
    },
    {
        "unit_name": "Period 9: 1980-Present",
        "topic_name": "Globalization and the Technological Revolution",
        "type": "mcq",
        "difficulty": 1,
        "prompt": "The growth of globalization in the American economy since the 1980s has been most closely associated with which of the following trends?",
        "correct_answer": "A",
        "source": "human_written",
        "validation_status": "approved",
        "skill_tags": ["continuity-and-change"],
        "misconception_tags": [],
        "options": [
            {"label": "A", "text": "The decline of domestic manufacturing employment as production shifted to other countries with lower labor costs.", "is_correct": True},
            {"label": "B", "text": "A steady increase in domestic manufacturing jobs as trade barriers rose worldwide.", "is_correct": False},
            {"label": "C", "text": "The complete elimination of the American service sector.", "is_correct": False},
            {"label": "D", "text": "A total ban on international trade agreements after 1980.", "is_correct": False},
        ],
        "explanations": [
            {"option_label": "A", "explanation": "Correct: globalization and free trade agreements contributed to deindustrialization as manufacturing moved abroad.", "misconception_tag": None},
            {"option_label": "B", "explanation": "This reverses the actual trend; trade barriers generally fell (e.g., NAFTA) rather than rose, and manufacturing jobs declined.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "C", "explanation": "The service sector grew substantially during this period rather than disappearing.", "misconception_tag": "reverses-cause-and-effect"},
            {"option_label": "D", "explanation": "The U.S. entered into more trade agreements, such as NAFTA (1994), not fewer.", "misconception_tag": "reverses-cause-and-effect"},
        ],
        "rubric_json": None,
    },
]
