import { test, expect } from "@playwright/test";
import { clerk } from "@clerk/testing/playwright";
import { createTestUser } from "./fixtures/testUser";

test.describe("Candidate English Language exam rehearsal", () => {
  test.skip(!process.env.CLERK_SECRET_KEY || process.env.E2E_INCLUDE_CANDIDATES !== "1", "requires real Clerk and an explicitly seeded disposable candidate database");
  test.describe.configure({ timeout: 90_000 });
  let user: Awaited<ReturnType<typeof createTestUser>>;
  test.beforeAll(async () => { user = await createTestUser(); });
  test.afterAll(async () => { await user?.remove(); });
  test("launch, persist, lock, write, submit, and self-review", async ({ page }, testInfo) => {
    const failures: string[] = [];
    page.on("response", response => { if (response.status() >= 500) failures.push(new URL(response.url()).pathname); });
    await page.goto("/");
    await clerk.signIn({ page, emailAddress: user.email });
    await page.goto("/onboarding");
    await page.getByRole("radio", { name: /Professional/ }).click();
    await page.getByRole("button", { name: "Continue" }).click();
    await page.getByRole("button", { name: "AP English Language and Composition", exact: true }).click();
    await page.getByRole("button", { name: "Continue" }).click();
    await page.getByRole("button", { name: "Start studying" }).click();
    await expect(page).toHaveURL(/\/dashboard/);
    await page.goto("/subjects");
    await page.getByText("AP English Language and Composition", { exact: true }).locator("../..").getByRole("link", { name: "Open course" }).click();
    await page.getByRole("button", { name: "Start Form A" }).click();
    await expect(page).toHaveURL(/\/exams\/\d+$/);
    const examUrl = page.url();
    await expect(page.getByRole("timer")).toBeVisible();
    const choice = page.locator("main button").filter({ hasText: /^[A-D]\./ }).first();
    const choiceText = await choice.textContent();
    await choice.click();
    await page.getByRole("button", { name: "Save now" }).click();
    await expect(page.getByRole("status")).toHaveText("Saved to your account");
    await page.reload();
    await expect(page.getByRole("button", { pressed: true }).filter({ hasText: choiceText! })).toBeVisible();
    await page.goto("/practice");
    await page.getByRole("link", { name: "Resume session" }).first().click();
    await expect(page).toHaveURL(examUrl);
    await page.getByRole("button", { name: "Finish section", exact: true }).click();
    await expect(page.getByText(/44 unanswered\. Closing this section/)).toBeVisible();
    await page.getByRole("button", { name: "Save and close section" }).click();
    await expect(page.getByText("Take a breath.")).toBeVisible();
    await expect(page.getByRole("timer")).toHaveCount(0);
    await page.getByRole("button", { name: "Begin Free response" }).click();
    await expect(page.getByRole("textbox", { name: "Your response" })).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("essay-mobile.png"), fullPage: true });
    const essay = "The city should prioritize access and review the pilot carefully. Source D identifies different mobility needs, while Source C reports benefits and costs without establishing causation. A reversible trial should measure both rather than assuming that more visitors benefit everyone equally.";
    await page.getByRole("textbox", { name: "Your response" }).fill(essay);
    await page.getByRole("button", { name: "Save now" }).click();
    await expect(page.getByRole("status")).toHaveText("Saved to your account");
    await page.reload();
    await expect(page.getByRole("textbox", { name: "Your response" })).toHaveValue(essay);
    await page.getByRole("button", { name: "Finish section", exact: true }).click();
    await page.getByRole("button", { name: "Save and close section" }).click();
    await expect(page).toHaveURL(/\/practice\/results\/\d+$/);
    await expect(page.getByText(/3 responses use rubric self-review/)).toBeVisible();
    // Scope to the smallest review container, not ancestor result wrappers.
    const firstReview = page.getByRole("heading", { name: "Your rubric review" }).first().locator("../..");
    await firstReview.getByRole("group").nth(0).getByRole("radio").nth(1).check();
    await firstReview.getByRole("group").nth(1).getByRole("radio").nth(2).check();
    await firstReview.getByRole("group").nth(2).getByRole("radio").nth(0).check();
    await firstReview.getByRole("button", { name: "Save rubric review" }).click();
    await expect(firstReview.getByRole("status")).toHaveText("Saved self-assessment: 3/6 points.");
    await page.reload();
    await expect(page.getByText("Saved self-assessment: 3/6 points.")).toBeVisible();
    expect(failures).toEqual([]);
  });
});
